/*
@license

dhtmlxGantt v.4.0.10 Professional
This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t.config.quickinfo_buttons=["icon_delete","icon_edit"],t.config.quick_info_detached=!0,t.config.show_quick_info=!0,t.attachEvent("onTaskClick",function(e){return t.showQuickInfo(e),!0}),function(){for(var e=["onEmptyClick","onViewChange","onLightbox","onBeforeTaskDelete","onBeforeDrag"],i=function(){return t._hideQuickInfo(),!0},n=0;n<e.length;n++)t.attachEvent(e[n],i)}(),t.templates.quick_info_title=function(t,e,i){return i.text.substr(0,50)},t.templates.quick_info_content=function(t,e,i){
return i.details||i.text},t.templates.quick_info_date=function(e,i,n){return t.templates.task_time(e,i,n)},t.templates.quick_info_class=function(t,e,i){return""},t.showQuickInfo=function(e){if(e!=this._quick_info_box_id&&this.config.show_quick_info){this.hideQuickInfo(!0);var i=this._get_event_counter_part(e);i&&(this._quick_info_box=this._init_quick_info(i,e),this._quick_info_box.className=t._prepare_quick_info_classname(e),this._fill_quick_data(e),this._show_quick_info(i))}},t._hideQuickInfo=function(){
t.hideQuickInfo()},t.hideQuickInfo=function(e){var i=this._quick_info_box;if(this._quick_info_box_id=0,i&&i.parentNode){if(t.config.quick_info_detached)return i.parentNode.removeChild(i);i.className+=" gantt_qi_hidden","auto"==i.style.right?i.style.left="-350px":i.style.right="-350px",e&&i.parentNode.removeChild(i)}},t.event(window,"keydown",function(e){27==e.keyCode&&t.hideQuickInfo()}),t._show_quick_info=function(e){var i=t._quick_info_box;if(t.config.quick_info_detached){i.parentNode&&"#document-fragment"!=i.parentNode.nodeName.toLowerCase()||t.$task_data.appendChild(i);
var n=i.offsetWidth,a=i.offsetHeight,s=this.getScrollState(),r=this.$task.offsetWidth+s.x-n;i.style.left=Math.min(Math.max(s.x,e.left-e.dx*(n-e.width)),r)+"px",i.style.top=e.top-(e.dy?a:-e.height)-25+"px"}else i.style.top="20px",1==e.dx?(i.style.right="auto",i.style.left="-300px",setTimeout(function(){i.style.left="-10px"},1)):(i.style.left="auto",i.style.right="-300px",setTimeout(function(){i.style.right="-10px"},1)),i.className+=" gantt_qi_"+(1==e.dx?"left":"right"),t._obj.appendChild(i)},t._prepare_quick_info_classname=function(e){
var i=t.getTask(e),n="gantt_cal_quick_info",a=this.templates.quick_info_class(i.start_date,i.end_date,i);return a&&(n+=" "+a),n},t._init_quick_info=function(e,i){var n=t.getTask(i);if("boolean"==typeof this._quick_info_readonly&&this._is_readonly(n)!==this._quick_info_readonly&&(t.hideQuickInfo(!0),this._quick_info_box=null),this._quick_info_readonly=this._is_readonly(n),!this._quick_info_box){var a=this._quick_info_box=document.createElement("div"),s='<div class="gantt_cal_qi_title"><div class="gantt_cal_qi_tcontent"></div><div  class="gantt_cal_qi_tdate"></div></div><div class="gantt_cal_qi_content"></div>';
s+='<div class="gantt_cal_qi_controls">';for(var r=t.config.quickinfo_buttons,o={icon_delete:!0,icon_edit:!0},_=0;_<r.length;_++)this._quick_info_readonly&&o[r[_]]||(s+='<div class="gantt_qi_big_icon '+r[_]+'" title="'+t.locale.labels[r[_]]+"\"><div class='gantt_menu_icon "+r[_]+"'></div><div>"+t.locale.labels[r[_]]+"</div></div>");s+="</div>",a.innerHTML=s,t.event(a,"click",function(e){e=e||event,t._qi_button_click(e.target||e.srcElement)}),t.config.quick_info_detached&&t.event(t.$task_data,"scroll",function(){
t.hideQuickInfo()})}return this._quick_info_box},t._qi_button_click=function(e){var i=t._quick_info_box;if(e&&e!=i){var n=e.className;if(-1!=n.indexOf("_icon")){var a=t._quick_info_box_id;t.$click.buttons[n.split(" ")[1].replace("icon_","")](a)}else t._qi_button_click(e.parentNode)}},t._get_event_counter_part=function(e){for(var i=t.getTaskNode(e),n=0,a=0,s=i;s&&"gantt_task"!=s.className;)n+=s.offsetLeft,a+=s.offsetTop,s=s.offsetParent;var r=this.getScrollState();if(s){var o=n+i.offsetWidth/2-r.x>t._x/2?1:0,_=a+i.offsetHeight/2-r.y>t._y/2?1:0;
return{left:n,top:a,dx:o,dy:_,width:i.offsetWidth,height:i.offsetHeight}}return 0},t._fill_quick_data=function(e){var i=t.getTask(e),n=t._quick_info_box;t._quick_info_box_id=e;var a=n.firstChild.firstChild;a.innerHTML=t.templates.quick_info_title(i.start_date,i.end_date,i);var s=a.nextSibling;s.innerHTML=t.templates.quick_info_date(i.start_date,i.end_date,i);var r=n.firstChild.nextSibling;r.innerHTML=t.templates.quick_info_content(i.start_date,i.end_date,i)}});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_quick_info.js.map