 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 42300'   WHERE farrms_field_id= 'arbitration'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10018'   WHERE farrms_field_id= 'block_define_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 40400'   WHERE farrms_field_id= 'buyer_seller_option'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 17200'   WHERE farrms_field_id= 'confirm_status_type'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10092'   WHERE farrms_field_id= 'crop_year'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 41000'   WHERE farrms_field_id= 'cycle'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 475'   WHERE farrms_field_id= 'deal_category_value_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 5600'   WHERE farrms_field_id= 'deal_status'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 40200'   WHERE farrms_field_id= 'detail_inco_terms'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id =1600'   WHERE farrms_field_id= 'detail_pricing'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 40300'   WHERE farrms_field_id= 'governing_law'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 40200'   WHERE farrms_field_id= 'inco_terms'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 17300'   WHERE farrms_field_id= 'internal_desk_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id =39800'   WHERE farrms_field_id= 'internal_portfolio_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 20000'   WHERE farrms_field_id= 'payment_term'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id =1600'   WHERE farrms_field_id= 'pricing'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 4100'   WHERE farrms_field_id= 'product_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_staticDataValues @flag = ''h'', @type_id = 18200'   WHERE farrms_field_id= 'profile_code'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_staticDataValues @flag = ''h'', @type_id = 18300'   WHERE farrms_field_id= 'pv_party'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_staticDataValues @flag = ''h'', @type_id = 10002'   WHERE farrms_field_id= 'state_value_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_staticDataValues @flag = ''h'', @type_id = 10002'   WHERE farrms_field_id= 'status'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 18100'   WHERE farrms_field_id= 'category'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 978'   WHERE farrms_field_id= 'granularity_id'
 
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Receiving Counterparty'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Shipping Counterparty'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'nn'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Owner 1'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Owner 2'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_minor_location ''o'''   WHERE Field_label= 'Purchase Location'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Actual Yearly Price'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Actual Float Price'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Liquification Fee Index'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Pricing Index'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 31400'   WHERE Field_label= 'Priority'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'', @type_of_entity = 301994'   WHERE Field_label= 'Pipeline'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_contract_group @flag  = ''r'', @contract_name = ''broker''' WHERE Field_label= 'Broker Contract'

 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_commodity_maintain ''a'''   WHERE Field_label= 'Commodity'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_contract_group ''r'''   WHERE Field_label= 'Contract'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_contract_group ''r'''   WHERE Field_label= 'Reporting Contract'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_contract_group ''r'''   WHERE Field_label= 'Sell Payments Terms'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Owner 1'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''c'''   WHERE Field_label= 'Owner 2'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location ''o'''   WHERE Field_label= 'Location'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location ''o'''   WHERE Field_label= 'Purchase Location'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location ''o'''   WHERE Field_label= 'Receipt Location'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location ''o'''   WHERE Field_label= 'Delivery Location'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Curve'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Curve ID'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Actual Yearly Price'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Actual Float Price'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Avg1 Curve 1'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Avg1 Curve 2'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Avg2 Curve 3'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Avg2 Curve 4'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'NMGRT Tax Rate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Compensating Tax Rate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'County Tax Rate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'City Tax Rate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Pre Cascade Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Post Cascade Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Liquification Fee Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Pricing Index 1'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'TAX'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'''   WHERE Field_label= 'Pricing Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 15000'   WHERE Field_label= 'Tier_UDF'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 32400'   WHERE Field_label= 'Rounding Method'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10023'   WHERE Field_label= 'Fuel'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 17300'   WHERE Field_label= 'Profile'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10019'   WHERE Field_label= 'Charge Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 11150'   WHERE Field_label= 'Region'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10004'   WHERE Field_label= 'VAT Code Sale'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10004'   WHERE Field_label= 'VAT Code Buy'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 39000'   WHERE Field_label= 'Series Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 39500'   WHERE Field_label= 'Generation Category'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 400'   WHERE Field_label= 'Transaction Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10004'   WHERE Field_label= 'TAX CODE'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 27000'   WHERE Field_label= 'Product Group'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29800'   WHERE Field_label= 'VAT GL Account'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29800'   WHERE Field_label= 'VAT GL Account Buy'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 14000'   WHERE Field_label= 'Country'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10019'   WHERE Field_label= 'Products'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29800'   WHERE Field_label= 'Current Year General Ledger'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10005'   WHERE Field_label= 'Current Year Cost Center'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29900'   WHERE Field_label= 'Current Year Profit Center'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29800'   WHERE Field_label= 'Last Year General Ledger'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10005'   WHERE Field_label= 'Last Year Cost Center'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 29900'   WHERE Field_label= 'Last Year Profit Center'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 14000'   WHERE Field_label= 'Origin'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 40200'   WHERE Field_label= 'Buy Inco Terms'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 20000'   WHERE Field_label= 'Sell Inco Terms'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 20000'   WHERE Field_label= 'Buy Payments Terms'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'', @type_of_entity = 301994'   WHERE Field_label= 'Pipeline'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'''   WHERE Field_label= 'Operator'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10004'   WHERE Field_label= 'VAT Code'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10005'   WHERE Field_label= 'Cost Encoding'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10006'   WHERE Field_label= 'GL Account Balance For Estimate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 10004'   WHERE Field_label= 'VAT Code Estimate'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 32000'   WHERE Field_label= 'Priority'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_StaticDataValues @flag = ''h'', @type_id = 39600'   WHERE Field_label= 'GSP Group'
 UPDATE user_defined_fields_template SET sql_string= 'EXEC spa_contract_group @flag = ''r'', @contract_name = ''broker''' WHERE Field_label = 'Broker Contract'
 UPDATE user_defined_fields_template SET sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'',  @not_int_ext_flag = ''b''' WHERE Field_label = 'TRM Counterparty'
 UPDATE user_defined_fields_template SET sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'',  @is_active = ''y''' WHERE Field_label = 'Counterparty'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location @flag = ''o'', @location_name = ''Generator'', @location_name_group = 0'   WHERE Field_label= 'Generator'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_minor_location @flag = ''o'', @location_name = ''Storage'', @location_name_group = 1'   WHERE Field_label= 'Storage Location'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_counterparty_maintain ''p'',@static_type_name = ''Counterparty External ID'',@static_code = ''Entity Code''' WHERE Field_label= 'Entity'


 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'', @is_active = ''y'', @not_int_ext_flag = ''b'''   WHERE farrms_field_id= 'counterparty_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'', @is_active = ''y'', @int_ext_flag = ''i'''   WHERE farrms_field_id= 'internal_counterparty'


 