 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_book_maintain ''x'''   WHERE farrms_field_id= 'source_system_book_id1'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_book_maintain ''x'''   WHERE farrms_field_id= 'source_system_book_id2'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_book_maintain ''x'''   WHERE farrms_field_id= 'source_system_book_id3'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_book_maintain ''x'''   WHERE farrms_field_id= 'source_system_book_id4'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'adder_currency_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'broker_currency_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'fixed_cost_currency_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'fixed_price_currency_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'formula_currency_id'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'price_adder_currency2'
 UPDATE maintain_field_deal SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE farrms_field_id= 'settlement_currency'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_deal_type_maintain ''x'', ''y'''   WHERE farrms_field_id= 'deal_sub_type_type_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_deal_type_maintain ''x'''   WHERE farrms_field_id= 'source_deal_type_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_legal_entity_maintain ''s'''   WHERE farrms_field_id= 'legal_entity'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_traders_maintain ''x'''   WHERE farrms_field_id= 'trader_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_traders_maintain ''x'''   WHERE farrms_field_id= 'trader_id2'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE farrms_field_id= 'curve_id'
 UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE farrms_field_id= 'formula_curve_id'


 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_deal_type_maintain ''x'''   WHERE Field_label= 'Deal Type'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_product ''g'''   WHERE Field_label= 'Product ID'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_uom_maintain ''s'''   WHERE Field_label= 'Packaging UOM'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE Field_label= 'Exposure Index'
 UPDATE user_defined_deal_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE Field_label= 'Index'
 
 
 
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 51'   WHERE Field_label= 'Book ID2'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 50'   WHERE Field_label= 'Book'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 51'   WHERE Field_label= 'Counterparty Group'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 52'   WHERE Field_label= 'Instrument Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 53'   WHERE Field_label= 'Proj Index Group'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 53'   WHERE Field_label= 'Projection Index Group'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_book_maintain ''x'', @source_system_book_type_value_id = 50'   WHERE Field_label= 'Internal Portfolio'
 UPDATE user_defined_fields_template SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE Field_label= 'Currency'
 UPDATE user_defined_fields_template SET  sql_string= 'Exec spa_source_currency_maintain ''p'''   WHERE Field_label= 'Lag Price Currency'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_deal_type_maintain ''x'''   WHERE Field_label= 'Deal Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_deal_type_maintain ''x'''   WHERE Field_label= 'Deal Sub-Type'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_product ''g'''   WHERE Field_label= 'Product ID'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_traders_maintain ''x'''   WHERE Field_label= 'Trader'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_uom_maintain ''c'''   WHERE Field_label= 'Convert UOM'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_uom_maintain ''s'''   WHERE Field_label= 'Packaging UOM'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_uom_maintain ''c'''   WHERE Field_label= 'UOM'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE Field_label= 'Exposure Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_source_price_curve_def_maintain ''l'', @is_active = ''y'''   WHERE Field_label= 'Index'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_getAllMeter @flag=''s'''   WHERE Field_label= 'Meter ID'
 UPDATE user_defined_fields_template SET  sql_string= 'EXEC spa_getAllMeter @flag=''s'''   WHERE Field_label= 'Meter'


UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'', @is_active = ''y'', @not_int_ext_flag = ''b'''   WHERE farrms_field_id= 'broker_id'
UPDATE maintain_field_deal SET  sql_string= 'EXEC spa_source_counterparty_maintain @flag = ''c'', @is_active = ''y'', @int_ext_flag = ''b'''   WHERE farrms_field_id= 'counterparty_id2'
