UPDATE map_function_category
SET is_active = 0

UPDATE  mfc
SET is_active = 1
FROM map_function_category mfc
INNER JOIN static_data_value sdv ON sdv.type_id = 800 AND mfc.function_id = sdv.value_id
WHERE sdv.code IN 
(
'-',
'(',
')',
'*',
'/',
'+',
'<',
'<=',
'<>',
'=',
'>', 
'ABS',
'AllocVolm',
'AND',
'AveragePrice',
'AVG',
'BuySell',
'CEILING',
'CHANNEL',
'ContractPriceValue',
'ContractualVolm',
'DaysinContractMnth',
'DaysInMnth',
'DaysInYr',
'DealFees',
'DealFixPrice',
'DealFloatPrice',
'DealLeg',
'DealMultiplier',
'DealNetPrice',
'DealSettlement',
'DealType',
'GetCurveValue',
'GetLogicalValue',
'GetTimeSeriesData',
'IF Condition',
'ISNULL',
'MAX',
'MeterVol',
'MIN',
'Month',
'OR',
'PeakHours',
'POWER',
'PriceAdder',
'PriceMultiplier',
'PriorFinalizedAmount',
'PriorFinalizedVol',
'RollingAVG',
'RollingSum',
'Round',
'ROW',
'ShapedDealPrice',
'ShapedVol',
'SQRT',
'UDFDetailValue',
'UDFValue',
'UOMConv',
'WeekDay',
'WeekDaysInMth',
'Year'
)