IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[source_ice_trade_vault]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[source_ice_trade_vault](
		source_deal_header_id INT,
		[SenderTradeRefId] [varchar](200) NULL,
		[TradeDate] [varchar](100) NULL,
		[Commodity] [varchar](100) NULL,
		[Position] [varchar](50) NULL,
		[Buyer] [nvarchar](100) NULL,
		[Index] [varchar](100) NULL,
		[Price] [varchar](100) NULL,
		[Quantity] [varchar](100) NULL,
		[StartDate] [varchar](100) NULL,
		[EndDate] [varchar](100) NULL,
		[Accounting Treatment] [varchar](50) NULL,
		[TotalQuantity] [varchar](100) NULL,
		[Seller] [nvarchar](100) NULL,
		[Broker] [nvarchar](100) NULL,
		[PaymentCalendar] [varchar](100) NULL,
		[PaymentFrom] [varchar](100) NULL,
		[PriceCurrency] [varchar](100) NULL,
		[SettlementCurrency] [varchar](100) NULL,
		[SellerPayIndex] [varchar](100) NULL,
		[HoursFromThru] [varchar](100) NULL,
		[HoursFromThruTimezone] [varchar](100) NULL,
		[LoadType] [varchar](100) NULL,
		[DaysOfWeek] [varchar](100) NULL,
		[MasterAgreementType] [varchar](100) NULL,
		[ContractDate] [varchar](100) NULL,
		[MasterAgreementVersion] [varchar](100) NULL,
		[MarketType] [varchar](100) NULL,
		[TradeType] [varchar](100) NULL,
		[ProductId] [int] NULL,
		[ProductName] [varchar](100) NULL,
		[ReportableProduct] [varchar](100) NULL,
		[ContractType] [varchar](100) NULL,
		[SwapPurpose] [varchar](100) NULL,
		[SettlementMethod] [varchar](100) NULL,
		[PriceUnit] [varchar](100) NULL,
		[QuantityUnit] [varchar](100) NULL,
		[QuantityFrequency] [varchar](100) NULL,
		[SettlementFrequency] [varchar](100) NULL,
		[SellerIndexPricingCalendar] [varchar](100) NULL,
		[PaymentDays] [int] NULL,
		[PaymentTerms] [varchar](100) NULL,
		[CurrencyConversion] [varchar](100) NULL,
		[CurrencyConversionSource] [varchar](100) NULL,
		[ExecutionVenue] [varchar](100) NULL,
		[Compression] [varchar](100) NULL,
		[Cleared] [varchar](100) NULL,
		[USSDRReportableTrade] [varchar](100) NULL,
		[ExtraLegalLanguage] [varchar](100) NULL,
		[AllocationTrade] [varchar](100) NULL,
		[InterAffiliateClearingExemptionElection] [varchar](100) NULL,
		[EMIRReportableTrade] [varchar](100) NULL,
		[ExecutionTime] [varchar](100) NULL,
		[CollateralizationType] [varchar](100) NULL,
		[ExecutionTimeCreator] [varchar](100) NULL,
		[UTICreator] [varchar](100) NULL,
		[BuyerCADTR] [varchar](100) NULL,
		[CADClearingExemption] [varchar](100) NULL,
		[CADReportingEntity] [varchar](100) NULL,
		[SellerCADTR] [varchar](100) NULL,
		[CADHistoricSwap] [varchar](100) NULL,
		[CSAReportableTrade] [varchar](100) NULL,
		--------
		[Create Date From] DATETIME,
		[Create Date To] DATETIME,
		[ICE Vault Submission Status] INT,
		[Process ID] varchar (100),
		[Report Type ID] INT,
		[create_user] VARCHAR(50),
		[create_ts] DATETIME,
		[update_user] VARCHAR(50),
		[update_ts] DATETIME
	) ON [PRIMARY]
END	
ELSE
	PRINT 'Table ''source_ice_trade_vault'' already exists.'