IF EXISTS (SELECT 1 FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[source_emir]') AND TYPE IN (N'U'))
BEGIN
    PRINT 'Table Already Exists'
END
ELSE
BEGIN
    CREATE TABLE [dbo].[source_emir] (
		--system default
		[source_emir_id] INT IDENTITY(1, 1) CONSTRAINT [pk_source_emir_id] PRIMARY KEY CLUSTERED WITH (IGNORE_DUP_KEY = OFF) NOT NULL,
		[source_deal_header_id] INT,
		[deal_id] VARCHAR(200),
		[sub_book_id] INT,
		--system default
		--emir columns
		[reporting_timestamp] VARCHAR(25) NOT NULL,
		[counterparty_id] VARCHAR(50) NOT NULL,
		[other_counterparty_id] VARCHAR(50),
		[counterparty_name] VARCHAR(100) NOT NULL,
		[counterparty_domicile] VARCHAR(500),
		[corporate_sector] CHAR(1),
		[is_financial_cpty] CHAR(1),
		[broker_id] VARCHAR(50),
		[reporting_entity_id] VARCHAR(50),
		[clearing_member_id] VARCHAR(50),
		[beneficiary_type_id] VARCHAR(50),
		[beneficiary_id] VARCHAR(50),
		[trading_capacity] CHAR(1),
		[counterparty_side] CHAR(1),
		[commercial_or_treasury] CHAR(1),
		[clearing_threshold] CHAR(1),
		[contarct_mtm_value] NUMERIC(38,  20),
		[contarct_mtm_currency] CHAR(5),
		[valuation_ts] VARCHAR(15),
		[valuation_type] CHAR(1),
		[collateralization] CHAR(2),
		[collateral_portfolio] CHAR(1),
		[collateral_portfolio_code] INT,
		[initial_margin_posted] NUMERIC(38,  20),
		[initial_margin_posted_currency] CHAR(5),
		[variation_margin_posted] NUMERIC(38,  20),
		[variation_margin_posted_currency] CHAR(5),
		[initial_margin_received] NUMERIC(38,  20),
		[initial_margin_received_currency] CHAR(5),
		[variation_margin_received] NUMERIC(38, 20),
		[variation_margins_received_currency] CHAR(5),
		[excess_collateral_posted] NUMERIC(38, 20),
		[excess_collateral_posted_currency] CHAR(5),
		[excess_collateral_received] NUMERIC(38,  20),
		[excess_collateral_received_currency] CHAR(5),
		[contract_type] VARCHAR(20),		
		[asset_class] VARCHAR(20), 
		[product_classification_type] CHAR(1),
		[product_classification] CHAR(6),
		[product_identification_type] CHAR(1),
		[product_identification] CHAR(1),
		[underlying] VARCHAR(20),
		[underlying_identification] VARCHAR(8000),
		[notional_currency_1] CHAR(5),
		[notional_currency_2] CHAR(5),
		[derivable_currency] CHAR(5),
		[trade_id] VARCHAR(52),
		[report_tracking_no] VARCHAR(100),
		[complex_trade_component_id] VARCHAR(40),
		[exec_venue] CHAR(4),
		[compression] CHAR(1),
		[price_rate] NUMERIC(38, 20),
		[price_notation] CHAR(5),
		[price_currency] CHAR(5),
		[notional_amount] NUMERIC(38, 20),
		[price_multiplier] FLOAT,
		[quantity] INT,
		[up_front_payment] FLOAT,
		[delivery_type] CHAR(1),
		[execution_timestamp] VARCHAR(25),
		[effective_date] VARCHAR(10),
		[maturity_date] VARCHAR(10),
		[termination_date] VARCHAR(10),
		[settlement_date] VARCHAR(10),
		[aggreement_type] VARCHAR(50),
		[aggreement_version] CHAR(4),
		[confirm_ts] VARCHAR(25),
		[confirm_means] CHAR(1),
		[clearing_obligation] CHAR(1),
		[cleared] CHAR(1),
		[clearing_ts] VARCHAR(25),
		[ccp] VARCHAR(20),
		[intra_group] CHAR(1),
		[fixed_rate_leg_1] FLOAT,
		[fixed_rate_leg_2] FLOAT,
		[fixed_rate_day_count_leg_1] VARCHAR(100),
		[fixed_rate_day_count_leg_2] VARCHAR(100),
		[fixed_rate_payment_feq_time_leg_1] CHAR(3),
		[fixed_rate_payment_feq_mult_leg_1] CHAR(3),
		[fixed_rate_payment_feq_time_leg_2] CHAR(3),
		[fixed_rate_payment_feq_mult_leg_2] CHAR(3),
		[float_rate_payment_feq_time_leg_1] CHAR(3),
		[float_rate_payment_feq_mult_leg_1] CHAR(3),
		[float_rate_payment_feq_time_leg_2] CHAR(3),
		[float_rate_payment_feq_mult_leg_2] CHAR(3),
		[float_rate_reset_freq_leg_1_time] CHAR(3),
		[float_rate_reset_freq_leg_1_mult] CHAR(3),
		[float_rate_reset_freq_leg_2_time] CHAR(3),
		[float_rate_reset_freq_leg_2_mult] CHAR(3),		
		[float_rate_leg_1] VARCHAR(100),
		[float_rate_ref_period_leg_1_time] CHAR(1),
		[float_rate_ref_period_leg_1_mult] INT,
		[float_rate_leg_2] VARCHAR(100),
		[float_rate_ref_period_leg_2_time] CHAR(1),
		[float_rate_ref_period_leg_2_mult] INT,
		[delivery_currency_2] CHAR(5),
		[exchange_rate_1] FLOAT,
		[forward_exchange_rate] FLOAT,
		[exchange_rate_basis] VARCHAR(20),
		[commodity_base] CHAR(2),
		[commodity_details] VARCHAR(500),
		[delivery_point] VARCHAR(16),
		[interconnection_point] VARCHAR(50),
		[load_type] CHAR(2),
		[load_delivery_interval] VARCHAR(25),
		[delivery_start_date] VARCHAR(25),
		[delivery_end_date] VARCHAR(25),
		[duration] CHAR(1),
		[days_of_the_week] VARCHAR(100),
		[delivery_capacity] VARCHAR(50),
		[quantity_unit] VARCHAR(50),
		[price_time_interval_quantity] FLOAT,
		[option_type] CHAR(1),
		[option_style] CHAR(1),
		[strike_price] FLOAT,
		[strike_price_notation] CHAR(1),
		[underlying_maturity_date] VARCHAR(10),
		[seniority] CHAR(4),
		[reference_entity] VARCHAR(100),
		[frequency_of_payment] CHAR(4),
		[calculation_basis] VARCHAR(50),
		[series] INT,
		[version] INT,
		[index_factor] NUMERIC(38,20),
		[tranche] CHAR(1),
		[attachment_point] VARCHAR(50),
		[detachment_point] VARCHAR(50),
		[action_type] CHAR(1) NOT NULL,
		[level] CHAR(1) NOT NULL,
		--emir columns
		--system default
		[report_type] INT,
		[create_date_from] DATETIME,
		[create_date_to] DATETIME,
		[submission_status] INT,
		[submission_date] DATETIME,
		[confirmation_date] DATETIME,
		[process_id] VARCHAR(100),
		[error_validation_message] VARCHAR(MAX),
		[file_export_name] VARCHAR(100),
		[hash_of_concatenated_values] VARCHAR(1000),
		[progressive_number] INT,
		[create_user] VARCHAR(100) NULL DEFAULT dbo.FNADBUser(),
		[create_ts] DATETIME DEFAULT GETDATE(),
		[update_user] VARCHAR(100) NULL,
		[update_ts] DATETIME NULL
		--system default
    )

    PRINT 'Table Successfully Created'
END

GO