IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UC_rec_generator_code')
BEGIN
	ALTER TABLE rec_generator
	DROP CONSTRAINT UC_rec_generator_code
END

IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UC_rec_generator_id')
BEGIN
	ALTER TABLE rec_generator
	DROP CONSTRAINT UC_rec_generator_id
END


IF NOT EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UC_rec_generator_code_id')
BEGIN
	ALTER TABLE rec_generator
	ADD CONSTRAINT UC_rec_generator_code_id UNIQUE (code,id)
END