IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'confirm_means' AND TABLE_NAME = 'source_emir')
BEGIN
	ALTER TABLE source_emir ALTER COLUMN confirm_means VARCHAR(50)					
END