DELETE FROM [search_meta_data] 
WHERE ID = 48

INSERT [dbo].[search_meta_data] ([ID], [tableName], [columnName], [displayColumns], [table_display_name], [column_display_name]) 
VALUES (48, N'contract_group', N'contract_name', N'''Contract Name:- '' + ISNULL(contract_name, '''')+ '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | name:- '' +ISNULL([Name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Contract Name'),
		(48, N'contract_group', N'contract_desc', N'''Contract Name:- '' + ISNULL(contract_name, '''')+ '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | name:- '' +ISNULL([Name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Contract Desc'),
	   (48, N'contract_group', N'name', N'''Contract Name:- '' + ISNULL(contract_name, '''')+ '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | Name:- '' +ISNULL([name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Contact Name'),
	   (48, N'contract_group', N'company', N'''Contract Name:- '' + ISNULL(contract_name, '''')+ '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | Name:- '' +ISNULL([name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Company Name'),
	   (48, N'contract_group', N'address', N'''Contract Name:- '' + ISNULL(contract_name, '''') + '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | Name:- '' +ISNULL([name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Address'),
	   (48, N'contract_group', N'address2', N'''Contract Name:- '' + ISNULL(contract_name, '''') + '' | contract_desc:- '' +ISNULL([contract_desc], '''') + '' | name:- '' +ISNULL([name], '''')  + '' | Company:- '' +ISNULL([company], '''') + '' | address:- '' +ISNULL([address], '''') + '' | Address2:- '' +ISNULL([address2], '''')', N'Contract', N'Address 2')
