--SELECT * FROM 
UPDATE application_ui_template 
SET template_type = 102807, 
	remarks = NULL
WHERE application_function_id IN (
	SELECT function_id FROM application_functions WHERE function_name IN (
	'View Adjustment'
	,'Actualize Schedules'
	,'Amortize Deferred AOCI'
	,'Apply Cash'
	,'Archive Data'
	,'Automate Matching of Hedges'
	,'Automation of Forecasted Transaction'
	,'Calculate Credit Exposure'
	,'Calculate Credit Value Adjustment'
	,'Close Accounting Period'
	,'Closed Settlement Accounting Period'
	,'Copy Nomination'
	,'Copy Prior MTM Value'
	,'Create and View Deals'
	,'Data Import/Export New UI'
	,'Delete Voided Deal'
	,'Designation of a Hedge'
	,'Dashboard Manager'
	,'EOD Process'
	,'Excel Addin Report Manager'
	,'Export GL Entries'
	,'First Day Gain/Loss Treatment'
	,'Flow Optimization'
	,'Forecast Load'
	,'Forecast Price'
	,'Formula Builder'
	,'Generation Reserve Planner'
	,'Generic Mapping'
	,'Run Assessment'
	,'Lock As of Date'
	,'Manage Approval'
	,'Manage Document'
	,'Manage Email'
	,'Process Invoice'
	,'Reclassify Hedge De-Designation'
	,'REMIT Submission'
	,'Regulatory Submission'
	,'Report Manager'
	,'Run Auto Nom Process'
	,'Run Deal Settlement'
	,'Run Forecasting'
	,'Run Generation Process'
	,'Run Inventory Calc'
	,'Run Measurement Process'
	,'Run Purge Process'
	,'Run Storage WACOG Calc'
	,'Scheduling Workbench'
	,'Setup Book Structure'
	,'Setup CNG Deals'
	,'Setup Custom Report Template'
	,'Setup Delivery Path'
	,'Setup DST'
	,'Setup Hedging Relationship Types'
	,'Setup Logical Trade Lock'
	,'Maintain Netting Asset/Liab Groups'
	,'Setup Renewable Sources'
	,'Setup Route'
	,'Setup Time Series'
	,'Setup Weather Data'
	,'Rules Workflow'
	,'Shut In Volume'
	,'Split Nomination Volume'
	,'E-tag'
	,'Transfer Book Position'
	,'Update Wellhead Volume'
	,'View Edit Nomination'
	,'View Invoice'
	,'View Nomination Schedule'
	,'View Outstanding Automation Results'
	,'View Prices'
	,'View Report'
	,'View Scheduled Job'
	,'View/Edit Meter Data'
	,'View/Edit Profile Data'
	,'View/Update Cum PNL Series'
	)
)

UPDATE application_ui_template 
SET template_type = 102807, remarks = NULL
WHERE application_function_id = 10105890