UPDATE r
SET r.is_system = 0
FROM report r
WHERE r.[name] IN (
	'Position Change Report',
	'MTM Change Report'
)
GO

UPDATE r
SET r.is_system = 1
FROM report r
WHERE r.[name] IN (
	'PNL Attribution Report',
	'Position Attribution Report',
	'AR Aging Report',
	'Cash Collateral Balance Report',
	'Counterparty Collateral Inventory Report',
	'Counterparty Detail Report',
	'Counterparty Limit Report',
	'Credit Exposure By Counterparty',
	'Credit Exposure Extract Report',
	'Credit Exposure Summary Report',
	'Credit Exposure Summary Report for Trader',
	'Credit Exposure To Counterparty',
	'Credit Reserve Report',
	'Credit Value Adjustment Report',
	'Default Probability Report',
	'Default Recovery Rate Report',
	'Parent Counterparty Credit Exposure Report',
	'PFE Report',
	'Deal Audit Trail Detail Report',
	'Deal Extract Report',
	'EoD Trade Report',
	'Correlation Change Report',
	'Correlation Report',
	'Limit Report',
	'Marginal VaR Report',
	'Multiple Scenario WhatIf MTM Report ',
	'Options Greeks Report',
	'Price Report',
	'Volatility Change Report',
	'Volatility Report',
	'What If Analysis Report',
	'Earning Report',
	'MTM Extract Report',
	'MTM Fees Extract Report',
	'MTM Report By Book',
	'MTM Report By Charges',
	'MTM Report By Counterparty',
	'MTM Report by Deal',
	'MTM Report By Trader',
	'MTM Settlement Extract Report',
	'Realized Unrealized Detail Report',
	'Realized Unrealized PNL Report',
	'Daily Position Extract Report',
	'Daily Position Summary Report',
	'Hourly Position Extract Report',
	'Hourly Position Summary Report',
	'Monthly Position Extract Report',
	'Monthly Position Summary Report',
	'Power ToU Position Report',
	'Delta Position Monthly Report',
	'Delta Position Report by Deal',
	'At Risk Backtesting',
	'At Risk Report',
	'At Risk Report-Pivot',
	'Cholesky Decomposition Report',
	'Eigen Values Report',
	'Eigen Vectors Report',
	'Expected Return Change Report',
	'Expected Return Report',
	'Implied Volatility Report',
	'Simulated Prices Report',
	'What if Analysis Report-Pivot',
	'Cash Flow PnL Extract Report',
	'Cash Flow Report by Book and Counterparty',
	'Contract Settlement Detail Report',
	'Contract Settlement Extract with GL Codes',
	'Deal Invoice Report',
	'Deal Settlement Extract Report',
	'Deal Settlement Report By Book',
	'Deal Settlement Report By Counterparty',
	'Journal Entry Report',
	'Meter Data Report',
	'PNL Report by Book and Counterparty',
	'Expiration Calendar Report',
	'Holiday Calendar Report',
	'Trader Definition Report',
	'Price Curve Definition Report',
	'Forecast Profile Definition Report',
	'Meter Definition Report',
	'Location Definition Report',
	'Counterparty Contract Definition Report',
	'Counterparty Definition Report',
	'Counterparty Contact Definition Report',
	'PNL Detail Report',
	'REC Ledger Report',
	'REC Generation Sales Report',
	'REC Summary Report',
	'REC Detail Report',
	'Broker Fees Report',
	'Contract Definition Report'
)
GO

UPDATE ir
SET is_system_import = 'y'
FROM ixp_rules ir
WHERE ir.ixp_rules_name IN (
	'Contract Definition',
	'Counterparty Contact Definition',
	'Counterparty Contract Definition',
	'Counterparty Definition',
	'Expiration Calendar Definition',
	'Holiday Calendar Definition',
	'Location Definition',
	'Meter Definition',
	'Forecast Profile Definition',
	'Price Curve Definition',
	'Trader Definition',
	'Meter Data',
	'Price Curve Data',
	'Deals',
	'Forecast Volume',
	'Shaped Volume',
	'Correlation',
	'Counterparty Credit Information',
	'Counterparty Enhancement Data',
	'Counterparty Unsecured Limit',
	'Default Probability',
	'Recovery Rate',
	'Volatility'
)
GO