UPDATE rp
SET
rp.report_status_id = (SELECT report_status_id  FROM report_status WHERE  name = 'Private')
FROM report_paramset rp
INNER JOIN report_page rpage ON rpage.report_page_id = rp.page_id
INNER JOIN report r ON r.report_id = rpage.report_id
WHERE r.name in ('Expiration Calendar Report'
,'Holiday Calendar Report'
,'Trader Definition Report'
,'Price Curve Definition Report'
,'Forecast Profile Definition Report'
,'Contract Definition Report'
,'Meter Definition Report'
,'Location Definition Report'
,'Counterparty Definition Report'
,'Counterparty Contract Definition Report'
,'Counterparty Contact Definition Report'
,'Deal Audit Trail Detail Report'
,'Deal Extract Report'
,'EoD Trade Report'
,'Hourly Position Extract Report'
,'Hourly Position Summary Report'
,'Daily Position Extract Report'
,'Daily Position Summary Report'
,'Monthly Position Extract Report'
,'Monthly Position Summary Report'
,'Position Attribution Report'
,'Power ToU Position Report'
,'Delta Position Monthly Report'
,'Delta Position Report by Deal'
,'Options Greeks Report'
,'Price Report'
,'PNL Attribution Report'
,'MTM Extract Report'
,'MTM Fees Extract Report'
,'MTM Report by Book'
,'MTM Report by Charges'
,'MTM Report by Counterparty'
,'MTM Report by Deal'
,'MTM Report by Trader'
,'Contract Settlement Detail Report'
,'Contract Settlement Extract with GL Codes'
,'Deal Settlement Extract Report'
,'Deal Settlement Report by Book'
,'Deal Settlement Report by Counterparty'
,'Journal Entry Report'
,'Broker Fees Report'
,'Realized Unrealized PNL Report'
,'PNL Report by Book and Counterparty'
,'Meter Data Report'
,'Deal Invoice Report'
,'Cash Flow PnL Extract Report'
,'Cash Flow Report by Book and Counterparty'
,'MTM Settlement Extract Report'
,'Realized Unrealized Detail Report'
,'Earning Report'
,'AR Aging Report'
,'Cash Collateral Balance Report'
,'Counterparty Collateral Inventory Report'   
,'Counterparty Detail Report'
,'Counterparty Limit Report'
,'Credit Exposure Extract Report'
,'Credit Exposure Summary Report'
,'Credit Exposure By Counterparty'
,'Credit Exposure To Counterparty'
,'Credit Reserve Report'
,'Credit Value Adjustment Report'
,'Default Probability Report'
,'Default Recovery Rate Report'
,'Parent Counterparty Credit Exposure Report'
,'PFE Report'
,'Credit Migration Margin Report By Counterparty'
,'Credit Migration Margin Report To Counterparty'
,'Correlation Change Report'
,'Correlation Report'
,'Limit Report'
,'Marginal VaR Report'
,'Multiple Scenario WhatIf MTM Report'
,'At Risk Backtesting'
,'At Risk Report'
,'At Risk Report-Pivot'
,'Cholesky Decomposition Report'
,'Eigen Values Report'
,'Eigen Vectors Report'
,'Expected Return Change Report'
,'Expected Return Report'
,'Implied Volatility Report'
,'What If Analysis Report'
,'What if Analysis Report-Pivot'
,'Volatility Change Report'
,'Volatility Report'
,'Monthly Inventory Constraint Report'
,'Monthly Inventory WACOG Report'
,'Detail Inventory Constraint Report'
,'Detail Inventory WACOG Report'
,'REC Ledger Report'
,'REC Detail Report'
,'Rec Summary Report'
,'REC Deal Summary Report'
,'REC Extract Report'
,'REC Generation Sales Report'
,'Match Report'
,'Match Audit Report'
,'Match Exception Report'
,'Eligibility Mapping Report'
,'Jurisdiction Market Information Report'
,'Tier Mapping Report'
,'Generator Information Report'
,'Product Detail Report'
,'Hedge Position Report'
,'Generation MTM Report'
,'Var Cost Report'
,'Monthly Position Summary Report By Book'
,'MTM Report by Book and Counterparty'
,'Cost Calc Detail Export'
,'Actualize Ticket Dump Report'
,'Schedule Match report'
,'Shipments Data Dump Report'
,'Shipments Detail Data Dump Report'
,'Simulated Prices Report- Hourly'
,'Consolidated MTM report'
,'Simulated Prices with Percentile'
,'Deal Confirmation Extract Report'
,'Invoice Charge Type Level Extract Report'
,'Invoice Deal Level Extract Report'
,'Trade Ticket Extract Report')


