IF COL_LENGTH('source_deal_settlement_breakdown', 'extrinsic_value_deal') IS NULL
BEGIN


--alter table source_deal_settlement_breakdown add leg_mtm_deal [float]
--alter table source_deal_settlement_breakdown add leg_mtm_inv [float]
--alter table source_deal_settlement_breakdown add leg_set_deal [float]
--alter table source_deal_settlement_breakdown add leg_set_inv [float]
alter table source_deal_settlement_breakdown add extrinsic_value_deal [float]
alter table source_deal_settlement_breakdown add price_deal [float]
alter table source_deal_settlement_breakdown add curve_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add price_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add curve_value_deal [float]
alter table source_deal_settlement_breakdown add fixed_cost_deal [float]
alter table source_deal_settlement_breakdown add fixed_price_deal [float]
alter table source_deal_settlement_breakdown add formula_value_deal [float]
alter table source_deal_settlement_breakdown add price_adder_deal [float]
alter table source_deal_settlement_breakdown add fixed_cost_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add formula_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add price_adder1_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add price_adder2_fx_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add price_adder2_deal [float]
alter table source_deal_settlement_breakdown add market_value_deal [float]
alter table source_deal_settlement_breakdown add market_value_inv [float]
alter table source_deal_settlement_breakdown add contract_value_deal [float]
alter table source_deal_settlement_breakdown add contract_value_inv [float]
alter table source_deal_settlement_breakdown add simple_formula_curve_value_deal [float]
alter table source_deal_settlement_breakdown add simple_formula_curve_value_inv [float]
alter table source_deal_settlement_breakdown add formula_conv_factor_deal [float]
alter table source_deal_settlement_breakdown add formula_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add contract_price_deal [float]
alter table source_deal_settlement_breakdown add market_price_deal [float]
--alter table source_deal_settlement_breakdown add deal_cur_id int
--alter table source_deal_settlement_breakdown add inv_cur_id int
alter table source_deal_settlement_breakdown add price_inv [float]
alter table source_deal_settlement_breakdown add extrinsic_value_inv [float]
alter table source_deal_settlement_breakdown add contract_price_inv [float]
alter table source_deal_settlement_breakdown add market_price_inv [float]
alter table source_deal_settlement_breakdown add price_adder2_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add price_adder1_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add formula_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add fixed_cost_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add curve_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add price_fx_conv_factor_inv [float]
alter table source_deal_settlement_breakdown add formula_value_inv [float]
alter table source_deal_settlement_breakdown add price_adder_inv [float]
alter table source_deal_settlement_breakdown add price_adder2_inv [float]
alter table source_deal_settlement_breakdown add fixed_cost_inv [float]
alter table source_deal_settlement_breakdown add fixed_price_inv [float]
alter table source_deal_settlement_breakdown add curve_value_inv [float]
--alter table source_deal_settlement_breakdown add must_run_volume [float]
--alter table source_deal_settlement_breakdown add must_run_market_value [float]
--alter table source_deal_settlement_breakdown add must_run_contract_value [float]
--alter table source_deal_settlement_breakdown add dispatch_volume [float]
--alter table source_deal_settlement_breakdown add dispatch_market_value [float]
--alter table source_deal_settlement_breakdown add dispatch_contract_value [float]


end
