IF OBJECT_ID(N'[dbo].[source_mifid_trade]', N'U') IS NOT NULL
BEGIN
	PRINT 'Table already exists.'
	RETURN
END

CREATE TABLE [dbo].[source_mifid_trade] (
	[source_mifid_trade_id] INT IDENTITY(1, 1) CONSTRAINT [pk_source_mifid_trade_id] PRIMARY KEY CLUSTERED WITH (IGNORE_DUP_KEY = OFF) NOT NULL,
	[source_deal_header_id] INT NULL,
	[deal_id] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[sub_book_id] INT NULL,
	[trading_date_and_time] VARCHAR(30) COLLATE DATABASE_DEFAULT NULL,
	[instrument_identification_code_type] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[instrument_identification_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[price] NUMERIC(38, 20) NULL,
	[venue_of_execution] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[price_notation] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[price_currency] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[notation_quantity_measurement_unit] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[quantity_measurement_unit] NUMERIC(38, 20) NULL,
	[quantity] NUMERIC(38, 20) NULL,
	[notional_amount] NUMERIC(38, 20) NULL,
	[notional_currency] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[type] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[publication_date_and_time] VARCHAR(30) COLLATE DATABASE_DEFAULT NULL,
	[venue_of_publication] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[transaction_identification_code] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[transaction_to_be_cleared] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[process_id] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[error_validation_message] VARCHAR(MAX) COLLATE DATABASE_DEFAULT NULL,
	[submission_status] INT NULL,
	[create_date_from] DATETIME NULL,
	[create_date_to] DATETIME NULL,	
	[flags] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[supplimentary_deferral_flags] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[trade_report_id] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[trade_version] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[trade_report_type] INT NULL,
	[trade_report_reject_reason] INT NULL,
	[trade_report_trans_type] INT NULL,
	[package_id] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[trade_number] INT NULL,
	[total_num_trade_reports] INT NULL,
	[security_id] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[security_id_source] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[unit_of_measure] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[contract_multiplier] [float] NULL,
	[reporting_party_lei] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[submitting_party_lei] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[submitting_party_si_status] CHAR (1) COLLATE DATABASE_DEFAULT NULL,
	[asset_class] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[contract_type] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[PreviouslyReported] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[StrikeCurrency] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[asset_sub_class] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[maturity_date] VARCHAR(30) COLLATE DATABASE_DEFAULT NULL,
	[freight_size] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[specific_route_or_time_charter_average] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[settlement_location] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[reference_rate] INT NULL,
	[ir_term_of_contract] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[parameter] INT NULL,
	[notional_currency2] CHAR (5) COLLATE DATABASE_DEFAULT NULL,
	[series] INT NULL,
	[version] INT NULL,
	[roll_months] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[next_roll_date] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[option_type] INT NULL,
	[strike_price] NUMERIC(38, 20) NULL,
	[strike_currency] CHAR (5) COLLATE DATABASE_DEFAULT NULL,
	[exercise_style] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[delivery_type] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[transaction_type] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[final_price_type] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[floating_rate_of_leg2] INT NULL,
	[ir_term_of_contract_leg2] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[issue_date] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[settl_currency] CHAR (5) COLLATE DATABASE_DEFAULT NULL,
	[notional_schedule] INT NULL,
	[valuation_method_trigger] INT NULL,
	[return_or_payout_trigger] INT NULL,
	[debt_seniority] INT NULL,
	[dsb_use_case] INT NULL,
	[no_underlyings] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_symbol] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_security_type] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_issuer] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_maturity_date] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_issue_date] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_security_id] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_security_id_source] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_index_name] INT NULL,
	[underlying_issuer_type] INT NULL,
	[underlying_index_term] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_further_sub_product] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_other_security_type] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[underlying_other_further_sub_product] VARCHAR(250) COLLATE DATABASE_DEFAULT NULL,
	[execution_flags] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[side] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[rp_deferral_code] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[counterparty_partyid_lei] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[regulatory_report_type] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[deferral_code] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[submitting_party_nca] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[rp_deferral_reason] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[rp_initial_deferral_reason] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[rp_initial_deferral_code] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[hybrid_deferral] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[initial_deferral_code] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[apa_entity] [nvarchar] (100) COLLATE DATABASE_DEFAULT NULL,
	[create_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL DEFAULT ([dbo].[FNADBUser]()),
	[create_ts] DATETIME NULL DEFAULT (GETDATE()),
	[update_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[update_ts] DATETIME NULL
)