IF OBJECT_ID(N'[dbo].[source_mifid]', N'U') IS NOT NULL
BEGIN
	PRINT 'Table already exists.'
	RETURN
END

CREATE TABLE [dbo].[source_mifid] (
	[source_mifid_id] INT IDENTITY(1, 1) CONSTRAINT [pk_source_mifid_id] PRIMARY KEY CLUSTERED WITH (IGNORE_DUP_KEY = OFF) NOT NULL,
	[source_deal_header_id] INT NULL,
	[deal_id] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[sub_book_id] INT NULL,
	[report_status] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[trans_ref_no] VARCHAR(200) COLLATE DATABASE_DEFAULT NULL,
	[trading_trans_id] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[exec_entity_id] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[covered_by_dir] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[submitting_entity_id_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[buyer_id] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_country] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_fname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_sname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_dob] DATETIME NULL,
	[buyer_decision_maker_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[buyer_decision_maker_fname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_decision_maker_sname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[buyer_decision_maker_dob] DATETIME NULL,
	[seller_id] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_country] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_fname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_sname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_dob] DATETIME NULL,
	[seller_decision_maker_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[seller_decision_maker_fname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_decision_maker_sname] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[seller_decision_maker_dob] DATETIME NULL,
	[order_trans_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[buyer_trans_firm_id] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[seller_trans_firm_id] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[trading_date_time] VARCHAR(30) COLLATE DATABASE_DEFAULT NULL,
	[trading_capacity] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[quantity] NUMERIC(38, 20) NULL,
	[quantity_currency] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[der_notional_incr_decr] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[price] NUMERIC(38, 20) NULL,
	[price_currency] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[net_amount] NUMERIC(38, 20) NULL,
	[venue] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[branch_membership_country] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[upfront_payment] NUMERIC(38, 20) NULL,
	[upfront_payment_currency] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[complex_trade_component_id] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[instrument_id_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[instrument_name] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[instrument_classification] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[notional_currency_1] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[notional_currency_2] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[price_multiplier] NUMERIC(38, 20) NULL,
	[underlying_instrument_code] VARCHAR(25) COLLATE DATABASE_DEFAULT NULL,
	[underlying_index_name] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[underlying_index_term] VARCHAR(10) COLLATE DATABASE_DEFAULT NULL,
	[option_type] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[strike_price] NUMERIC(38, 20) NULL,
	[strike_price_currency] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[option_exercise_style] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[maturity_date] DATE NULL,
	[expiry_date] DATE NULL,
	[delivery_type] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[firm_invest_decision] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[decision_maker_country] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[firm_execution] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[supervising_execution_country] VARCHAR(50) COLLATE DATABASE_DEFAULT NULL,
	[waiver_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[short_selling_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[otc_post_trade_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[commodity_derivative_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[securities_financing_transaction_indicator] VARCHAR(20) COLLATE DATABASE_DEFAULT NULL,
	[report_type] INT NULL,
	[create_date_from] DATETIME NULL,
	[create_date_to] DATETIME NULL,
	[submission_status] INT NULL,
	[submission_date] DATETIME NULL,
	[confirmation_date] DATETIME NULL,
	[process_id] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[error_validation_message] VARCHAR(max) COLLATE DATABASE_DEFAULT NULL,
	[file_export_name] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[hash_of_concatenated_values] VARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
	[progressive_number] INT NULL,
	[create_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL DEFAULT ([dbo].[FNADBUser]()),
	[create_ts] DATETIME NULL DEFAULT (GETDATE()),
	[update_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[update_ts] DATETIME NULL
)