IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE [object_id] = OBJECT_ID (N'[dbo].[source_remit_transport]') AND [type] IN (N'U'))
BEGIN
	 CREATE TABLE [dbo].[source_remit_transport] (
		 [id] INT PRIMARY KEY IDENTITY(1,1),
		 [source_deal_header_id] INT NULL,
		 [deal_id] VARCHAR(200) NULL,
		 [sub_book_id] INT NULL,
		 [sender_identification] VARCHAR(16) NULL,
		 [organised_market_place_id] VARCHAR(16) NULL,
		 [process_identification] VARCHAR(35) NULL,
		 [type_of_gas] VARCHAR(3) NULL,
		 [transportation_transaction_identification] VARCHAR(35) NULL,
		 [creation_date_and_time] VARCHAR(30) NULL,
		 [auction_open_date_and_time] VARCHAR(30) NULL,
		 [auction_end_date_and_time] VARCHAR(30) NULL,
		 [transportation_transaction_type] VARCHAR(3) NULL,
		 [start_date_and_time] VARCHAR(30) NULL,
		 [end_date_and_time] VARCHAR(30) NULL,
		 [offered_capacity] VARCHAR(17) NULL,
		 [capacity_category] VARCHAR(3) NULL,
		 [action_type] VARCHAR(3) NULL,
		 [quantity] NUMERIC(20,5) NULL,
		 [measure_unit] VARCHAR(3) NULL,
		 [currency] VARCHAR(3) NULL,
		 [total_price] NUMERIC(20, 5) NULL,
		 [fixed_or_floating_reserve_price] VARCHAR(3) NULL,
		 [reserve_price] NUMERIC(20, 5) NULL,
		 [premium_price] NUMERIC(20, 5) NULL,
		 [network_point_identification] VARCHAR(35) NULL,
		 [bundling] VARCHAR(3) NULL,
		 [direction] VARCHAR(3) NULL,
		 [tso1_identification] VARCHAR(16) NULL,
		 [tso2_identification] VARCHAR(16) NULL,
		 [market_participant_identification] VARCHAR(16) NULL,
		 [balancing_group_or_portfolio_code] VARCHAR(100) NULL,
		 [procedure_applicable] VARCHAR(3) NULL,
		 [maximum_bid_amount] NUMERIC(20, 5) NULL,
		 [minimum_bid_amount] NUMERIC(20, 5) NULL,
		 [maximum_quantiy] NUMERIC(20, 5) NULL,
		 [minimum_quantiy] NUMERIC(20, 5) NULL,
		 [price_paid_to_tso] NUMERIC(20, 5) NULL,
		 [price_transferee_pays_transferor] NUMERIC(20, 5) NULL,
		 [transferor_identification] VARCHAR(16) NULL,
		 [transferee_identification] VARCHAR(16) NULL,
		 [bid_id] VARCHAR(35) NULL,
		 [auction_round_number] INT NULL,
		 [bid_price] NUMERIC(20, 5) NULL,
		 [bid_quantity] NUMERIC(20, 5) NULL,
		 [report_type] INT NULL,
		 [create_date_from] DATETIME NULL,
		 [create_date_to] DATETIME NULL,
		 [acer_submission_status] INT NULL,
		 [acer_submission_date] DATETIME NULL,
		 [acer_confirmation_date] DATETIME NULL,
		 [process_id] VARCHAR(100) NULL,
		 [error_validation_message] VARCHAR(8000) NULL,
		 [file_export_name] VARCHAR(100) NULL,
		 [hash_of_concatenated_values] VARCHAR(1000) NULL,
		 [progressive_number] INT NULL,
		 [xml_version] INT,
		 [create_ts] DATETIME DEFAULT (GETDATE()),
		 [create_user] VARCHAR(50) DEFAULT ([dbo].[FNADBUser]()),
	)
END
ELSE
	PRINT 'Table source_remit_transport already exist'