IF NOT EXISTS (SELECT 1 FROM admin_email_configuration WHERE template_name = 'OTP Notify' AND module_type = 17821)
BEGIN
	INSERT INTO admin_email_configuration
	(		
		email_subject,
		email_body,
		module_type,
		default_email,
		template_name
	)
	VALUES
	(
		'OTP Verification',
		'<p>Hello &lt;USER_FIRSTNAME&gt;,&nbsp;</p> <p>Please find your One Time Password (OTP) for login below.</p> <p><strong>&lt;OTP_CODE&gt;</strong></p> <h6>&nbsp;Automatically generated by FARRMS. Please do not reply.</h6> <p>Thank you!</p>',
		17821,
		'y',
		'OTP Notify'
	)
END



