IF NOT EXISTS (SELECT 1 FROM admin_email_configuration WHERE template_name = 'FARRMS FIX Protocol Service')
BEGIN
	INSERT INTO admin_email_configuration (email_subject, email_body, module_type, template_name, default_email)
	SELECT 'FARRMS FIX Protocol Service', '<p>Dear&nbsp;<TRM_USER_LAST_NAME></p> <p><TRM_MESSAGE></p> <p>&nbsp;</p> <p>Automatically generated by FARRMS FIX Protocol Service. Please do not reply.</p> <p>Thank you,</p>'
	, 17813, 'FARRMS FIX Protocol Service', 'n'
	PRINT 'AFM Feedback Template email template inserted'
END
ELSE
BEGIN
	UPDATE admin_email_configuration 
	SET email_subject = 'FARRMS FIX Protocol Service:<TRM_VERSION>'
		, email_body = '<p>Dear&nbsp;<TRM_USER_LAST_NAME></p> <p><TRM_MESSAGE></p> <p>&nbsp;</p> <p>Automatically generated by FARRMS FIX Protocol Service. Please do not reply.</p> <p>Thank you,</p>'
		, module_type = 17813
		, default_email = 'n'
	 WHERE template_name = 'FARRMS FIX Protocol Service'
	 PRINT 'FARRMS FIX Protocol Service email template updated'
END
