--	Deleted previously created email template with 'FARRMS FIX Protocol Service'
IF EXISTS (SELECT 1 FROM admin_email_configuration WHERE template_name = 'FARRMS FIX Protocol Service')
BEGIN
	DELETE FROM admin_email_configuration WHERE template_name = 'FARRMS FIX Protocol Service'
END

IF NOT EXISTS (SELECT 1 FROM admin_email_configuration WHERE template_name = 'TRMTracker XConnect Service')
BEGIN
	INSERT INTO admin_email_configuration (email_subject, email_body, module_type, template_name, default_email)
	SELECT 'TRMTracker XConnect Service', '<p>Dear&nbsp;<TRM_USER_LAST_NAME></p> <p><TRM_MESSAGE></p> <p>&nbsp;</p> <p>Automatically generated by TRMTracker XConnect Service. Please do not reply.</p> <p>Thank you,</p>'
	, 17813, 'TRMTracker XConnect Service', 'n'
END
ELSE
BEGIN
	UPDATE admin_email_configuration 
	SET email_subject = 'TRMTracker XConnect Service:<TRM_VERSION>'
		, email_body = '<p>Dear&nbsp;<TRM_USER_LAST_NAME></p> <p><TRM_MESSAGE></p> <p>&nbsp;</p> <p>Automatically generated by TRMTracker XConnect Service. Please do not reply.</p> <p>Thank you,</p>'
		, module_type = 17813
		, default_email = 'n'
	 WHERE template_name = 'TRMTracker XConnect Service'
	 PRINT 'TRMTracker XConnect Service template updated'
END
