DECLARE @mapping_table_id INT 
SELECT @mapping_table_id = mapping_table_id FROM generic_mapping_header WHERE mapping_name = 'XConnect Tag Definition'
-- Security Definition NoLegs Tags
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegSymbol' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'600','LegSymbol',NULL,'LegSymbol','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegSecurityType' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'609','LegSecurityType',NULL,'LegSecurityType','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegSide' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'624','LegSide',NULL,'LegSide','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegQuantity' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'623','LegQuantity',NULL,'LegQuantity','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegPrice' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'566','LegPrice',NULL,'LegPrice','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegSecuritySubType' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'764','LegSecuritySubType',NULL,'LegSecuritySubType','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegOptionDelta' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'1017','LegOptionDelta',NULL,'LegOptionDelta','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegRatioQtyDenominator' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9623','LegRatioQtyDenominator',NULL,'LegRatioQtyDenominator','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegRatioQtyNumerator' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9624','LegRatioQtyNumerator',NULL,'LegRatioQtyNumerator','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegRatioPriceDenominator' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9566','LegRatioPriceDenominator',NULL,'LegRatioPriceDenominator','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm4_value = 'LegRatioPriceNumerator' AND gmv.clm5_value IN('13')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9567','LegRatioPriceNumerator',NULL,'LegRatioPriceNumerator','13') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '996' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'996','UnitOfMeasure',NULL,'UnitOfMeasure','8') END
-- Security Definition Additional Tags to Support User Defined Strategy
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '22' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'22','SecurityIDSource',NULL,'SecurityIDSource','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '107' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'107','SecurityDesc',NULL,'SecurityDesc','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '60' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'60','TransactTime',NULL,'TransactTime','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '167' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'167','SecurityType',NULL,'SecurityType','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '207' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'207','SecurityExchange',NULL,'SecurityExchange','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '541' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'541','MaturityDate',NULL,'MaturityDate','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '762' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'762','SecuritySubType',NULL,'SecuritySubType','8') END
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '9011' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9011','LegDealsSuppressed',NULL,'LegDealsSuppressed','8') END
-- Just To Denote SecurityDefinition ID
IF NOT EXISTS(SELECT 1 from generic_mapping_header gmh INNER JOIN generic_mapping_values gmv ON gmh.mapping_table_id = gmv.mapping_table_id WHERE mapping_name = 'XConnect Tag Definition' AND gmv.clm1_value = '9999' AND gmv.clm5_value IN('8')) BEGIN INSERT INTO generic_mapping_values(mapping_table_id, clm1_value, clm2_value, clm3_value, clm4_value, clm5_value) VALUES (CAST(@mapping_table_id AS VARCHAR),'9999','SecurityDefinitionID',NULL,'SecurityDefinitionID','8') END