IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_header' AND COLUMN_NAME = 'update_ts' AND COLUMN_DEFAULT IS NOT NULL)
BEGIN
	ALTER TABLE source_deal_header DROP CONSTRAINT source_deal_header_UPDATE_ts_def
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_header' AND COLUMN_NAME = 'update_user' AND COLUMN_DEFAULT IS NOT NULL)
BEGIN
	ALTER TABLE source_deal_header DROP CONSTRAINT source_deal_header_UPDATE_user_def
END
GO