IF OBJECT_ID(N'[dbo].[source_remit_audit]', N'U') IS NOT NULL
BEGIN
	PRINT 'Table already "source_remit_audit" exists.'
	RETURN
END

CREATE TABLE [dbo].[source_remit_audit]( 
	[source_remit_audit_id] INT IDENTITY(1, 1) CONSTRAINT [pk_source_remit_audit_id] PRIMARY KEY CLUSTERED WITH (IGNORE_DUP_KEY = OFF) NOT NULL,
	[status] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[error_code] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[error_description] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[action] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[message_type] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[message_received_timestamp] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[processed_timestamp] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[message_id] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[transaction_type] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[uti_id] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[trade_id] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[source_file_name] VARCHAR(500) COLLATE DATABASE_DEFAULT NULL,
	[type] INT NULL,
	[create_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL DEFAULT ([dbo].[FNADBUser]()),
	[create_ts] DATETIME NULL DEFAULT (GETDATE()),
	[update_user] VARCHAR(100) COLLATE DATABASE_DEFAULT NULL,
	[update_ts] DATETIME NULL
)
GO
