IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_f_name')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_f_name NVARCHAR(100) NULL
END

IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_m_name')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_m_name NVARCHAR(100) NULL
END

IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_l_name')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_l_name NVARCHAR(100) NULL
END

IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_address1')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_address1 NVARCHAR(100) NULL
END
IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_address2')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_address2 NVARCHAR(100) NULL
END
IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_address3')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_address3 NVARCHAR(100) NULL
END
IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'city_value_id')
BEGIN
	ALTER TABLE application_users ALTER COLUMN city_value_id NVARCHAR(100) NULL
END
IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_title')
BEGIN
	ALTER TABLE application_users ALTER COLUMN user_title NVARCHAR(100) NULL
END
--IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_zipcode')
--BEGIN
--	ALTER TABLE application_users ALTER COLUMN user_zipcode NVARCHAR(100) NULL
--END


----IF EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'application_users' AND COLUMN_NAME = 'user_login_id')
----BEGIN
----	ALTER TABLE application_users ALTER COLUMN user_login_id NVARCHAR(100) NULL
----END