IF NOT EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'time_zones' AND COLUMN_NAME = 'TIMEZONE_NAME_FOR_PHP')
BEGIN
	ALTER TABLE time_zones ADD TIMEZONE_NAME_FOR_PHP VARCHAR(50) NULL
END