IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'rec_generator' AND COLUMN_NAME = 'strategy_id')
BEGIN
 ALTER TABLE rec_generator DROP COLUMN strategy_id
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'rec_generator' AND COLUMN_NAME = 'subbook_id')
BEGIN
 ALTER TABLE rec_generator DROP COLUMN  subbook_id
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'rec_generator' AND COLUMN_NAME = 'book_structure')
BEGIN
 ALTER TABLE rec_generator DROP COLUMN  book_structure
END