IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_cng' AND COLUMN_NAME = 'pump_number')
BEGIN
	ALTER TABLE source_deal_cng ALTER COLUMN pump_number VARCHAR(100)
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_cng' AND COLUMN_NAME = 'driver')
BEGIN
	ALTER TABLE source_deal_cng ALTER COLUMN driver VARCHAR(100)
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_cng' AND COLUMN_NAME = 'vehicle_id')
BEGIN
	ALTER TABLE source_deal_cng ALTER COLUMN vehicle_id VARCHAR(100)
END

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'source_deal_cng' AND COLUMN_NAME = 'odo_meter')
BEGIN
	ALTER TABLE source_deal_cng ALTER COLUMN odo_meter VARCHAR(100)
END