IF NOT EXISTS(SELECT 'X' FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UK_template_id')
BEGIN
	ALTER TABLE deal_fields_mapping
	ADD CONSTRAINT UK_template_id UNIQUE (template_id)
END