/***************
Alter Table CONTRACT_CHARGE_TYPE_DETAIL
**************/
IF NOT EXISTS (SELECT 'X' FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name = 'CONTRACT_CHARGE_TYPE_DETAIL' and column_name = 'GROUP_BY')
	ALTER TABLE CONTRACT_CHARGE_TYPE_DETAIL add GROUP_BY int


