/* Author		:  Vishwas Khanal			  */
/* Description  :  Rebuilding Function ID	  */
/* Dated		:  15.05.2009				  */

-- Uncomment below lines to apply the new function id changes
-- This script has to be deployed only ONCE.

/*

			/*	------------------------------------------------------------------------------------------------*/
										-- Delete all the dependent tables
			/*	------------------------------------------------------------------------------------------------*/

DELETE FROM application_functional_users WHERE 1 = 1
DELETE FROM menu_item WHERE  1 = 1
DELETE FROM wizard_page_choice WHERE  1 =1
DELETE FROM wizard_page WHERE 1 = 1
DELETE FROM application_functions WHERE 1 = 1

			/*	------------------------------------------------------------------------------------------------*/
										-- Increase the column width of application_functions
			/*	------------------------------------------------------------------------------------------------*/
ALTER TABLE dbo.application_functions ALTER COLUMN function_name VARCHAR(200)
ALTER TABLE dbo.application_functions ALTER COLUMN function_desc VARCHAR(200)

			/*	------------------------------------------------------------------------------------------------*/
										-- Insertion of Project ID, Module IDs, Menu IDs and Event IDs
			/*	------------------------------------------------------------------------------------------------*/

insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10000000,'TRM Tracker','Trade Risk Management Tracker',NULL,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10100000,'Setup','Setup',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101000,'Maintain Static Data','Maintain Static Data',10100000,'windowMaintainStaticData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101010,'Static Data IU','Static Data IU',10101000,'windowMaintainStaticDataIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101011,'Delete Static Data','Delete Static Data',10101000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101012,'Jurisdiction Properties','Jurisdiction Properties',10101000,'windowMaintainStaticProperties') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101013,'Banking Duration IU','Banking Duration IU',10101012,'windowStatePropertiesDuration') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101014,'Delete Banking Duration','Delete Banking Duration',10101012,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101015,'RFC Bonus IU','RFC Bonus IU',10101012,'windowStatePropertiesBonus') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101016,'Delete RFC Bonus','Delete RFC Bonus',10101012,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101017,'REC Requirement IU','REC Requirement IU',10101012,'windowStatePropertiesRequirement') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101018,'Delete REC Requirement','Delete REC Requirement',10101012,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101019,'REC Compliance IU','REC Compliance IU',10101012,'windowStatePropertiesCompliance') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101020,'Delete REC Requirement','Delete REC Requirement',10101012,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101021,'Calender Properties','Calender Properties',10101000,'windowMaintainholidaygroup') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101022,'Delete Calender','Delete Calender',10101000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101023,'Calender IU','Calender IU',10101021,'windowMaintainholidaygroupIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101024,'On Peak/Off Peak Block Defination Properties','On Peak/Off Peak Block Defination Properties',10101000,'windowMaintainHourgroup') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101100,'Maintain Definition','Maintain Definition',10100000,'windowMaintainDefination') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101110,'Maintain Definition Book IU','Maintain Definition Book IU',10101100,'windowMaintainDefinationBK') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101111,'Maintain Definition Broker IU','Maintain Definition Broker IU',10101100,'windowMaintainDefinationBroker') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101112,'Maintain Definition Commodity IU','Maintain Definition Commodity IU',10101100,'windowMaintainDefinationCom') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101113,'Maintain Definition Contract IU','Maintain Definition Contract IU',10101100,'windowMaintainDefinationCont') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101114,'Maintain Definition Conversion IU','Maintain Definition Conversion IU',10101100,'windowMaintainDefinationVol') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101115,'Maintain Definition CounterParty IU','Maintain Definition CounterParty IU',10101100,'windowMaintainDefinationCon') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101116,'Counterparty Bank Info IU','Counterparty Bank Info IU',10101115,'windowCounterpartyBankInfo') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101117,'Delete Counterparty Bank Info','Delete Counterparty Bank Info',10101115,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101118,'Map Contract IU','Map Contract IU',10101115,'windowMaintainDefinationCont') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101119,'Delete Map Contract','Delete Map Contract',10101115,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101120,'Map Recorder ID IU','Map Recorder ID IU',10101115,'windowMaintainRecMeterID') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101121,'Delete Map Recorder ID','Delete Map Recorder ID',10101115,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101122,'CounterParty Credit File','CounterParty Credit File',10101110,'windowCounterpartyCreditFile') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101123,'CounterParty Enhanced IU','CounterParty Enhanced IU',10101122,'windowCounterpartyCreditFileEnhanceIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101124,'Delete CounterParty Enhanced','Delete CounterParty Enhanced',10101122,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101125,'CounterParty Block Trading IU','CounterParty Block Trading IU',10101122,'windowCounterpartyBlockTradingIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101126,'Delete CounterParty Block Trading','Delete CounterParty Block Trading',10101122,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101127,'Netting Group IU','Netting Group IU',10101122,'nettingGrpDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101128,'Delete Netting Group','Delete Netting Group',10101122,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101129,'Maintain Definition Currency IU','Maintain Definition Currency IU',10101100,'windowMaintainDefinationCur') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101130,'Maintain Definition Curve Def','Maintain Definition Curve Def',10101100,'windowMaintainDefinationPrice') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101131,'Maintain Definition Curve Def Privileges IU','Maintain Definition Curve Def Privileges IU',10101130,'windowMaintainDefinationPriceIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101132,'Delete Definition Curve Def Privileges','Delete Definition Curve Def Privileges',10101130,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101133,'Maintain Time Bucket Mapping IU','Maintain Time Bucket Mapping IU',10101130,'windowMaintainTimeBucketMappingIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101134,'Delete Time Bucket Mapping','Delete Time Bucket Mapping',10101130,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101135,'Maintain Definition Deal Type IU','Maintain Definition Deal Type IU',10101100,'windowMaintainDefinationDeal') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101136,'Maintain Internal Desk IU','Maintain Internal Desk IU',10101100,'windowMaintainDefinationInternal_desk') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101137,'Maintain Internal Portfolio IU','Maintain Internal Portfolio IU',10101100,'windowMaintainDefinationInternal_portfolio') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101138,'Maintain Definition Legal Entity IU','Maintain Definition Legal Entity IU',10101100,'windowMaintainDefinationLegalEntity') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101139,'Maintain Definition Location IU','Maintain Definition Location IU',10101100,'windowMaintainDefinationMinor_Location') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101140,'Meter Data IU','Meter Data IU',10101139,'windowMinorLocationMeterData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101141,'Delete Meter Data','Delete Meter Data',10101139,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101142,'Maintain Definition Location Group IU','Maintain Definition Location Group IU',10101100,'windowMaintainDefinationMajor_Location') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101143,'Maintain Product IU','Maintain Product IU',10101100,'windowMaintainDefinationProduct') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101144,'Maintain Definition Trader IU','Maintain Definition Trader IU',10101100,'windowMaintainDefinationTrader') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101145,'Maintain Definition IU','Maintain Definition IU',10101100,'windowMaintainDefinationUOM') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101146,'Delete Maintain Definition','Delete Maintain Definition',10101100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101200,'Setup Book Structure','Setup Book Structure',10100000,'windowSetupHedgingStrategies') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101210,'Book Structure IU','Book Structure IU',10101200,'windowSubsidiaryProperty') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101211,'Delete Book Structure','Delete Book Structure',10101200,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101300,'Map GL Codes','Map GL Codes',10100000,'windowMapGLCodes') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101310,'Map GL Code IU','Map GL Code IU',10101300,'windowMapGlCodesIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101311,'Delete Map GL Code','Delete Map GL Code',10101300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101400,'Maintain Deal Template','Maintain Deal Template',10100000,'windowMaintainDealTemplate') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101410,'Maintain Deal Template Detail IU_Copy','Maintain Deal Template Detail IU_Copy',10101400,'windowMaintainDealTemplateDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101411,'Delete Deal Template','Delete Deal Template',10101400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101412,'UDF Fields IU','UDF Fields IU',10101410,'windowUDFFields') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101413,'Delete UDF Fields','Delete UDF Fields',10101410,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101500,'Maintain Netting Asset/Liab Groups','Maintain Netting Asset/Liab Groups',10100000,'windowMaintainNettingGroups') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101510,'Parent Netting Group IU','Parent Netting Group IU',10101500,'parentNetGrpDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101511,'Delete Parent Netting Group','Delete Parent Netting Group',10101500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101512,'Netting Group IU','Netting Group IU',10101500,'nettingGrpDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101513,'Delete Netting Group','Delete Netting Group',10101500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101514,'Netting Group Applies To IU','Netting Group Applies To IU',10101500,'netGroupAppToDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101515,'Delete Netting Group Applies To','Delete Netting Group Applies To',10101500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101600,'View Scheduled Job','View Scheduled Job',10100000,'windowSchedulejob') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10101610,'Delete Scheduled Job','Delete scheduled Job',10101600,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10110000,'Users and Roles','Users and Roles',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111000,'Maintain Users','Maintain Users',10110000,'windowMaintainUsers') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111010,'Maintain User Privilege','Maintain User Privilege',10111000,'windowMaintainPrivileges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111011,'Insert Roles','Insert Roles',10111000,'windowSelectRoles') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111012,'Delete Roles','Delete Roles',10111000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111013,'Change Password','Change Password',10111000,'windowPasswordChanged') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111014,'Insert User Privilege','Insert User Privilege',10111010,'windowSelectPrivileges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111015,'Delete User Privilege','Delete User Privilege',10111010,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111016,'Maintain User Insert','Maintain User Insert',10111000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111017,'Maintain User Update','Maintain User Update',10111000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111018,'Delete User','Delete User',10111000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111100,'Maintain Roles','Maintain Roles',10110000,'windowMaintainRoles') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111110,'Maintain Roles IU','Maintain Roles IU',10111100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111111,'Delete Role','Delete Role',10111100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111112,'Maintain Roles Privilege','Maintain Roles Privilege',10111110,'windowMaintainPrivileges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111113,'Insert Role Privilege','Insert Role Privilege',10111112,'windowSelectPrivileges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111114,'Delete Role Privilege','Delete Role Privilege',10111112,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111200,'Maintain Work Flow Menu','Maintain Work Flow Menu',10110000,'windowCustomizedMenu') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111210,'WorkFlow group IU','WorkFlow group IU',10111200,'windowCustomizedMenuGroups') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111211,'Insert Menu Item IU','Insert Menu Item IU',10111200,'windowCustomizedMenuItem') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111212,'Delete WorkFlow/MenuItem','Delete WorkFlow/MenuItem',10111200,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111300,'Run Privilege Report','Run Privilege Report',10110000,'windowRunPrivilege') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10111400,'Run System Access Log Report','Run System Access Log Report',10110000,'windowRunSystemAccessLog') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10120000,'Compliance Management','Compliance Management',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121000,'Maintain Compliance Groups','Maintain Compliance Groups',10120000,'maintainComplianceProcess') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121010,'Maintain Group 1(Process) IU','Maintain Group 1(Process) IU',10121000,'windowMaintainComplianceProcessIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121011,'Delete Group 1(Process)','Delete Group 1(Process)',10121000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121012,'Maintain Group 2 (Risks) IU','Maintain Group 2 (Risks) IU',10121000,'windowMaintainComplianceRisksIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121013,'Delete Group 2 (Risks)','Delete Group 2 (Risks)',10121000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121014,'Maintain Compliance Activity','Maintain Compliance Activity',10121000,'compActDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121015,'Maintain Compliance Activity IU_Copy','Maintain Compliance Activity IU_Copy',10121014,'windowCompActivityIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121016,'Delete Compliance Activity','Delete Compliance Activity',10121014,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121017,'Maintain Compliance Activities Dependency','Maintain Compliance Activities Dependency',10121014,'windowCompActivityDependent') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121018,'Perform Compliance Steps IU','Perform Compliance Steps IU',10121014,'reportDummyStepsIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121019,'Delete Compliance Steps','Delete Compliance Steps',10121014,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121020,'Compliance Activity Communication IU','Compliance Activity Communication IU',10121014,'windowActivityProcessMapIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121021,'Delete Compliance Activity Communication','Delete Compliance Activity Communication',10121014,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121022,'Maintain compliance Dependency Insert','Maintain compliance Dependency Insert',10121017,'WindowCompActivityDependencyGrid') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121023,'Delete Compliance Dependency','Delete Compliance Dependency',10121017,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121100,'Approve Compliance Activities','Approve Compliance Activities',10120000,'ApproveComplianceActivities') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121200,'Perform Compliance Activities','Perform Compliance Activities',10120000,'PerformComplianceActivities') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121300,'Maintain Compliance Standards','Maintain Compliance Standards',10120000,'MaintainComplianceStandards') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121310,'Maintain Compliance Standard/Rules IU','Maintain Compliance Standard/Rules IU',10121300,'maintainCompStdsIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121311,'Delete Compliance Standard/Rules','Delete Compliance Standard/Rules',10121300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121312,'Maintain Compliance Revisions IU','Maintain Compliance Revisions IU',10121300,'maintainCompStdsRevIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121313,'Delete Compliance Revisions','Delete Compliance Revisions',10121300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121314,'Maintain Compliance Requirements','Maintain Compliance Requirements',10121300,'MaintainComplianceRequirements') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121315,'Compliance Requirements IU','Compliance Requirements IU',10121314,'windowCompReqMainIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121316,'Delete Compliance Requirements Main','Delete Compliance Requirements Main',10121314,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121317,'Compliance requirements Details IU_copy','Compliance requirements Details IU_copy',10121314,'MaintainComplianceRequirementsIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121318,'Delete Compliance requirements Details','Delete Compliance requirements Details',10121314,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121319,'Maintain Compliance Requirement Revision Dependancy','Maintain Compliance Requirement Revision Dependancy',10121314,'windowCompReqRevisionDependent') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121320,'Compliance Assign Requirements IU','Compliance Assign Requirements IU',10121314,'maintainCompReaAssIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121321,'Delete Compliance Assign Requirements','Delete Compliance Assign Requirements',10121314,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121322,'Maintain Compliance Requirement Revision Dependancy IU','Maintain Compliance Requirement Revision Dependancy IU',10121319,'windowCompActivityStdDependencyIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121323,'Maintain Compliance Requirement Revision Steps IU','Maintain Compliance Requirement Revision Steps IU',10121317,'reportStepsStdIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121324,'Delete Compliance Requirement Revision Steps','Delete Compliance Requirement Revision Steps',10121317,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121325,'Delete Compliance Requirement Revision Dependency','Delete Compliance Requirement Revision Dependency',10121319,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121326,'Compliance Requirements Group','Compliance Requirements Group',10121315,'windowRequirementGroup') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121327,'Compliance Requirements Group IU','Compliance Requirements Group IU',10121326,'RequirementsGroupIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121328,'Delete Compliance Requirements Group','Delete Compliance Requirements Group',10121326,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121400,'Activity Process Map','Activity Process Map',10120000,'windowActivityProcessMap') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121410,'Group2 (Risks)','Group2 (Risks)',10121400,'windowMaintainComplianceRisksIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121411,'Delete Group2 (Risks)','Delete Group2 (Risks)',10121400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121412,'Maintain Static Data IU','Maintain Static Data IU',10121400,'windowMaintainComplianceRisksIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121413,'Delete Static Data','Delete Static Data',10121400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121414,'Compliance Activity IU','Compliance Activity IU',10121400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121500,'Change Owners','Change Owners',10120000,'MaintainChangeOwners') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121600,'View Compliance Activities','View Compliance Activities',10120000,'ViewComplianceActivities') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121700,'View Status On Compliance Activities','View Status On Compliance Activities',10120000,'ReportComplianceActivities') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121800,'Run Compliance Activity Audit Report','Run Compliance Activity Audit Report',10120000,'RunComplianceAuditReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10121900,'Run Compliance Trend Report','Run Compliance Trend Report',10120000,'RunComplianceTrendReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10122000,'Run Compliance Graph Report','Run Compliance Graph Report',10120000,'dashReportPie') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10122100,'Run Compliance Status Graph Report','Run Compliance Status Graph Report',10120000,'dashReportBar') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10130000,'Deal Capture','Deal Capture',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131000,'Maintain Transactions','Maintain Transactions',10130000,'windowMaintainDeals') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131010,'Maintain Transactions IU','Maintain Transactions IU',10131000,'windowMaintainDealInsert') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131011,'Deal Blotter IU','Deal Blotter IU',10131000,'windowMaintainDealInsertBlotter') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131013,'Delete Deal Blotter','Delete Deal Blotter',10131011,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131014,'Maintain Transactions Copy','Maintain Transactions Copy',10131000,'windowCopyDealIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131015,'Delete Transactions','Delete Transactions',10131000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131016,'Maintain Transactions Close','Maintain Transactions Close',10131000,'windowMaintainDealCloseBlotter') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131017,'Maintain Transactions Transfer','Maintain Transactions Transfer',10131000,'windowInterBookTransfer') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131100,'Maintain Transactions Blotter','Maintain Transactions Blotter',10130000,'windowMaintainDealsBlotter') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131300,'Import Deal','Import Deal',10130000,'windowImportData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10131400,'Rollover From Forward To Spot','Rollover From Forward To Spot',10130000,'windowRolloverForwardSpot') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10140000,'Position Reporting','Position Reporting',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10141000,'Run Position Report','Run Position Report',10140000,'windowRunPositionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10141100,'Run Options Report','Run Options Report',10140000,'windowRunOptionsReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10141200,'Run Options Greeks Report','Run Options Greeks Report',10140000,'windowRunOptionsGreeksReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10141300,'Run Hourly Position Report','Run Hourly Position Report',10140000,'windowSettlementProductionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10141400,'Run Transactions Report','Run Transactions Report',10140000,'windowRunTransactionsReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10150000,'Price Curve Management','Price Curve Management',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10151000,'View Prices','View Prices',10150000,'windowViewPrices') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10151010,'View Price Edit','View Price Edit',10151000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10151100,'Import Price','Import Price',10150000,'windowImportData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10160000,'Scheduling And Delivery','Scheduling And Delivery',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161000,'Maintain Loss Factor','Maintain Loss Factor',10160000,'windowMaintainLossFactor') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161010,'Maintain Loss Factor IU','Maintain Loss Factor IU',10161000,'LossFactorIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161011,'Delete Maintain Loss Factor','Delete Maintain Loss Factor',10161000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161100,'Setup Delivery Path','Setup Delivery Path',10160000,'windowSetupDeliveryPath') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161110,'Setup Delivery Path IU','Setup Delivery Path IU',10161100,'UpdateDeliveryPath') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161111,'Delete Setup Delivery Path','Delete Setup Delivery Path',10161100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161200,'Run Position Report','Run Position Report',10160000,'windowPositionGas') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161300,'Schedule and Delivery','Schedule and Delivery',10160000,'windowScheduleAndDelivery') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161310,'Book Schedule And Delivery','Book Schedule And Delivery',10161300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161311,'UnBook Schedule And Delivery','UnBook Schedule And Delivery',10161300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10161400,'Run Storage Position Report','Run Storage Position Report',10160000,'windowRunStoragePositionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10170000,'Deal Verification And Confirmation','Deal Verification And Confirmation',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171000,'Confirm Transactions','Confirm Transactions',10170000,'windowConfirmModule') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171010,'Deal History Confirm Transactions','Deal History Confirm Transactions',10171000,'windowDealConfirmStatus') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171011,'Deal History Confirm Transactions IU','Deal History Confirm Transactions IU',10171000,'windowDealConfirmStatus') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171012,'Delete Deal History Confirm Transactions','Delete Deal History Confirm Transactions',10171011,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171013,'Update Status Confirm Transactions','Update Status Confirm Transactions',10171000,'windowDealConfirmStatusIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171014,'Lock Confirm Transactions','Lock Confirm Transactions',10171000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171015,'UnLock Confirm Transactions','UnLock Confirm Transactions',10171000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171016,'Generate Confirm Confirm Transactions','Generate Confirm Confirm Transactions',10171000,'windowConfirmGenerate') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171100,'Transaction Audit Log Report','Transaction Audit Log Report',10170000,'windowTransactionAuditLog') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171200,'Lock/Unlock Deal','Lock/Unlock Deal',10170000,'windowLockUnlockDeal') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10171300,'Run Unconfirmed Exception Report','Run Unconfirmed Exception Report',10170000,'windowUnconfirmedExeptionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10180000,'Valuation And Risk Analysis','Valuation And Risk Analysis',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181000,'Run MTM','Run MTM',10180000,'windowRunMtmCalc') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181100,'Run MTM Report','Run MTM Report',10180000,'windowMTMReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181200,'Maintain VaR Measurement Criteria','Maintain VaR Measurement Criteria',10180000,'VaRMeasurementCriteriaDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181210,'Maintain VaR Measurement Criteria IU_COPY','Maintain VaR Measurement Criteria IU_COPY',10181200,'VaRMeasurementCriteriaDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181211,'Maintain VaR Measurement Criteria Book IU','Maintain VaR Measurement Criteria Book IU',10181210,'VaRCriteriaBookIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181212,'Delete Maintain VaR Measurement Criteria','Delete Maintain VaR Measurement Criteria',10181200,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181214,'Delete VaR Measurement Criteria Book','Delete VaR Measurement Criteria Book',10181200,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181300,'Maintain Limits','Maintain Limits',10180000,'LimitTrackingScreen') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181310,'Maintain Limits IU','Maintain Limits IU',10181300,'LimitTrackingScreenIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181311,'Maintain Limits Book IU','Maintain Limits Book IU',10181300,'LimitTrackingBookIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181312,'Delete Maintain Limits Book','Delete Maintain Limits Book',10181300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181313,'Maintain Limits Pos Tenor IU','Maintain Limits Pos Tenor IU',10181300,'LimitTrackingCurveIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181314,'Delete Maintain Limits Pos Tenor','Delete Maintain Limits Pos Tenor',10181300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181315,'Delete Maintain Limits','Delete Maintain Limits',10181300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181400,'Calculate Volatility and Correlation','Calculate Volatility and Correlation',10180000,'CalculateVolatilityCorrelation') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181500,'Run VaR Calculations','Run VaR Calculations',10180000,'VaRMeasurementCriteriaDetailReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181600,'Run VaR Report','Run VaR Report',10180000,'windowVaRreport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181700,'Run Limits Report','Run Limits Report',10180000,'windowLimitsReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181800,'Run Implied Volatility Calculation','Run Implied Volatility Calculation',10180000,'windowCalImpVolatility') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10181900,'Run Implied Volatility Report','Run Implied Volatility Report',10180000,'windowReportImpVol') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10182000,'View Volatility and Correlations','View Volatility and Correlations',10180000,'windowViewVolCorReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10190000,'Credit Risk And Analysis','Credit Risk And Analysis',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191000,'Maintain Counterparty','Maintain Counterparty',10190000,'windowMaintainDefinationArg') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191100,'Import Credit Data','Import Credit Data',10190000,'windowImportData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191200,'Export Credit Data Report','Export Credit Data Report',10190000,'windowExportCreditData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191300,'Run Credit Exposure Report','Run Credit Exposure Report',10190000,'windowRunCreditExposureReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191400,'Run Fixed/MTM Exposure Report','Run Fixed/MTM Exposure Report',10190000,'windowRunFixdMtmExposureReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191500,'Run Exposure Concentration Report','Run Exposure Concentration Report',10190000,'windowRunConcExposureReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191600,'Run Credit Reserve Report','Run Credit Reserve Report',10190000,'windowCrRunReserveReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191700,'Run Aged A/R Report','Run Aged A/R Report',10190000,'windowAgedARReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10191800,'Calculate Credit Exposure','Calculate Credit Exposure',10190000,'windowCalculateCreditExposure') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10200000,'Reporting','Reporting',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10201000,'Report Writer','Report Writer',10200000,'windowreportwrite') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10201010,'Report Writer IU','Report Writer IU',10201000,'windowtargetreport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10201011,'Delete Report Writer','Delete Report Writer',10201000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10210000,'Contract Administration','Contract Administration',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10211000,'Maintain Contract','Maintain Contract',10210000,'windowMaintainContractGroup') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10211010,'Contract Detail IU','Contract Detail IU',10211000,'windowMaintainContractGroupDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10211011,'Delete Contract Detail','Delete Contract Detail',10211000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10211013,'Contract Components IU','Contract Components IU',10211010,'windowMaintainContractGroupSize') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10211014,'Delete Contract Component','Delete Contract Component',10211010,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10220000,'Settlement And Billing','Settlement And Billing',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221000,'Run Settlement Process','Run Settlement Process',10220000,'windowMaintainInvoice') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221010,'Maintain Invoice Reconcile','Maintain Invoice Reconcile',10221000,'windowMaintainInvoiceReconcile') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221011,'Manual Invoice Line Item IU','Manual Invoice Line Item IU',10221010,'windowMaintainInvoiceReconcileIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221012,'Delete Manual Invoice Line Item','Delete Manual Invoice Line Item',10221010,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221013,'Generate Invoice/Remittance','Generate Invoice/Remittance',10221010,'windowGenerateInvoice') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221014,'Payment Instruction IU','Payment Instruction IU',10221010,'windowPaymentInsHeaderIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221015,'Delete Payment Instruction','Delete Payment Instruction',10221010,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221016,'Assign Payment Insturction','Assign Payment Insturction',10221010,'windowPaymentInsDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221017,'Unassign Payment Insturction','Unassign Payment Insturction',10221010,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221018,'Save Invoice','Save Invoice',10221010,'windowSaveInvoice') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221019,'Maintain Invoice Reconcile Finalize','Maintain Invoice Reconcile Finalize',10221010,'windowMaintainInvoiceReconcileFinalize') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221020,'Maintain Interruption Block','Maintain Interruption Block',10221010,'windownInterruptionBlock') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221021,'Interruption Block IU','Interruption Block IU',10221019,'windownInterruptionBlockIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221022,'Delete Interruption Block','Delete Interruption Block',10221019,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221100,'Run Inventory Calc','Run Inventory Calc',10220000,'windowRunInventoryCalc') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221200,'Run Settlement Report','Run Settlement Report',10220000,'windowBrokerFeeReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221300,'Settlement Calculation History','Settlement Calculation History',10220000,'windowMaintainInvoiceHistory') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221310,'Delete Settlement Calculation History','Delete Settlement Calculation History',10221300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221311,'Void Charge Type','Void Charge Type',10221300,'windowVoidChargeType') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221312,'Maintain Invoice IU','Maintain Invoice IU',10221300,'windowMaintainInvoiceIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221313,'Delete Invoice','Delete Invoice',10221300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221400,'Post JE Report','Post JE Report',10220000,'windowPostJEReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221500,'Define Meter IDs','Define Meter IDs',10220000,'windowDefineMeterID') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221510,'Meter ID IU','Meter ID IU',10221500,'windowDefineMeterIDIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221511,'Delete Meter ID','Delete Meter ID',10221500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221512,'Meter ID Allocation IU','Meter ID Allocation IU',10221500,'windowDefineMeterIDallocation') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221513,'Delete Meter ID Allocation','Delete Meter ID Allocation',10221500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221514,'Define Meter Channel','Define Meter Channel',10221500,'windowDefineChannel') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221515,'Meter IDs Properties','Meter IDs Properties',10221500,'windowDefineMeterIDProperties') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221516,'Meter IDs Properties IU','Meter IDs Properties IU',10221515,'windowDefineMeterIDPropertiesIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221517,'Delete Meter IDs Properties','Delete Meter IDs Properties',10221515,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221600,'Settlement Adjustments','Settlement Adjustments',10220000,'windowSettlementAdjustments') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10221610,'Adjust Charge Types','Adjust Charge Types',10221600,'windowAdjustChargeType') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10230000,'Accounting','Accounting',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231000,'Maintain Inventory GL Account','Maintain Inventory GL Account',10230000,'windowMaintainInventoryGLAccount') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231010,'Maintain Inventory GL Account IU','Maintain Inventory GL Account IU',10231000,'windowMaintainInventoryGLAccountIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231011,'Delete Maintain Inventory GL Account','Delete Maintain Inventory GL Account',10231000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231100,'Run Inventory Journal Entry Report','Run Inventory Journal Entry Report',10230000,'windowRunInventoryAccountReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231200,'Run Wght Avg Inventory Cost Report','Run Wght Avg Inventory Cost Report',10230000,'windowRunWghtInventoryCostReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231300,'Maintain Contract Components Gl Codes','Maintain Contract Components Gl Codes',10230000,'windowDefineInvoiceGLCode') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231310,'Contract Components GL Codes IU','Contract Components GL Codes IU',10231300,'windowDefineInvoiceGLCodeIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231311,'Delete Contract Components Gl Codes','Delete Contract Components Gl Codes',10231300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231312,'Contract Components GL Codes Detail IU ','Contract Components GL Codes Detail IU ',10231300,'windowDefineInvoiceGLCodeIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231313,'Delete Contract Components GL Codes Detail','Delete Contract Components GL Codes Detail',10231300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231400,'Setup Default GL Code for Contract Components','Setup Default GL Code for Contract Components',10230000,'windowSetupDefaultGLCode') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231410,'Setup Default GL Code for Contract Components IU','Setup Default GL Code for Contract Components IU',10231400,'windowSetupDefaultGLCodeIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231411,'Setup Default GL Code for Contract Components IU','Setup Default GL Code for Contract Components IU',10231400,'windowSetupDefaultGLCodeIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231412,'Delete Default GL Code for Contract Components','Delete Default GL Code for Contract Components',10231400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231500,'Curve Value Report','Curve Value Report',10230000,'windowCurveValueReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231600,'Run Revenue Report','Run Revenue Report',10230000,'windowRevenueReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231700,'Run Journal Entry Report','Run Journal Entry Report',10230000,'windowRunInventoryJournalEntryReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231800,'Run EQR Report','Run EQR Report',10230000,'windowRunEQRReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231900,'Setup Hedging Relationship Types','Setup Hedging Relationship Types',10230000,'windowSetupHedgingRelationshipsTypes') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231910,'Setup Hedging Relationship Types IU','Setup Hedging Relationship Types IU',10231900,'windowSetupHedgingRelationshipsTypesDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231911,'Copy Hedging Relationship Types','Copy Hedging Relationship Types',10231900,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231912,'Delete Setup Hedging Relationship Types','Delete Setup Hedging Relationship Types',10231900,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231913,'Hedge/Item Relationship types IU','Hedge/Item Relationship types IU',10231910,'windowSetupHedgingRelationshipsTypesDetailHedgingItems') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231914,'Delete Hedging Relationship type','Delete Hedging Relationship type',10231910,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231915,'Delete Item Relationship type','Delete Item Relationship type',10231910,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10231916,'Approve Setup Hedging Relationship Types','Approve Setup Hedging Relationship Types',10231900,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232000,'Run Hedging Relationship Types Report','Run Hedging Relationship Types Report',10230000,'windowRunSetupHedgingRelationshipsTypesReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232200,'Manage Documents','Manage Documents',10230000,'windowManageDocuments') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232210,'Manage Documents IU','Manage Documents IU',10232200,'windowManageDocumentsIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232211,'Delete Documents','Delete Documents',10232200,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232212,'Manage Documents - Email','Manage Documents - Email',10232200,'windowEmail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232213,'Save Documents','Save Documents',10232210,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232300,'Run Assessment','Run Assessment',10230000,'windowRunAssessment') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232310,'Assesment Result IU','Assesment Result IU',10232400,'windowViewAssessmentResultsIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232400,'View Assessment Results','View Assessment Results',10230000,'windowViewAssessmentResults') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232500,'Run Assessment Trend Graph','Run Assessment Trend Graph',10230000,'windowRunAssessmentTrendGraph') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232600,'Run What-If Effectiveness Analysis','Run What-If Effectiveness Analysis',10230000,'windowRunWhatIfEffectivenessAnalysis') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232610,'What if Analysis IU','What if Analysis IU',10232600,'windowRunWhatIfEffectivenessAnalysisDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232611,'Delete What if Analysis','Delete What if Analysis',10232600,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232612,'Copy What if Analysis','Copy What if Analysis',10232600,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232613,'Hedge/Item What if Analysis Effectiveness IU','Hedge/Item What if Analysis Effectiveness IU',10232610,'windowRunWhatIfEffectivenessAnalysisDetailhi') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232614,'Delete Hedge What if Analysis Effectiveness','Delete Hedge What if Analysis Effectiveness',10232610,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232615,'Delete Item What if Analysis Effectiveness','Delete Item What if Analysis Effectiveness',10232610,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232700,'Import Data','Import Data',10230000,'windowImportData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232800,'Run Import Audit Report','Run Import Audit Report',10230000,'windowRunFilesImportAuditReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232900,'Maintain Missing Static Data','Maintain Missing Static Data',10230000,'windowMaintainMissingStaticData') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10232910,'Insert Missing Data','Insert Missing Data',10232900,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233000,'Delete Voided Deal','Delete Voided Deal',10230000,'windowVoidDealImports') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233010,'Delete Void Deal Data','Delete Void Deal Data',10233000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233200,'Run What-If Measurement Analysis','Run What-If Measurement Analysis',10230000,'windowRunwhatifmeasurementana') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233300,'Copy Prior MTM Value','Copy Prior MTM Value',10230000,'windowPriorMTM') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233400,'Run Measurement','Run Measurement',10230000,'windowRunMeasurement') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233500,'Run Calc Embedded Derivative','Run Calc Embedded Derivative',10230000,'windowCalcEmbedded') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233600,'Close Accounting Period','Close Accounting Period',10230000,'windowCloseMeasurement') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233700,'Designation of a Hedge','Designation of a Hedge',10230000,'windowDesignationofaHedgeFromMenu') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233710,'Insert Hedging RelationShip','Insert Hedging RelationShip',10233700,'windowDesignationofaHedgeFromMenu') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233711,'Run Analysis Hedging RelationShip','Run Analysis Hedging RelationShip',10233710,'windowHedgingRunEffectiveness') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233712,'Delete Dedesignation','Delete Dedesignation',10233710,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233713,'Hedges IU','Hedges IU',10233710,'windowSelectDealDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233714,'Delete Hedges','Delete Hedges',10233710,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233715,'Hedge Items IU','Hedge Items IU',10233710,'windowSelectDealDetail') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233716,'Delete Hedge Items','Delete Hedge Items',10233710,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233717,'Detail Hedging RelationShip','Detail Hedging RelationShip',10233700,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233718,'Delete Hedging RelationShip','Delete Hedging RelationShip',10233700,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233719,'Dedesignate Hedging RelationShip','Dedesignate Hedging RelationShip',10233700,'windowDedesignateMutlipleHedges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233720,'Copy Hedging RelationShip','Copy Hedging RelationShip',10233700,'windowCopyLink') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233800,'De-Designation of a Hedge by FIFO/LIFO','De-Designation of a Hedge by FIFO/LIFO',10230000,'windowDedesignateFifolifo') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10233900,'Run Hedging Relationship Report','Run Hedging Relationship Report',10230000,'windowRunHedgeRelationshipReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234000,'Reclassify Hedge De-Designation','Reclassify Hedge De-Designation',10230000,'windowReclassifyDedesignationVALUES') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234010,'Delete Reclassify Hedge De-Designation','Delete Reclassify Hedge De-Designation',10234000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234011,'Reclassify Date','Reclassify Date',10234000,'windowReclassifyDateIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234100,'Amortize Deferred AOCI','Amortize Deferred AOCI',10230000,'windowAmortizeLockedAOCI') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234110,'Delete Amortize Deferred AOCI','Delete Amortize Deferred AOCI',10234100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234111,'Amortize Amortize Deferred AOCI','Amortize Amortize Deferred AOCI',10234100,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234200,'Life Cycle of Hedges','Life Cycle of Hedges',10230000,'windowLifecyclesOfHedges') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234300,'Automation of Forecasted Transaction','Automation of Forecasted Transaction',10230000,'windowAutomationofForecastedTransaction') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234310,'Select Deals Group','Select Deals Group',10234300,'windowGenDealsGroupIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234311,'Delete Automation of Forecasted Transaction','Delete Automation of Forecasted Transaction',10234300,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234312,'Update General Deal Groups IU','Update General Deal Groups IU',10234300,'windowGenDealsGroupDetailIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234400,'Automate Matching of Hedges','Automate Matching of Hedges',10230000,'windowAutomationMathingHedge') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234410,'Match Transaction Automate Matching of Hedges','Match Transaction Automate Matching of Hedges',10234400,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234500,'View Outstanding Automation Results','View Outstanding Automation Results',10230000,'windowViewOutstandingAutomationResults') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234510,'Get Status View Outstanding Automation Results','Get Status View Outstanding Automation Results',10234500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234511,'Delete View Outstanding Automation Results','Delete View Outstanding Automation Results',10234500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234512,'Approve Relationships View Outstanding Automation Results','Approve Relationships View Outstanding Automation Results',10234500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234513,'Update Items View Outstanding Automation Results','Update Items View Outstanding Automation Results',10234500,'windowviewoutstandautoresIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234514,'Finalized Approved Transactions','Finalized Approved Transactions',10234500,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234600,'First Day Gain/Loss Treatment','First Day Gain/Loss Treatment',10230000,'windowFirstDayGainLoss') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234610,'Process First Day Gain/Loss Treatment','Process First Day Gain/Loss Treatment',10234600,'windowFirstDayGainLossIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234611,'Update First Day Gain/Loss Treatment','Update First Day Gain/Loss Treatment',10234600,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234612,'Delete First Day Gain/Loss Treatment','Delete First Day Gain/Loss Treatment',10234600,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234700,'Maintain Transactions Tagging','Maintain Transactions Tagging',10230000,'windowMaintainTransactionsTagging') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234710,'Update Maintain Transactions Tagging','Update Maintain Transactions Tagging',10234700,'windowTransactionAuditReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234800,'Bifurcation Of Embedded Derivatives','Bifurcation Of Embedded Derivatives',10230000,'windowBifurcationEmbeddedDerivatives') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234810,'Bifurcation Of Embedded Derivatives','Bifurcation Of Embedded Derivatives',10234800,'windowBifurcationEmbeddedDerivativesIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234811,'Update Bifurcation Of Embedded Derivatives','Update Bifurcation Of Embedded Derivatives',10234800,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234812,'Delete Bifurcation Of Embedded Derivatives','Delete Bifurcation Of Embedded Derivatives',10234800,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10234900,'Run Measurement Report','Run Measurement Report',10230000,'windowRunMeasurementReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235000,'Run Measurement Trend Graph','Run Measurement Trend Graph',10230000,'windowRunMeasurementTrendGraph') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235100,'Run Period Change Values Report','Run Period Change Values Report',10230000,'windowPeriodChangeValueReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235200,'Run AOCI Report','Run AOCI Report',10230000,'windowAOCIReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235300,'Run De-Designation Values Report','Run De-Designation Values Report',10230000,'windowDedesignateReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235400,'Run Journal Entry Report','Run Journal Entry Report',10230000,'windowRunJournalEntryReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235500,'Run Netted Journal Entry Report','Run Netted Journal Entry Report',10230000,'windowRunNettedJournalEntryReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235600,'Run Accounting Disclosure Report','Run Accounting Disclosure Report',10230000,'windowRunDisclosureReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235700,'Run Fair Value Disclosure Report','Run Fair Value Disclosure Report',10230000,'windowRunnetAssetsReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235800,'Run Assessment Report','Run Assessment Report',10230000,'windowRunAssessmentReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10235900,'Run Transaction Report','Run Transaction Report',10230000,'windowRunDealReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236000,'Run Tagging Export','Run Tagging Export',10230000,'windowTaggingExport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236100,'Run Missing Assessment Values Report','Run Missing Assessment Values Report',10230000,'windowRunMissingAssessmentValuesReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236200,'Run Failed Assessment Values Report','Run Failed Assessment Values Report',10230000,'windowRunFailAssessmentValuesReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236300,'Run Unapproved Hedging Relationship Exception Report','Run Unapproved Hedging Relationship Exception Report',10230000,'windowRunUnapprovedHedgingRelationshipExceptionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236400,'Run Available Hedge Capacity Exception Report','Run Available Hedge Capacity Exception Report',10230000,'windowRunAvailableHedgeCapacityExceptionReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236500,'Run Not Mapped Transaction Report','Run Not Mapped Transaction Report',10230000,'windowRunNotMappedDealReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236600,'Run Tagging Audit Report','Run Tagging Audit Report',10230000,'windowRunTaggingAuditReport') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10236700,'Run Hedge and Item Position Matching Report','Run Hedge and Item Position Matching Report',10230000,'windowHedgeItemMatchExceptRpt') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10240000,'Treasury','Treasury',10000000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10241000,'Reconcile Cash Entries for Derivatives','Reconcile Cash Entries for Derivatives',10240000,'windowReconcileCashEntriesDerivatives') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10241010,'Reconcile Cash Entries for DerivativesIU','Reconcile Cash Entries for DerivativesIU',10240000,'windowReconcileEntriesDerivativesIU') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10241011,'Delete Reconcile Cash Entries for DerivativesIU','Delete Reconcile Cash Entries for DerivativesIU',10240000,NULL) 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values ( 10241100,'Apply Cash','Apply Cash',10240000,'windowApplyCash') 
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values (10161500,'Maintain Source Generator','Maintain Source Generator',10160000,'windowMaintainSourceGenerator')
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values (10161600,'Location Price Index','Location Price Index',10160000,'windowLocationPriceIndex')
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values (10161700,'Bid Offer Formulator','Bid Offer Formulator',10160000,'windowBidOfferFormulator')
insert application_functions( function_id,function_name,function_desc,func_ref_id,function_call) values (10161800,'Maintain Power Outage','Maintain Power Outage',10160000,'windowMaintainPowerOutage')

*/