TRUNCATE TABLE process_risk_controls_activities_status

insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 1,725,'N','N','N','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 2,728,'N','N','N','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 3,725,'Y','N','N','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 4,728,'Y','N','N','N',11000,NULL) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 5,729,'Y','N','N','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 6,726,'Y','N','N','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 7,725,'N','Y','N','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 8,728,'N','Y','N','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 9,728,'N','Y','N','N',11000,NULL) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 10,729,'N','Y','N','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 11,726,'N','Y','N','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 12,725,'N','N','Y','N',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 13,728,'N','N','Y','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 14,725,'N','N','N','Y',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 15,728,'N','N','N','Y',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 16,731,'N','N','N','Y',11002,730) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 17,730,'N','N','N','Y',11003,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 18,725,'N','N','N','Y',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 19,728,'N','N','N','Y',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 20,725,'Y','N','Y','N',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 21,728,'Y','N','Y','N',11000,729) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 22,729,'Y','N','Y','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 23,726,'Y','N','Y','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 24,725,'N','Y','Y','N',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 25,728,'N','Y','Y','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 26,728,'N','Y','Y','N',11000,NULL) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 27,729,'N','Y','Y','N',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 28,726,'N','Y','Y','N',11001,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 29,725,'Y','N','Y','Y',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 30,728,'Y','N','Y','Y',11000,NULL) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 31,729,'Y','N','Y','Y',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 32,726,'Y','N','Y','Y',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 33,731,'Y','N','Y','Y',11002,730) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 34,730,'Y','N','Y','Y',11003,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 35,725,'Y','N','Y','Y',11005,728) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 36,728,'Y','N','Y','Y',11000,NULL) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 37,729,'Y','N','Y','Y',11004,725) 
insert into process_risk_controls_activities_status( activityStatusId,activityStatus,requiresApproval,requiresApprovalLate,requiresProof,mitigationRequired,nextAction,nextStatus)
values ( 38,726,'Y','N','Y','Y',11005,728) 
