IF OBJECT_ID('dbo.[credit_exposure_detail]','u') IS NOT NULL 
DROP TABLE dbo.[credit_exposure_detail]
--This is the final output table.. Save this and get reports from here..

--drop table credit_exposure_detail

CREATE TABLE dbo.[credit_exposure_detail](
	[as_of_date] DATETIME NOT NULL,
	curve_source_value_id INT NOT NULL,
	[Netting_Parent_Group_ID] [int] NULL,
	[Netting_Parent_Group_Name] [varchar](100) NULL,
	[Netting_Group_ID] [int] NULL,
	[Netting_Group_Name] [varchar](100) NULL,
	[Netting_Group_Detail_ID] [int] NULL,
	fas_subsidiary_id int NULL, 
	fas_strategy_id int NULL,
	fas_book_id int NULL,
	[Source_Deal_Header_ID] [int] NULL,
	[Source_Counterparty_ID] [int] NULL,
	[term_start] [datetime] NULL,
	[agg_term_start] [varchar] (20) NULL,
	[Final_Und_Pnl] [float] NULL,
	[Final_Dis_Pnl] [float] NULL,
	[legal_entity] [int] NULL,
	[exp_type_id] [varchar](10) NULL,
	[exp_type] [varchar](10) NULL,
	[gross_exposure] [float] NULL,
	[d_gross_exposure] [float] NULL,
	[invoice_due_date] DATETIME NULL,
	[aged_invoice_days] float,
	[netting_counterparty_id] [int] NULL,
	[counterparty_name] [varchar](250) NULL,
	[parent_counterparty_name] [varchar](250) NULL,
	[counterparty_type] [varchar](50) NULL,
	[risk_rating] [varchar](50) NULL,
	[debt_rating] [varchar](50) NULL,
	[industry_type1] [varchar](50) NULL,
	[industry_type2] [varchar](50) NULL,
	[sic_code] [varchar](50) NULL,
	[account_status] [varchar](50) NULL,
	[currency_name] [varchar](50) NULL,
	[watch_list] [varchar](1) NULL,
	[int_ext_flag] [varchar](1) NULL,
	[tenor_limit] int, 
	[tenor_days] int, 
	[total_limit_provided] float, 
	[total_limit_received] float, 
	[net_exposure_to_us] [float] NULL,
	[net_exposure_to_them] [float] NULL,
	[total_net_exposure] [float] NULL,
	[limit_to_us_avail] [float] NULL,
	[limit_to_them_avail] [float] NULL,
	[limit_to_us_violated] [int] NULL,
	[limit_to_them_violated] [int] NULL,
	[tenor_limit_violated] [int] NULL,
	[limit_to_us_variance] [float] NULL,
	[limit_to_them_variance] [float] NULL,
	d_net_exposure_to_us float NULL, 
	d_net_exposure_to_them float NULL, 
	d_total_net_exposure float NULL, 
	d_limit_to_us_avail float NULL, 
	d_limit_to_them_avail float NULL, 
	d_limit_to_us_variance float NULL, 
	d_limit_to_them_variance float NULL
) 