--DROP TABLE [dbo].[source_remit_standard]

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[source_remit_standard]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[source_remit_standard](
		id  INT IDENTITY(1,1) NOT NULL,
		source_deal_header_id INT,
		deal_id VARCHAR (200),
		sub_book_id INT,
		market_id_participant_counterparty VARCHAR (50),
		type_of_code_field_1 VARCHAR (3),
		trader_id_market_participant VARCHAR (50),
		other_id_market_participant_counterparty VARCHAR (50),
		type_of_code_field_4 VARCHAR (3),
		reporting_entity_id VARCHAR (50),
		type_of_code_field_6 VARCHAR (3),
		beneficiary_id VARCHAR (50),
		type_of_code_field_8 VARCHAR (3),
		trading_capacity_market_participant VARCHAR (1),
		buy_sell_indicator VARCHAR (1),
		initiator_aggressor VARCHAR (1),
		order_id VARCHAR (20),
		order_type VARCHAR (3),
		order_condition VARCHAR (3),
		order_status VARCHAR (3),
		minimum_execution_volume NUMERIC (20,5),
		price_limit NUMERIC (20,5),
		undisclosed_volume NUMERIC (20,5),
		order_duration VARCHAR (3),
		contract_id VARCHAR (200),
		[contract_name] VARCHAR (200),
		contract_type VARCHAR (3),
		energy_commodity VARCHAR (2),
		fixing_index_or_reference_price VARCHAR (200),
		settlement_method VARCHAR (1),
		organised_market_place_id_otc VARCHAR (20),
		contract_trading_hours VARCHAR (20),
		last_trading_date_and_time DATETIME,
		transaction_timestamp DATETIME,
		unique_transaction_id VARCHAR (52),
		linked_transaction_id VARCHAR (52),
		linked_order_id VARCHAR (52),
		voice_brokered VARCHAR (1),
		price NUMERIC (20,5),
		index_value NUMERIC (20,5),
		price_currency VARCHAR (3),
		notional_amount NUMERIC (20,5),
		notional_currency VARCHAR (3),
		quantity_volume NUMERIC (20,5),
		total_notional_contract_quantity NUMERIC (20,5),
		quantity_unit_field_40_and_41 VARCHAR (10),
		termination_date DATETIME,
		option_style VARCHAR (1),
		option_type VARCHAR (1),
		option_exercise_date DATETIME,
		option_strike_price NUMERIC (20,5),
		delivery_point_or_zone VARCHAR (16),
		delivery_start_date DATETIME,
		delivery_end_date DATETIME,
		duration VARCHAR (1),
		load_type VARCHAR (2),
		days_of_the_week VARCHAR (2),
		load_delivery_intervals VARCHAR(20),
		delivery_capacity NUMERIC (20,5),
		quantity_unit_used_in_field_55 VARCHAR(10),
		price_time_interval_quantity NUMERIC (20,5),
		action_type VARCHAR (1),
		report_type INT,
		create_date_from DATETIME,
		create_date_to DATETIME,
		create_ts DATETIME  DEFAULT GETDATE(),
		create_user VARCHAR(50) DEFAULT dbo.FNADBUser(),
		acer_submission_status INT,
		acer_submission_date DATETIME,
		acer_confirmation_date DATETIME,
		process_id VARCHAR (100),
		error_validation_message VARCHAR (8000),
		file_export_name VARCHAR (100),
		hash_of_concatenated_values VARCHAR (1000),
		progressive_number INT
		)

END
ELSE PRINT 'Table ''source_remit_standard'' already exists.'