IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[source_remit_non_standard]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[source_remit_non_standard](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[source_deal_header_id] [int] NULL,
	[deal_id] [varchar](200) NULL,
	[sub_book_id] [int] NULL,
	[id_of_the_market_participant_or_counterparty] [varchar](50) NULL,
	[type_of_code_used_in_field_1] [varchar](3) NULL,
	[id_of_the_other_market_participant_or_counterparty] [varchar](50) NULL,
	[type_of_code_used_in_field_3] [varchar](3) NULL,
	[reporting_entity_id] [varchar](50) NULL,
	[type_of_code_used_in_field_5] [varchar](3) NULL,
	[beneficiary_id] [varchar](50) NULL,
	[type_of_code_used_in_field_7] [varchar](3) NULL,
	[trading_capacity_of_the_market_participant_or_counterparty_in_field_1] [varchar](1) NULL,
	[buy_sell_indicator] [varchar](1) NULL,
	[contract_id] [varchar](100) NULL,
	[contract_date] [datetime] NULL,
	[contract_type] [varchar](2) NULL,
	[energy_commodity] [varchar](2) NULL,
	[price] [numeric](20, 5) NULL,
	[price_formula] [varchar](1000) NULL,
	[estimated_notional_amount] [numeric](20, 5) NULL,
	[notional_currency] [varchar](3) NULL,
	[total_notional_contract_quantity] [numeric](20, 5) NULL,
	[volume_optionality_capacity] [varchar](20) NULL,
	[notional_quantity_unit] [varchar](10) NULL,
	[volume_optionality] [varchar](1) NULL,
	[volume_optionality_frequency] [varchar](1) NULL,
	[volume_optionality_intervals] [varchar](100) NULL,
	[type_of_index_price] [varchar](1) NULL,
	[fixing_index] [varchar](2000) NULL,
	[fixing_index_types] [varchar](200) NULL,
	[fixing_index_sources] [varchar](1000) NULL,
	[first_fixing_date] [varchar](1000) NULL,
	[last_fixing_date] [varchar](1000) NULL,
	[fixing_frequency] [varchar](100) NULL,
	[settlement_method] [varchar](1) NULL,
	[option_style] [varchar](1) NULL,
	[option_type] [varchar](1) NULL,
	[option_first_exercise_date] [datetime] NULL,
	[option_last_exercise_date] [datetime] NULL,
	[option_exercise_frequency] [varchar](1) NULL,
	[option_strike_index] [varchar](150) NULL,
	[option_strike_index_type] [varchar](2) NULL,
	[option_strike_index_source] [varchar](100) NULL,
	[option_strike_price] [numeric](20, 5) NULL,
	[delivery_point_or_zone] [varchar](16) NULL,
	[delivery_start_date] [datetime] NULL,
	[delivery_end_date] [datetime] NULL,
	[load_type] [varchar](2) NULL,
	[action_type] [varchar](1) NULL,
	[report_type] [int] NULL,
	[create_date_from] [datetime] NULL,
	[create_date_to] [datetime] NULL,
	[create_ts] [datetime] DEFAULT getdate(),
	[create_user] [varchar](50) DEFAULT [dbo].[FNADBUser](),
	[acer_submission_status] [int] NULL,
	[acer_submission_date] [datetime] NULL,
	[acer_confirmation_date] [datetime] NULL,
	[process_id] [varchar](100) NULL,
	[error_validation_message] [varchar](8000) NULL,
	[file_export_name] [varchar](100) NULL,
	[hash_of_concatenated_values] [varchar](1000) NULL,
	[progressive_number] [int] NULL
) ON [PRIMARY]

END
ELSE PRINT 'Table ''source_remit_non_standard'' already exists.'
