if OBJECT_ID('delete_source_deal_detail') is  null
CREATE TABLE [dbo].[delete_source_deal_detail](
	[rowid] [int] IDENTITY(1,1) NOT NULL,
	[source_deal_detail_id] [int] ,
	[source_deal_header_id] [int] NOT NULL,
	[term_start] [datetime] NOT NULL,
	[term_end] [datetime] NOT NULL,
	[Leg] [int] NOT NULL,
	[contract_expiration_date] [datetime] NOT NULL,
	[fixed_float_leg] [char](1) NOT NULL,
	[buy_sell_flag] [char](1) NOT NULL,
	[curve_id] [int] NULL,
	[fixed_price] [numeric](38, 20) NULL,
	[fixed_price_currency_id] [int] NULL,
	[option_strike_price] [numeric](38, 20) NULL,
	[deal_volume] [numeric](38, 20) NULL,
	[deal_volume_frequency] [char](1) NOT NULL,
	[deal_volume_uom_id] [int] NOT NULL,
	[block_description] [varchar](100) NULL,
	[deal_detail_description] [varchar](100) NULL,
	[formula_id] [int] NULL,
	[volume_left] [float] NULL,
	[settlement_volume] [float] NULL,
	[settlement_uom] [int] NULL,
	[create_user] [varchar](50) NULL,
	[create_ts] [datetime] NULL,
	[update_user] [varchar](50) NULL,
	[update_ts] [datetime] NULL,
	[price_adder] [numeric](38, 20) NULL,
	[price_multiplier] [numeric](38, 20) NULL,
	[settlement_date] [datetime] NULL,
	[day_count_id] [int] NULL,
	[location_id] [int] NULL,
	[meter_id] [int] NULL,
	[physical_financial_flag] [char](1) NULL,
	[Booked] [char](1) NULL,
	[process_deal_status] [int] NULL,
	[fixed_cost] [numeric](38, 20) NULL,
	[multiplier] [numeric](38, 20) NULL,
	[adder_currency_id] [int] NULL,
	[fixed_cost_currency_id] [int] NULL,
	[formula_currency_id] [int] NULL,
	[price_adder2] [numeric](38, 20) NULL,
	[price_adder_currency2] [int] NULL,
	[volume_multiplier2] [numeric](38, 20) NULL,
	[total_volume] [numeric](38, 20) NULL,
	[pay_opposite] [varchar](1) NULL,
	[capacity] [numeric](38, 20) NULL
) ON [PRIMARY]

go


if OBJECT_ID('delete_source_deal_header') is  null
CREATE TABLE [dbo].[delete_source_deal_header](
	rowid int IDENTITY(1,1) NOT NULL,
	[source_deal_header_id] [int] ,
	[source_system_id] [int] NOT NULL,
	[deal_id] [varchar](50) NOT NULL,
	[deal_date] [datetime] NOT NULL,
	[ext_deal_id] [varchar](50) NULL,
	[physical_financial_flag] [char](10) NOT NULL,
	[structured_deal_id] [varchar](50) NULL,
	[counterparty_id] [int] NOT NULL,
	[entire_term_start] [datetime] NOT NULL,
	[entire_term_end] [datetime] NOT NULL,
	[source_deal_type_id] [int] NOT NULL,
	[deal_sub_type_type_id] [int] NULL,
	[option_flag] [char](1) NOT NULL,
	[option_type] [char](1) NULL,
	[option_excercise_type] [char](1) NULL,
	[source_system_book_id1] [int] NOT NULL,
	[source_system_book_id2] [int] NULL,
	[source_system_book_id3] [int] NULL,
	[source_system_book_id4] [int] NULL,
	[description1] [varchar](100) NULL,
	[description2] [varchar](50) NULL,
	[description3] [varchar](50) NULL,
	[deal_category_value_id] [int] NOT NULL,
	[trader_id] [int] NOT NULL,
	[internal_deal_type_value_id] [int] NULL,
	[internal_deal_subtype_value_id] [int] NULL,
	[template_id] [int] NULL,
	[header_buy_sell_flag] [varchar](1) NULL,
	[broker_id] [int] NULL,
	[generator_id] [int] NULL,
	[status_value_id] [int] NULL,
	[status_date] [datetime] NULL,
	[assignment_type_value_id] [int] NULL,
	[compliance_year] [int] NULL,
	[state_value_id] [int] NULL,
	[assigned_date] [datetime] NULL,
	[assigned_by] [varchar](50) NULL,
	[generation_source] [varchar](250) NULL,
	[aggregate_environment] [varchar](1) NULL,
	[aggregate_envrionment_comment] [varchar](250) NULL,
	[rec_price] [float] NULL,
	[rec_formula_id] [int] NULL,
	[rolling_avg] [char](1) NULL,
	[contract_id] [int] NULL,
	[create_user] [varchar](50) NULL,
	[create_ts] [datetime] NULL,
	[update_user] [varchar](50) NULL,
	[update_ts] [datetime] NULL,
	[legal_entity] [int] NULL,
	[internal_desk_id] [int] NULL,
	[product_id] [int] NULL,
	[internal_portfolio_id] [int] NULL,
	[commodity_id] [int] NULL,
	[reference] [varchar](250) NULL,
	[deal_locked] [char](1) NULL,
	[close_reference_id] [int] NULL,
	[block_type] [int] NULL,
	[block_define_id] [int] NULL,
	[granularity_id] [int] NULL,
	[Pricing] [int] NULL,
	[deal_reference_type_id] [int] NULL,
	[unit_fixed_flag] [char](1) NULL,
	[broker_unit_fees] [float] NULL,
	[broker_fixed_cost] [float] NULL,
	[broker_currency_id] [int] NULL,
	[deal_status] [int] NULL,
	[term_frequency] [char](1) NULL,
	[option_settlement_date] [datetime] NULL,
	[verified_by] [varchar](50) NULL,
	[verified_date] [datetime] NULL,
	[risk_sign_off_by] [varchar](50) NULL,
	[risk_sign_off_date] [datetime] NULL,
	[back_office_sign_off_by] [varchar](50) NULL,
	[back_office_sign_off_date] [datetime] NULL,
	[book_transfer_id] [int] NULL,
	[confirm_status_type] [int] NULL
 )