IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_deal_header') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_deal_header'  , 'Deal' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_deal_detail') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_deal_detail'  , 'Deal Detail' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_counterparty') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_counterparty'  , 'Counterparty' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_traders') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_traders'  , 'Trader' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'contract_group') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'contract_group'  , 'Contract' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_book') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_book'  , 'Source Book' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_commodity') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_commodity'  , 'Commodity' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_currency') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_currency'  , 'Currency' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_deal_type') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_deal_type'  , 'Deal Type' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_price_curve_def') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_price_curve_def'  , 'Price Curve' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_uom') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_uom'  , 'UOM' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_minor_location') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_minor_location'  , 'Location' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'static_data_value') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'static_data_value'  , 'Static Data' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'formula_editor') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'formula_editor'  , 'Formula' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'meter_id') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'meter_id'  , 'Meter' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_deal_header_template') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_deal_header_template'  , 'Template' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'contract_group_detail') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'contract_group_detail'  , 'Contract Group Detail' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'user_defined_fields_template') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'user_defined_fields_template'  , 'User Defined Fields Template' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'maintain_field_template_detail') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'maintain_field_template_detail'  , 'Maintain Field Template Detail' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'maintain_field_template') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'maintain_field_template'  , 'Maintain Field Template' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'maintain_field_template_group') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'maintain_field_template_group'  , 'Maintain Field Template Group' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'maintain_field_deal') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'maintain_field_deal'  , 'Maintain Field Deal' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'application_users') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'application_users'  , 'Application Users' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_deal_detail_template') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_deal_detail_template'  , 'Source Deal Detail Template' END

IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'time_zones') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'time_zones'  , 'Time Zones' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'region') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'region'  , 'Region' END

-- ADDED FOR Contract Detail Export
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'source_system_description') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'source_system_description'  , 'Source System Description' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'Contract_report_template') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'Contract_report_template'  , 'Contract Report Template' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'contract_charge_type') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'contract_charge_type'  , 'Contract Charge' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'contract_charge_type_detail') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'contract_charge_type_detail'  , 'Contract Charge Detail' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'adjustment_default_gl_codes') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'adjustment_default_gl_codes'  , 'Adjustment GL Codes' END

-- ADDED FOR Alert
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'process_risk_controls') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'process_risk_controls'  , 'Process Risk Controls' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_sql') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_sql'  , 'Alert Sql' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_rule_table') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_rule_table'  , 'Alert Rule Table' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_table_relation') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_table_relation'  , 'Alert Table Relation' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_table_where_clause') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_table_where_clause'  , 'Alert Table Where Clause' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_conditions') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_conditions'  , 'Alert Conditions' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_actions') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_actions'  , 'Alert Actions' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_actions_events') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_actions_events'  , 'Alert Actions Events' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_workflows') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_workflows'  , 'Alert Workflows' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_reports') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_reports'  , 'Alert Reports' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_users') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_users'  , 'Alert Users' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'portfolio_hierarchy') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'portfolio_hierarchy'  , 'Portfolio Hierarchy' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'process_requirement_revision') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'process_requirement_revision'  , 'Process Requirement Revision' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_table_definition') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_table_definition'  , 'Alert Table Definition' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'alert_columns_definition') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'alert_columns_definition'  , 'Alert Columns Definition' END


--- For counterparty
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_bank_info') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_bank_info'  , 'Counterparty Bank info' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_contract_address') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_contract_address'  , 'Counterparty Contract address' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_epa_account') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_epa_account'  , 'counterparty epa account' END

IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_credit_info') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_credit_info'  , 'counterparty credit info' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_limits') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_limits'  , 'counterparty limits' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_confirm_info') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_confirm_info'  , 'counterparty confirm info' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'counterparty_invoice_info') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'counterparty_invoice_info'  , 'counterparty invoice info' END
IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'deal_detail_hour') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'deal_detail_hour'  , 'deal_detail_hour info' END

--IF NOT EXISTS (SELECT 1 FROM ixp_exportable_table it WHERE it.ixp_exportable_table_name = 'netting_group_detail_contract') BEGIN INSERT INTO ixp_exportable_table (ixp_exportable_table_name, ixp_exportable_table_description)    SELECT 'netting_group_detail_contract'  , 'netting group detail contract' END




UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Deal Header' WHERE ixp_exportable_table_name = 'source_deal_header'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Deal Header' WHERE ixp_exportable_table_name = 'source_deal_header'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Deal Detail' WHERE ixp_exportable_table_name = 'source_deal_detail'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Counterparty' WHERE ixp_exportable_table_name = 'source_counterparty'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Traders' WHERE ixp_exportable_table_name = 'source_traders'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Contract Group' WHERE ixp_exportable_table_name = 'contract_group'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Book' WHERE ixp_exportable_table_name = 'source_book'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Commodity' WHERE ixp_exportable_table_name = 'source_commodity'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Currency' WHERE ixp_exportable_table_name = 'source_currency'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Deal Type' WHERE ixp_exportable_table_name = 'source_deal_type'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Price Curve' WHERE ixp_exportable_table_name = 'source_price_curve_def'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source UOM' WHERE ixp_exportable_table_name = 'source_uom'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Location' WHERE ixp_exportable_table_name = 'source_minor_location'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Static Data' WHERE ixp_exportable_table_name = 'static_data_value'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Formula Editor' WHERE ixp_exportable_table_name = 'formula_editor'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Meter' WHERE ixp_exportable_table_name = 'meter_id'
UPDATE ixp_exportable_table SET ixp_exportable_table_description = 'Source Deal Template' WHERE ixp_exportable_table_name = 'source_deal_header_template'
