/*******Insert into static_data_type contract component ****************************/
insert static_data_type(type_id,type_name,internal,description )values (10019,'Contract Components',0,'Contract Components' )  

/*********************Insert static_data_value for contract_component **************/
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'CC-Disc','Customer Charge Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'CC','Customer Charge',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj','Fuel Cost Adj',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DC','Demand ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DC-Disc','Demand Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-Pm','Fuel Cost Adj. Prior Month',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DFC','Distribution Facility Charge',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DC-Off','Demand Cost, Off-Peak',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DC-On','Demand Cost, On-Peak',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC','Energy ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Wind_EC','Wind Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC-Disc','Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC-Off','Off Peak Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC-On','On Peak Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-On','Fuel Cost Adj. On-Peak',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Misc-DC','Misc. Adjustment Demand',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Misc-EC','Misc. Adjustment Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Misc-Other','Misc. Adjustment Other',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'OC','Ownership Charge',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SAFC','Service & Facility Charge',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-Off','Fuel Cost Adj. Off-Peak',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-Disc','Fuel Cost Adj-Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'AIC','Annual Interupt Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'ACF-Att. H Ferc','Attachment H FERC Annual Charge Fee',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'BR-Transmission','Base Rate-Transmission Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'CIP-EC','CIP Rider-Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'CIP-EC-Disc','CIP Rider-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DC-Adj','Demand Adjustment',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DS','Distribution Service',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EIR-DC','EIR-Demand',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EIR-EC','EIR-Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EIR-EC-Disc','EIR-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC-Take','Energy-Take or Pay',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-PM-Disc','Fuel Cost Adj- Prior Month-Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-Adj-PM-True','Fuel Cost Adj-Prior Month True up',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'GP','Graphs Package',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'MISO-Trans','MISO Transmission Pass Thru',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Monthly-IC','Monthly Interupt Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Other','Other',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RA','Rate Adder',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RDF-EC','RDF Rider-Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RDF-EC-Disc','RDF Rider-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RSAVC','Reactive Supply & Voltage Control',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RAFR','Regulation & Frequency Response',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SSCAD','Schedule System Control & Dispatch',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SEP-EC','SEP Rider-Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SEP-EC-Disc','SEP Rider-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SR','Spinning Reserve',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Supp-R','Supplemental Reserve',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'TCR-EC','TCR Rider-Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'TCR-EC-Disc','TCR Rider-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'TS','Transmission Service',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'SC-D','System control and Dispatch',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EC (2)','Energy (2)',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC','Fuel',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'MISO CL Credit','MISO Congestion and Losses Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Transmission Credit - Demand','Transmission Credit - Demand',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'DCC','Demand Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'EIR-Demand Discount','EIR-Demand Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'TC','Transmission Capacity',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'E-C','Energy Credit',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FCA-Discount','Fuel Cost Adj-Prior Month True-up Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC AdJ-On-Disc','Fuel Cost Adj-On Peak-Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'FC-ADJ-Off_Disc','Fuel Cost Adj-Off Peak-Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'REC-R','REC Rider',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RES-Rider','RES-Rider',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'RES-EC-Disc','RES Rider-Energy Discount',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10019,'Annual Interrupt Credit Accrual','Annual Interrupt Credit Accrual',NULL,NULL,NULL,NULL) 


/*****Insert static_data_type EQR Product Name  *************/

insert static_data_type(type_id,type_name,internal,description )values (10077,'EQR Product Name',0,'EQR Product Name')

/*********************Insert static_data_value for EQR Product Name**************/

insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'BOOKED OUT POWER ','BOOKED OUT POWER ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'CAPACITY ','CAPACITY ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'CUSTOMER CHARGE ','CUSTOMER CHARGE ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'EMERGENCY ENERGY','EMERGENCY ENERGY',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'ENERGY ','ENERGY ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'FUEL CHARGE ','FUEL CHARGE ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'OTHER ','OTHER ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'REACTIVE SUPPLY & VOLTAGE CONTROL','REACTIVE SUPPLY & VOLTAGE CONTROL',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'REGULATION & FREQUENCY RESPONSE ','REGULATION & FREQUENCY RESPONSE ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'SCHEDULE SYSTEM CONTROL & DISPATCH ','SCHEDULE SYSTEM CONTROL & DISPATCH ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'SPINNING RESERVE ','SPINNING RESERVE ',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10077,'SUPPLEMENTAL RESERVE ','SUPPLEMENTAL RESERVE ',NULL,NULL,NULL,NULL) 

/*****Insert static_data_type group_by  *************/

insert static_data_type(type_id,type_name,internal,description )values (10081,'group_by',0,'group_by')

/*********************Insert static_data_value for group_by**************/

insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10081,'Demand and Energy','Demand and Energy',NULL,NULL,NULL,NULL) 
insert static_data_value ( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10081,'Transmission','Transmission',NULL,NULL,NULL,NULL) 


/*****Insert static_data_type Term Name  *************/

insert static_data_type(type_id,type_name,internal,description )values (1120,'Term Name',1,'Term Name')

/*****  Insert static_data_value for Term Name  *********************/

SET IDENTITY_INSERT STATIC_DATA_VALUE ON

insert STATIC_DATA_VALUE( value_id,type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 1120,1120,'LT','Long Term',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( value_id,type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 1122,1120,'N/A','Not Applicable',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( value_id,type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 1121,1120,'ST','Short Term',NULL,NULL,NULL,NULL)
 
SET IDENTITY_INSERT STATIC_DATA_VALUE off

/*****Insert static_data_type EQR Balancing Authority  *************/

insert static_data_type(type_id,type_name,internal,description )values (10078,'EQR Balancing Authority',0,'EQR Balancing Authority')

/*****  Insert static_data_value for EQR Balancing Authority *********************/

insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'CLEC','CLEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'CWLD','CWLD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'CFE','CFE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PUPP','PUPP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'BUBA','BUBA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DERS','BUBA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'CNWY','CNWY',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GRMA','GRMA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'HGMA','HGMA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DENL','DENL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WMUC','WMUC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DPC','DPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DEAA','DEAA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DUK','DUK',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'EKPC','EKPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'EPE','EPE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'EEI','EEI',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'EDE','EDE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'EES','EES',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'ERCO','ERCO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'FMPP','FMPP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'FPL','FPL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'FPC','FPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GVL','GVL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GSOC','GSOC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GTC','GTC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GRDA','GRDA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GCPD','GCPD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GRE','GRE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GREC','GREC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GREN','GREN',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GRES','GRES',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'GA','GA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'HE','HE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'HQT','HQT',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IPCO','IPCO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IP','IP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IPRV','IPRV',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IID','IID',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IPL','IPL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'ISNE','ISNE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'JEA','JEA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'KCPL','KCPL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LAFA','LAFA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LGEE','LGEE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LES','LES',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LDWP','LDWP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LEPA','LEPA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'LAGN','LAGN',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MGE','MGE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MHEB','MHEB',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MECS','MECS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'CONS','CONS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DECO','DECO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MEC','MEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MISO','MISO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MP','MP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MDU','MDU',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MPW','MPW',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NPPD','NPPD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NEVP','NEVP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NBPC','NBPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NHC1','NHC1',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NYIS','NYIS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TEST','TEST',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NIPS','NIPS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NSP','NSP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NWMT','NWMT',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'OVEC','OVEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'OKGE','OKGE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'IMO','IMO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'OPPD','OPPD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'OTP','OTP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'DOPD','DOPD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PACE','PACE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PACW','PACW',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PJM','PJM',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PGE','PGE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PSCO','PSCO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PNM','PNM',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'PSEI','PSEI',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'RC','RC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SMUD','SMUD',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SRP','SRP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SC','SC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SPC','SPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SCL','SCL',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SEC','SEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SPPC','SPPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SCEG','SCEG',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SME','SME',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SMEE','SMEE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SEHA','SEHA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SERU','SERU',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SETH','SETH',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SOCO','SOCO',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SIPC','SIPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SIGE','SIGE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SMP','SMP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SWPP','SWPP',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SPA','SPA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SPS','SPS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'SECI','SECI',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TPWR','TPWR',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TEC','TEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TVA','TVA',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'HUB','HUB',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TLKN','TLKN',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TEPC','TEPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'TIDC','TIDC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'UPPC','UPPC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'NSB','NSB',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'MOWR','MOWR',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WACM','WACM',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WALC','WALC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WAUE','WAUE',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WAUW','WAUW',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WFEC','WFEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WR','WR',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WEC','WEC',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'WPS','WPS',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10078,'YAD','YAD',NULL,NULL,NULL,NULL) 

/*****Insert static_data_type Hourly Block  *************/

insert static_data_type(type_id,type_name,internal,description )values (10018,'Hourly Block',0,'Hourly Block')

/*****  Insert static_data_value for Hourly Block *********************/

insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10018,'Hourly_Denver','Hourly_Denver',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10018,'Hourly_hr7_to_hr22','Hourly_hr7_to_hr22',NULL,NULL,NULL,NULL) 
insert STATIC_DATA_VALUE( type_id,code,description,entity_id,xref_value_id,xref_value,category_id)
values ( 10018,'Hourly_hr9_to_hr9','Hourly_hr9_to_hr9',NULL,NULL,NULL,NULL) 




