SET IDENTITY_INSERT STATIC_data_value ON 
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES (291975,10018,'WeekendPlus 9_20','WeekendPlus 9_20',NULL,NULL,NULL,NULL)	
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291976,10018,'BE-WkndBase;2x24;0-24','BE-WkndBase;2x24;0-24',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291899,10018,'NL-Peak;5x12;8-20','NL-Peak;5x12;8-20',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291947,10018,'Intra Day- Hr 3','Intra Day- Hr 3',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292024,10018,'Test hour block term','Test hour block term',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291974,10018,'11-14','11-14',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292032,10018,'test 2','test 2',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292033,10018,'test 3','test 3',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292016,10018,'test','test',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292054,10018,'NL-Offpeak;5x12;8-20','NL-Offpeak;5x12;8-20',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292094,10018,'0001','test hour',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292115,10018,'sudan','sudan',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291900,10018,'Hourly_hr7_to_hr22','Hourly_hr7_to_hr22',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291969,10018,'Hourly_hr7_to_hr23','Hourly_hr7_to_hr23',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292020,10018,'BE-Onpeak;5x15,8-22','BE-Onpeak;5x15,8-22',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292080,10018,'Belgian_wdayoffpeak','Belgian_wdayoffpeak',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292081,10018,'Belgian_Weekendbase','Belgian_Weekendbase',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292116,10018,'1100','55',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291993,10018,'Base Load(DST Not Applied)','Base Load(DST Not Applied)',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291994,10018,'BE-OffPeak;5x12,2x24;20-8,0-24','BE-OffPeak;5x12,2x24;20-8,0-24',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291995,10018,'NL-OffPeak;5x12;2x24;20-8;0-24','NL-OffPeak;5x12;2x24;20-8;0-24',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291996,10018,'NL-OffPeak;5x8,2x24;23-7,0-24','NL-OffPeak;5x8,2x24;23-7,0-24',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291997,10018,'NL-Peak;5x16;7-23','NL-Peak;5x16;7-23',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291998,10018,'NL-Shoulder;5x4;7-8,21-23','NL-Shoulder;5x4;7-8,21-23',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292025,10018,'test23','test23',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291985,10018,'Intra Day- Hr 21','Intra Day- Hr 21',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291890,10018,'Base Load','Base Load',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292014,10018,'NL-WkndBase;2x24;0-24','NL-WkndBase;2x24;0-24',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292079,10018,'Belgian_peak','Belgian_peak',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(292010,10018,'NL-Wkndpeak 2x12;8-20','NL-Wkndpeak 2x12;8-20',NULL,NULL,NULL,NULL)
INSERT INTO static_data_value(value_id,TYPE_ID,code,DESCRIPTION,entity_id,xref_value_id,xref_value,category_id)
VALUES(291977,10018,'BE-Peak;5x12;8-20','BE-Peak;5x12;8-20',NULL,NULL,NULL,NULL)
SET IDENTITY_INSERT STATIC_data_value OFF 