IF Exists(Select 1 from Application_functions where function_id  =  10101162)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Add/Save Confirmation Rule' ,func_ref_id  = 10101161  Where function_id = 10101162  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10101162,'Add/Save','Add/Save Confirmation Rule',10101161) END
IF Exists(Select 1 from Application_functions where function_id  =  10101163)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Confirmation Rule' ,func_ref_id  = 10101161  Where function_id = 10101163  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10101163,'Delete','Delete Confirmation Rule',10101161) END
IF Exists(Select 1 from Application_functions where function_id  =  10102801)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Add/Save Profile' ,func_ref_id  = 10102800  Where function_id = 10102801  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10102801,'Add/Save','Add/Save Profile',10102800) END
IF Exists(Select 1 from Application_functions where function_id  =  10102802)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Profile' ,func_ref_id  = 10102800  Where function_id = 10102802  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10102802,'Delete','Delete Profile',10102800) END
IF Exists(Select 1 from Application_functions where function_id  =  10132313)   Begin   Update application_functions set function_name = 'Unlock', function_desc = 'Unlock' ,func_ref_id  = 10132300  Where function_id = 10132313  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10132313,'Unlock','Unlock',10132300) END
IF Exists(Select 1 from Application_functions where function_id  =  10163210)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Dashboard Manager IU' ,func_ref_id  = 10163200  Where function_id = 10163210  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10163210,'Add/Save','Dashboard Manager IU',10163200) END
IF Exists(Select 1 from Application_functions where function_id  =  10164410)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'View and Edit Nomination IU' ,func_ref_id  = 10164400  Where function_id = 10164410  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10164410,'Add/Save','View and Edit Nomination IU',10164400) END
IF Exists(Select 1 from Application_functions where function_id  =  10164411)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete View and Edit Nomination' ,func_ref_id  = 10164400  Where function_id = 10164411  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10164411,'Delete','Delete View and Edit Nomination',10164400) END
IF Exists(Select 1 from Application_functions where function_id  =  10166511)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Actualize Schedules' ,func_ref_id  = 10166500  Where function_id = 10166511  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166511,'Delete','Delete Actualize Schedules',10166500) END
IF Exists(Select 1 from Application_functions where function_id  =  10166512)   Begin   Update application_functions set function_name = 'Schedules', function_desc = 'Schedules - Actualize Schedules' ,func_ref_id  = 10166500  Where function_id = 10166512  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166512,'Schedules','Schedules - Actualize Schedules',10166500) END
IF Exists(Select 1 from Application_functions where function_id  =  10166513)   Begin   Update application_functions set function_name = 'Save', function_desc = 'Save - Schedules - Actualize Schedules' ,func_ref_id  = 10166512  Where function_id = 10166513  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166513,'Save','Save - Schedules - Actualize Schedules',10166512) END
IF Exists(Select 1 from Application_functions where function_id  =  10166514)   Begin   Update application_functions set function_name = 'Unmatch', function_desc = 'Unmatch - Schedules - Actualize Schedules' ,func_ref_id  = 10166512  Where function_id = 10166514  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166514,'Unmatch','Unmatch - Schedules - Actualize Schedules',10166512) END
IF Exists(Select 1 from Application_functions where function_id  =  10166710)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Add/Save Generation Reserve Planner' ,func_ref_id  = 10166700  Where function_id = 10166710  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166710,'Add/Save','Add/Save Generation Reserve Planner',10166700) END
IF Exists(Select 1 from Application_functions where function_id  =  10166711)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Generation Reserve Planner' ,func_ref_id  = 10166700  Where function_id = 10166711  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166711,'Delete','Delete Generation Reserve Planner',10166700) END
IF Exists(Select 1 from Application_functions where function_id  =  10166910)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Add/Save' ,func_ref_id  = 10166900  Where function_id = 10166910  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166910,'Add/Save','Add/Save',10166900) END
IF Exists(Select 1 from Application_functions where function_id  =  10166911)   Begin   Update application_functions set function_name = 'Update', function_desc = 'Update' ,func_ref_id  = 10166900  Where function_id = 10166911  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166911,'Update','Update',10166900) END
IF Exists(Select 1 from Application_functions where function_id  =  10166912)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete' ,func_ref_id  = 10166900  Where function_id = 10166912  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10166912,'Delete','Delete',10166900) END
IF Exists(Select 1 from Application_functions where function_id  =  10167210)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Forecast Parameters Mapping IU' ,func_ref_id  = 10167200  Where function_id = 10167210  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10167210,'Add/Save','Forecast Parameters Mapping IU',10167200) END
IF Exists(Select 1 from Application_functions where function_id  =  10167211)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Forecast Parameters Mapping' ,func_ref_id  = 10167200  Where function_id = 10167211  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10167211,'Delete','Delete Forecast Parameters Mapping',10167200) END
IF Exists(Select 1 from Application_functions where function_id  =  10181213)   Begin   Update application_functions set function_name = 'Run', function_desc = 'Run - Run At Risk Measurement' ,func_ref_id  = 10181200  Where function_id = 10181213  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10181213,'Run','Run - Run At Risk Measurement',10181200) END
IF Exists(Select 1 from Application_functions where function_id  =  10181316)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Setup Limit Tab IU' ,func_ref_id  = 10181318  Where function_id = 10181316  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10181316,'Add/Save','Setup Limit Tab IU',10181318) END
IF Exists(Select 1 from Application_functions where function_id  =  10181317)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Setup Limit Tab IU' ,func_ref_id  = 10181318  Where function_id = 10181317  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10181317,'Delete','Delete Setup Limit Tab IU',10181318) END
IF Exists(Select 1 from Application_functions where function_id  =  10181318)   Begin   Update application_functions set function_name = 'Limit', function_desc = 'Limit - Maintain Limits' ,func_ref_id  = 10181300  Where function_id = 10181318  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10181318,'Limit','Limit - Maintain Limits',10181300) END
IF Exists(Select 1 from Application_functions where function_id  =  10183012)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Curve Mapping Tab IU' ,func_ref_id  = 10183014  Where function_id = 10183012  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10183012,'Add/Save','Curve Mapping Tab IU',10183014) END
IF Exists(Select 1 from Application_functions where function_id  =  10183013)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Curve Mapping Tab' ,func_ref_id  = 10183014  Where function_id = 10183013  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10183013,'Delete','Delete Curve Mapping Tab',10183014) END
IF Exists(Select 1 from Application_functions where function_id  =  10183014)   Begin   Update application_functions set function_name = 'Curve Mapping', function_desc = 'Curve Mapping' ,func_ref_id  = 10183000  Where function_id = 10183014  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10183014,'Curve Mapping','Curve Mapping',10183000) END
IF Exists(Select 1 from Application_functions where function_id  =  10202120)   Begin   Update application_functions set function_name = 'NorthPool Position Report', function_desc = 'NorthPool Position Report' ,func_ref_id  = 10202200  Where function_id = 10202120  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10202120,'NorthPool Position Report','NorthPool Position Report',10202200) END
IF Exists(Select 1 from Application_functions where function_id  =  10241110)   Begin   Update application_functions set function_name = 'Add/Save', function_desc = 'Apply Cash IU' ,func_ref_id  = 10241100  Where function_id = 10241110  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10241110,'Add/Save','Apply Cash IU',10241100) END
IF Exists(Select 1 from Application_functions where function_id  =  10241111)   Begin   Update application_functions set function_name = 'Delete', function_desc = 'Delete Apply Cash' ,func_ref_id  = 10241100  Where function_id = 10241111  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10241111,'Delete','Delete Apply Cash',10241100) END
IF Exists(Select 1 from Application_functions where function_id  =  10241112)   Begin   Update application_functions set function_name = 'Write Off', function_desc = 'Write Off Apply Cash' ,func_ref_id  = 10241100  Where function_id = 10241112  End  Else Begin INSERT INTO application_functions(function_id,function_name,function_desc,func_ref_id)  VALUES(10241112,'Write Off','Write Off Apply Cash',10241100) END
