INSERT INTO counterparty_credit_info_audit (counterparty_credit_info_id,
	Counterparty_id, account_status, limit_expiration, credit_limit, curreny_code, Tenor_limit, Industry_type1, 
	Industry_type2, SIC_Code, Duns_No, Risk_rating, Debt_rating, Ticker_symbol, Date_established, Next_review_date, 
	Last_review_date, Customer_since, Approved_by, Watch_list, Settlement_contact_name, Settlement_contact_address, 
	Settlement_contact_address2, Settlement_contact_phone, Settlement_contact_email, payment_contact_name, payment_contact_address, 
	contactfax, payment_contact_phone, payment_contact_email, Debt_Rating2, Debt_Rating3, Debt_Rating4, Debt_Rating5, credit_limit_from, 
	payment_contact_address2, max_threshold, min_threshold, check_apply, cva_data, pfe_criteria, create_user, create_ts, 
	update_user, update_ts, exclude_exposure_after, user_action
)
SELECT 
	cci.counterparty_credit_info_id,
	cci.Counterparty_id,
	cci.account_status,
	cci.limit_expiration,
	cci.credit_limit,
	cci.curreny_code,
	cci.Tenor_limit,
	cci.Industry_type1,
	cci.Industry_type2,
	cci.SIC_Code,
	cci.Duns_No,
	cci.Risk_rating,
	cci.Debt_rating,
	cci.Ticker_symbol,
	cci.Date_established,
	cci.Next_review_date,
	cci.Last_review_date,
	cci.Customer_since,
	cci.Approved_by,
	cci.Watch_list,
	cci.Settlement_contact_name,
	cci.Settlement_contact_address,
	cci.Settlement_contact_address2,
	cci.Settlement_contact_phone,
	cci.Settlement_contact_email,
	cci.payment_contact_name,
	cci.payment_contact_address,
	cci.contactfax,
	cci.payment_contact_phone,
	cci.payment_contact_email,
	cci.Debt_Rating2,
	cci.Debt_Rating3,
	cci.Debt_Rating4,
	cci.Debt_Rating5,
	cci.credit_limit_from,
	cci.payment_contact_address2,
	cci.max_threshold,
	cci.min_threshold,
	cci.check_apply,
	cci.cva_data,
	cci.pfe_criteria,
	cci.create_user,
	cci.create_ts,
	cci.update_user,
	cci.update_ts,
	cci.exclude_exposure_after,
	'u'
FROM counterparty_credit_info cci
LEFT JOIN counterparty_credit_info_audit ccia ON cci.counterparty_credit_info_id = ccia.counterparty_credit_info_id
WHERE ccia.audit_id IS NULL


