IF NOT EXISTS (SELECT 1 FROM ixp_tables it WHERE it.ixp_tables_name = 'ixp_pipeline_cut_data_template') BEGIN INSERT INTO ixp_tables (ixp_tables_name, ixp_tables_description, import_export_flag)    SELECT 'ixp_pipeline_cut_data_template'  , 'Piplline Cut Data', 'i' END

INSERT INTO ixp_table_meta_data (ixp_tables_id, table_name)
SELECT it.ixp_tables_id,
       it.ixp_tables_name
FROM   ixp_tables it
LEFT JOIN ixp_table_meta_data itmd ON itmd.ixp_tables_id = it.ixp_tables_id
WHERE itmd.ixp_table_meta_data_table_id IS NULL

-- ixp_pipeline_cut_data_template starts
DECLARE @ixp_pipeline_cut_data_template_id INT	
SELECT @ixp_pipeline_cut_data_template_id = it.ixp_tables_id FROM   ixp_tables it WHERE  it.ixp_tables_name = 'ixp_pipeline_cut_data_template'

IF @ixp_pipeline_cut_data_template_id IS NOT NULL
BEGIN
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'purchase_report_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'purchase_report_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'transport_report_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'transport_report_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'receipt_location_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'receipt_location_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'receipt_location' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'receipt_location', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'svc_req' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'svc_req', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'delivery_date_from' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'delivery_date_from', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'delivery_date_to' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'delivery_date_to', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'deal_date' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'deal_date', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nominated_receipt' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nominated_receipt', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nominated_delivery' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nominated_delivery', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'scheduled_receipt' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'scheduled_receipt', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'scheduled_delivery' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'scheduled_delivery', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'contract' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'contract', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'package_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'package_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'transportation_contract' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'transportation_contract', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cpty_duns_no' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cpty_duns_no', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'counterparty' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'counterparty', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'up_pkg_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'up_pkg_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'delivery_location_id' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'delivery_location_id', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'actual_receipt' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'actual_receipt', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'delivery_location' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'delivery_location', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr1' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr1', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr3' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr3', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr4' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr4', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr5' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr5', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr6' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr6', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr7' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr7', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr8' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr8', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr9' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr9', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr10' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr10', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr11' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr11', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr12' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr12', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr13' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr13', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr14' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr14', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr15' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr15', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr16' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr16', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr17' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr17', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr18' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr18', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr19' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr19', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr20' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr20', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr21' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr21', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr22' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr22', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr23' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr23', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr24' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr24', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr25' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr25', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr26' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr26', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr27' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr27', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr28' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr28', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr29' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr29', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr30' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr30', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr31' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr31', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr32' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr32', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr33' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr33', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr34' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr34', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr35' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr35', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr36' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr36', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr37' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr37', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr38' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr38', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr39' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr39', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr40' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr40', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr41' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr41', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr42' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr42', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr43' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr43', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr44' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr44', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr45' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr45', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr46' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr46', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr47' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr47', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr48' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr48', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr49' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr49', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr50' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr50', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr51' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr51', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr52' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr52', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr53' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr53', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr54' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr54', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr55' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr55', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr56' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr56', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr57' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr57', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr58' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr58', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr59' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr59', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr60' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr60', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr61' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr61', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr62' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr62', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr63' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr63', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr64' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr64', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr65' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr65', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr66' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr66', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr67' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr67', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr68' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr68', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr69' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr69', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr70' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr70', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr71' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr71', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr72' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr72', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr73' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr73', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr74' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr74', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr75' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr75', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr76' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr76', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr77' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr77', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr78' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr78', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr79' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr79', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr80' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr80', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr81' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr81', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr82' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr82', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr83' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr83', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr84' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr84', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr85' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr85', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr86' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr86', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr87' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr87', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr88' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr88', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr89' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr89', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr90' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr90', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr91' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr91', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr92' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr92', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr93' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr93', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr94' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr94', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr95' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr95', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr96' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr96', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr97' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr97', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr98' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr98', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr99' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr99', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr100' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr100', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr101' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr101', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr102' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr102', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr103' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr103', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr104' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr104', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr105' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr105', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr106' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr106', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr107' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr107', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr108' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr108', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr109' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr109', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr110' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr110', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr111' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr111', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr112' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr112', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr113' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr113', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'nr114' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'nr114', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_type1' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_type1', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_type2' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_type2', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_type3' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_type3', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_type4' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_type4', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_value1' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_value1', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_value2' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_value2', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_value3' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_value3', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut_value4' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut_value4', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut1_value_del' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut1_value_del', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut2_value_del' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut2_value_del', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut3_value_del' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut3_value_del', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'cut4_value_del' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'cut4_value_del', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'mdq_original' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'mdq_original', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'mdq_available' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'mdq_available', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'filename' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'filename', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'error' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'error', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'create_ts' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'create_ts', 0, NULL END
	IF NOT EXISTS (SELECT * FROM ixp_columns WHERE ixp_columns_name = 'file_type' AND ixp_table_id = @ixp_pipeline_cut_data_template_id) BEGIN INSERT INTO ixp_columns (ixp_table_id, ixp_columns_name, is_major, header_detail) SELECT @ixp_pipeline_cut_data_template_id, 'file_type', 0, NULL END
END
ELSE
BEGIN
	SELECT 'ixp_pipeline_cut_data_template not present in ixp_tables'
END
-- ixp_pipeline_cut_data_template END

--SELECT * FROM ixp_columns WHERE ixp_table_id = 2074

