CREATE SYNONYM source_deal_settlement_arch1 FOR farrmsarch.trmtracker_essent.dbo.source_deal_settlement_arch1
CREATE SYNONYM source_deal_settlement_arch2 FOR farrmsarch.trmtracker_essent.dbo.source_deal_settlement_arch2

CREATE SYNONYM Calc_formula_value_arch1 FOR farrmsarch.trmtracker_essent.dbo.Calc_formula_value_arch1
CREATE SYNONYM Calc_formula_value_arch2 FOR farrmsarch.trmtracker_essent.dbo.Calc_formula_value_arch2

CREATE SYNONYM index_fees_breakdown_settlement_arch1 FOR farrmsarch.trmtracker_essent.dbo.index_fees_breakdown_settlement_arch1
CREATE SYNONYM index_fees_breakdown_settlement_arch2 FOR farrmsarch.trmtracker_essent.dbo.index_fees_breakdown_settlement_arch2
