/* 
Author : Santosh Gupta 
Date: 22nd  June 2012
Purpose: To Create Partition Scheme for MTM
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS ( select 1 FROM sys.partition_schemes WHERE [NAME] = N'PS_MTM_DEAL_PNL')
BEGIN 
CREATE PARTITION SCHEME [PS_MTM_DEAL_PNL]
AS 
PARTITION PF_MTM_DEAL_PNL TO 
([FG_DATE_001],[PRIMARY]
               )
END


---- source_deal_pnl_detail

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS ( select 1 FROM sys.partition_schemes WHERE [NAME] = N'PS_MTM_DEAL_PNL_DETAIL')
BEGIN 
CREATE PARTITION SCHEME [PS_MTM_DEAL_PNL_DETAIL]
AS 
PARTITION PF_MTM_DEAL_PNL_DETAIL TO 
([FG_DATE_001],[PRIMARY]
               )
END


--- Index_fee_settlement 

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS ( select 1 FROM sys.partition_schemes WHERE [NAME] = N'PS_MTM_INDEX_FEES')
BEGIN 
CREATE PARTITION SCHEME [PS_MTM_INDEX_FEES]
AS 
PARTITION PF_MTM_INDEX_FEES TO 
([FG_DATE_001],[PRIMARY]
               )
END