IF NOT EXISTS(SELECT 1 FROM partition_config_info  WHERE table_name = 'source_deal_settlement')
BEGIN
INSERT INTO [dbo].[partition_config_info]
           ([table_name]
           ,[no_partitions]
           ,[partition_nature]
           ,[partition_key]
           ,[function_name]
           ,[scheme_name]
           ,[frequency]
           ,[filegroup]
           ,[archive_status]
           ,[stage_table_name]
           ,[archive_table_name]
           ,[archive_db_name]
           ,[archive_server]
           ,[del_flg]
           ,[create_user]
           ,[create_ts]
           ,[update_user]
           ,[update_ts])
     VALUES
           ('source_deal_settlement'
           ,25
           ,'DATE'
           ,'as_of_date'
           ,'PF_source_settlement'
           ,'PS_source_settlement'
           ,'d'
           ,'FG_DATE'
           ,'Y'
           ,'source_deal_settlement'
           ,NULL
           ,NULL
           ,NULL
           ,'N'
           ,'SGUPTA'
           ,GETDATE()
           ,NULL
           ,NULL)
END

----------Insert value for mv90_data_mins
IF NOT EXISTS(SELECT 1 FROM partition_config_info  WHERE table_name = 'Calc_formula_value')
BEGIN
INSERT INTO [dbo].[partition_config_info]
           ([table_name]
           ,[no_partitions]
           ,[partition_nature]
           ,[partition_key]
           ,[function_name]
           ,[scheme_name]
           ,[frequency]
           ,[filegroup]
           ,[archive_status]
           ,[stage_table_name]
           ,[archive_table_name]
           ,[archive_db_name]
           ,[archive_server]
           ,[del_flg]
           ,[create_user]
           ,[create_ts]
           ,[update_user]
           ,[update_ts])
     VALUES
           ('Calc_formula_value'
           ,25
           ,'DATE'
           ,'prod_date'
           ,'PF_calc_settlement'
           ,'PS_calc_settlement'
           ,'d'
           ,'FG_DATE'
           ,'Y'
           ,'Calc_formula_value'
           ,NULL
           ,NULL
           ,NULL
           ,'N'
           ,'SGUPTA'
           ,GETDATE()
           ,NULL
           ,NULL)
END

----------Insert value for mv90_data_hour
IF NOT EXISTS(SELECT 1 FROM partition_config_info  WHERE table_name = 'index_fees_breakdown_settlement')
BEGIN
INSERT INTO [dbo].[partition_config_info]
           ([table_name]
           ,[no_partitions]
           ,[partition_nature]
           ,[partition_key]
           ,[function_name]
           ,[scheme_name]
           ,[frequency]
           ,[filegroup]
           ,[archive_status]
           ,[stage_table_name]
           ,[archive_table_name]
           ,[archive_db_name]
           ,[archive_server]
           ,[del_flg]
           ,[create_user]
           ,[create_ts]
           ,[update_user]
           ,[update_ts])
     VALUES
           ('index_fees_breakdown_settlement'
           ,25
           ,'DATE'
           ,'as_of_date'
           ,'PF_index_settlement'
           ,'PS_index_settlement'
           ,'d'
           ,'FG_DATE'
           ,'Y'
           ,'index_fees_breakdown_settlement'
           ,NULL
           ,NULL
           ,NULL
           ,'N'
           ,'SGUPTA'
           ,GETDATE()
           ,NULL
           ,NULL)
END
