/*
@license
dhtmlxScheduler v.4.3.35 Professional

This software is covered by DHTMLX Enterprise License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e._grid={sort_rules:{"int":function(e,t,a){return 1*a(e)<1*a(t)?1:-1},str:function(e,t,a){return a(e)<a(t)?1:-1},date:function(e,t,a){return new Date(a(e))<new Date(a(t))?1:-1}},_getObjName:function(e){return"grid_"+e},_getViewName:function(e){return e.replace(/^grid_/,"")}}}(),e.createGridView=function(t){function a(e){return!(void 0!==e&&(1*e!=e||0>e))}var i=t.name||"grid",n=e._grid._getObjName(i);e.config[i+"_start"]=t.from||new Date(0),e.config[i+"_end"]=t.to||new Date(9999,1,1),
e[n]=t,e[n].defPadding=8,e[n].columns=e[n].fields,e[n].unit=t.unit||"month",e[n].step=t.step||1,delete e[n].fields;for(var r=e[n].columns,s=0;s<r.length;s++)a(r[s].width)&&(r[s].initialWidth=r[s].width),a(r[s].paddingLeft)||delete r[s].paddingLeft,a(r[s].paddingRight)||delete r[s].paddingRight;e[n].select=void 0===t.select?!0:t.select,void 0===e.locale.labels[i+"_tab"]&&(e.locale.labels[i+"_tab"]=e[n].label||e.locale.labels.grid_tab),e[n]._selected_divs=[],e.date[i+"_start"]=function(a){return e.date[t.unit+"_start"]?e.date[t.unit+"_start"](a):a;
},e.date["add_"+i]=function(t,a){return e.date.add(t,a*e[n].step,e[n].unit)},e.templates[i+"_date"]=function(t,a){return e.templates.day_date(t)+" - "+e.templates.day_date(a)},e.templates[i+"_full_date"]=function(t,a,n){return e.isOneDayEvent(n)?this[i+"_single_date"](t):e.templates.day_date(t)+" &ndash; "+e.templates.day_date(a)},e.templates[i+"_single_date"]=function(t){return e.templates.day_date(t)+" "+this.event_date(t)},e.templates[i+"_field"]=function(e,t){return t[e]},e.attachEvent("onTemplatesReady",function(){
e.attachEvent("onDblClick",function(t,a){return this._mode==i?(e._click.buttons.details(t),!1):!0}),e.attachEvent("onClick",function(t,a){return this._mode==i&&e[n].select?(e._grid.unselectEvent("",i),e._grid.selectEvent(t,i,a),!1):!0});var t=e.render_data;e.render_data=function(a){return this._mode!=i?t.apply(this,arguments):void e._grid._fill_grid_tab(n)};var a=e.render_view_data;e.render_view_data=function(){var t=e._els.dhx_cal_data[0].lastChild;return this._mode==i&&t&&(e._grid._gridScrollTop=t.scrollTop),
a.apply(this,arguments)}}),e[i+"_view"]=function(t){if(e._grid._sort_marker=null,delete e._gridView,e._grid._gridScrollTop=0,e._rendered=[],e[n]._selected_divs=[],t){var a=null,r=null,s=e[n];s.paging?(a=e.date[i+"_start"](new Date(e._date)),r=e.date["add_"+i](a,1)):(a=e.config[i+"_start"],r=e.config[i+"_end"]),e._min_date=a,e._max_date=r,e._grid.set_full_view(n);var d="";+a>+new Date(0)&&+r<+new Date(9999,1,1)&&(d=e.templates[i+"_date"](a,r)),e._els.dhx_cal_date[0].innerHTML=d,e._gridView=n}}},e.dblclick_dhx_grid_area=function(){
!this.config.readonly&&this.config.dblclick_create&&this.addEventNow()},e._click.dhx_cal_header&&(e._old_header_click=e._click.dhx_cal_header),e._click.dhx_cal_header=function(t){if(e._gridView){var a=t||window.event,i=e._grid.get_sort_params(a,e._gridView);e._grid.draw_sort_marker(a.originalTarget||a.srcElement,i.dir),e.clear_view(),e._grid._fill_grid_tab(e._gridView,i)}else if(e._old_header_click)return e._old_header_click.apply(this,arguments)},e._grid.selectEvent=function(t,a,i){if(e.callEvent("onBeforeRowSelect",[t,i])){
var n=e._grid._getObjName(a);e.for_rendered(t,function(t){t.className+=" dhx_grid_event_selected",e[n]._selected_divs.push(t)}),e._select_id=t}},e._grid._unselectDiv=function(e){e.className=e.className.replace(/ dhx_grid_event_selected/,"")},e._grid.unselectEvent=function(t,a){var i=e._grid._getObjName(a);if(i&&e[i]._selected_divs)if(t){for(var n=0;n<e[i]._selected_divs.length;n++)if(e[i]._selected_divs[n].getAttribute("event_id")==t){e._grid._unselectDiv(e[i]._selected_divs[n]),e[i]._selected_divs.slice(n,1);
break}}else{for(var n=0;n<e[i]._selected_divs.length;n++)e._grid._unselectDiv(e[i]._selected_divs[n]);e[i]._selected_divs=[]}},e._grid.get_sort_params=function(t,a){var i=t.originalTarget||t.srcElement,n="desc",r=e._getClassName(i);"dhx_grid_view_sort"==r&&(i=i.parentNode),r=e._getClassName(i),-1==r.indexOf("dhx_grid_sort_asc")&&(n="asc");for(var s=0,d=0;d<i.parentNode.childNodes.length;d++)if(i.parentNode.childNodes[d]==i){s=d;break}var o=null;if(e[a].columns[s].template){var l=e[a].columns[s].template;
o=function(e){return l(e.start_date,e.end_date,e)}}else{var _=e[a].columns[s].id;"date"==_&&(_="start_date"),o=function(e){return e[_]}}var h=e[a].columns[s].sort;return"function"!=typeof h&&(h=e._grid.sort_rules[h]||e._grid.sort_rules.str),{dir:n,value:o,rule:h}},e._grid.draw_sort_marker=function(t,a){"dhx_grid_view_sort"==t.className&&(t=t.parentNode),e._grid._sort_marker&&(e._grid._sort_marker.className=e._grid._sort_marker.className.replace(/( )?dhx_grid_sort_(asc|desc)/,""),e._grid._sort_marker.removeChild(e._grid._sort_marker.lastChild)),
t.className+=" dhx_grid_sort_"+a,e._grid._sort_marker=t;var i="<div class='dhx_grid_view_sort' style='left:"+(+t.style.width.replace("px","")-15+t.offsetLeft)+"px'>&nbsp;</div>";t.innerHTML+=i},e._grid.sort_grid=function(t){var t=t||{dir:"desc",value:function(e){return e.start_date},rule:e._grid.sort_rules.date},a=e.get_visible_events();return"desc"==t.dir?a.sort(function(e,a){return t.rule(e,a,t.value)}):a.sort(function(e,a){return-t.rule(e,a,t.value)}),a},e._grid.set_full_view=function(t){if(t){
var a=(e.locale.labels,e._grid._print_grid_header(t));e._els.dhx_cal_header[0].innerHTML=a,e._table_view=!0,e.set_sizes()}},e._grid._calcPadding=function(t,a){var i=(void 0!==t.paddingLeft?1*t.paddingLeft:e[a].defPadding)+(void 0!==t.paddingRight?1*t.paddingRight:e[a].defPadding);return i},e._grid._getStyles=function(e,t){for(var a=[],i="",n=0;t[n];n++)switch(i=t[n]+":",t[n]){case"text-align":e.align&&a.push(i+e.align);break;case"vertical-align":e.valign&&a.push(i+e.valign);break;case"padding-left":
void 0!==e.paddingLeft&&a.push(i+(e.paddingLeft||"0")+"px");break;case"padding-right":void 0!==e.paddingRight&&a.push(i+(e.paddingRight||"0")+"px")}return a},e._grid._fill_grid_tab=function(t,a){for(var i=(e._date,e._grid.sort_grid(a)),n=e[t].columns,r="<div>",s=-2,d=0;d<n.length;d++){var o=e._grid._calcPadding(n[d],t);s+=n[d].width+o,d<n.length-1&&(r+="<div class='dhx_grid_v_border' style='left:"+s+"px'></div>")}r+="</div>",r+="<div class='dhx_grid_area'><table>";for(var d=0;d<i.length;d++)r+=e._grid._print_event_row(i[d],t);
r+="</table></div>",e._els.dhx_cal_data[0].innerHTML=r,e._els.dhx_cal_data[0].lastChild.scrollTop=e._grid._gridScrollTop||0;var l=e._els.dhx_cal_data[0].getElementsByTagName("tr");e._rendered=[];for(var d=0;d<l.length;d++)e._rendered[d]=l[d]},e._grid._print_event_row=function(t,a){var i=[];t.color&&i.push("background:"+t.color),t.textColor&&i.push("color:"+t.textColor),t._text_style&&i.push(t._text_style),e[a].rowHeight&&i.push("height:"+e[a].rowHeight+"px");var n="";i.length&&(n="style='"+i.join(";")+"'");
for(var r=e[a].columns,s=e.templates.event_class(t.start_date,t.end_date,t),d="<tr class='dhx_grid_event"+(s?" "+s:"")+"' event_id='"+t.id+"' "+n+">",o=e._grid._getViewName(a),l=["text-align","vertical-align","padding-left","padding-right"],_=0;_<r.length;_++){var h;h=r[_].template?r[_].template(t.start_date,t.end_date,t):"date"==r[_].id?e.templates[o+"_full_date"](t.start_date,t.end_date,t):"start_date"==r[_].id||"end_date"==r[_].id?e.templates[o+"_single_date"](t[r[_].id]):e.templates[o+"_field"](r[_].id,t);
var c=e._grid._getStyles(r[_],l),u=r[_].css?' class="'+r[_].css+'"':"";d+="<td style='width:"+r[_].width+"px;"+c.join(";")+"' "+u+">"+h+"</td>"}return d+="<td class='dhx_grid_dummy'></td></tr>"},e._grid._print_grid_header=function(t){for(var a="<div class='dhx_grid_line'>",i=e[t].columns,n=[],r=i.length,s=e._obj.clientWidth-2*i.length-20,d=0;d<i.length;d++){var o=1*i[d].initialWidth;isNaN(o)||""===i[d].initialWidth||null===i[d].initialWidth||"boolean"==typeof i[d].initialWidth?n[d]=null:(r--,s-=o,
n[d]=o)}for(var l=Math.floor(s/r),_=["text-align","padding-left","padding-right"],h=0;h<i.length;h++){var c=n[h]?n[h]:l;i[h].width=c-e._grid._calcPadding(i[h],t);var u=e._grid._getStyles(i[h],_);a+="<div style='width:"+(i[h].width-1)+"px;"+u.join(";")+"'>"+(void 0===i[h].label?i[h].id:i[h].label)+"</div>"}return a+="</div>"}});
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_grid_view.js.map