IF EXISTS ( SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[FNAFieldValue ]') AND TYPE IN (N'FN', N'IF', N'TF', N'FS', N'FT') )
    DROP FUNCTION [dbo].[FNAFieldValue ]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FNAFieldValue ] (@udf_id INT )
RETURNS FLOAT
AS
BEGIN
	RETURN 1
END
