/****** Object:  UserDefinedFunction [dbo].[FNAFormulaFormatMaxString]    Script Date: 09/15/2011 11:42:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FNAFormulaFormatMaxString]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[FNAFormulaFormatMaxString]
GO

/****** Object:  UserDefinedFunction [dbo].[FNAFormulaFormatMaxString]    Script Date: 09/15/2011 11:42:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 /**
	Add or Remove dbo.FNA to the function name

	Parameters :
	@formula : Formula string
	@type : Type 'd' to add, 'c'/'r' to remove

	Returns parsed formula string
 */

CREATE FUNCTION [dbo].[FNAFormulaFormatMaxString] (@formula varchar(max),@type char(1))
RETURNS varchar(max) AS  
BEGIN 
	DECLARE @test_formula varchar(max)
	IF @type = 'd'
	BEGIN	
		--return 1
		SET @test_formula = REPLACE(@formula, 'MAX', 'dbo.FNAMax')
		SET @test_formula = REPLACE(@test_formula, 'SUMPRODUCT', 'dbo.FNASUMPRODUCT')
		SET @test_formula = REPLACE(@test_formula, 'DaysInYr', 'dbo.FNADaysInYr')
		SET @test_formula = REPLACE(@test_formula, 'RollingAVG', 'dbo.FNARolling')
		SET @test_formula = REPLACE(@test_formula, 'DynamicCurve', 'dbo.FNADynamicCurve')
		SET @test_formula = REPLACE(@test_formula, 'UDFDetailValue', 'dbo.FNAUDFDetailValue')
		SET @test_formula = REPLACE(@test_formula, 'UDFCurveValue', 'dbo.FNAUDFCurveValue')
		--SET @test_formula = REPLACE(@test_formula, 'Rolling', 'dbo.FNARolling')
		SET @test_formula = REPLACE(@test_formula, 'PeakDmndMeter', 'dbo.FNAPeakDmndMeter')
		SET @test_formula = REPLACE(@test_formula, 'PeakDmd', 'dbo.FNAPeakDmd')
		SET @test_formula = REPLACE(@test_formula, 'MIN', 'dbo.FNAMIN')
		SET @test_formula = REPLACE(@test_formula, 'POWER', 'dbo.FNAPower')	
		SET @test_formula = REPLACE(@test_formula, 'SQRT', 'dbo.FNASqrt')
		SET @test_formula = REPLACE(@test_formula, 'MnthlyRollingAveg', 'dbo.FNAMnthlyRollingAveg')
		SET @test_formula = REPLACE(@test_formula, 'RollingSUM', 'dbo.FNARollingSum')
		SET @test_formula = REPLACE(@test_formula, 'LastMnthValue', 'dbo.FNALastMnthValue')
		SET @test_formula = REPLACE(@test_formula, 'CptMeterVolm', 'dbo.FNACptMeterVolm')
		--SET @test_formula = REPLACE(@test_formula, 'AVG', 'dbo.FNAAvg')
		SET @test_formula = REPLACE(@test_formula, 'MxRwValue', 'dbo.FNAMxRwValue')
		SET @test_formula = REPLACE(@test_formula, 'WghtFixPrice', 'dbo.FNAWghtFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'ImbalanceTotalVol', 'dbo.FNAImbalanceTotalVol')
		SET @test_formula = REPLACE(@test_formula, 'RelativeDailyCurve', 'dbo.FNARelativeDailyCurve')
		SET @test_formula = REPLACE(@test_formula, 'RelativeCurveD', 'dbo.FNARelativeDailyCurve')
		SET @test_formula = REPLACE(@test_formula, 'BookMap', 'dbo.FNABookMap')
		SET @test_formula = REPLACE(@test_formula, 'ActualTotalVol', 'dbo.FNAActualTotalVol')
		--SET @test_formula = REPLACE(@test_formula, 'HCurve', 'dbo.FNAHCurve')
		SET @test_formula = REPLACE(@test_formula, 'DaysInMnth', 'dbo.FNADaysInMnth')
		SET @test_formula = REPLACE(@test_formula, 'Curve15', 'dbo.FNACurve15')
		SET @test_formula = REPLACE(@test_formula, 'Curve30', 'dbo.FNACurve30')
		SET @test_formula = REPLACE(@test_formula, 'CurveD', 'dbo.FNACurveD')
		SET @test_formula = REPLACE(@test_formula, 'CurveY', 'dbo.FNACurveY')
		SET @test_formula = REPLACE(@test_formula, 'CurveH', 'dbo.FNACurveH')
		SET @test_formula = REPLACE(@test_formula, 'CurveM', 'dbo.FNACurve')
		SET @test_formula = REPLACE(@test_formula, 'GetCurveValue', 'dbo.FNAGetCurveValue')
		SET @test_formula = REPLACE(@test_formula, 'adiha_add', '+')
		SET @test_formula = REPLACE(@test_formula, 'adiha_space', ' ')
		SET @test_formula = REPLACE(@test_formula, 'Channel', 'dbo.FNAChannel')
		SET @test_formula = REPLACE(@test_formula, 'INPUT', 'dbo.FNAInput')
		SET @test_formula = REPLACE(@test_formula, 'EMSConv(', 'dbo.FNAEMSConv(')
		SET @test_formula = REPLACE(@test_formula, 'CountRow(', 'dbo.FNACntRw(')		
			SET @test_formula = REPLACE(@test_formula, 'EMSConv', 'dbo.FNAEMSConv')
		SET @test_formula = REPLACE(@test_formula, 'CountRow', 'dbo.FNACntRw')
		--save Row(Undefined) as dbo.FNARow(-1)
		SET @test_formula = REPLACE(@test_formula, 'YearlyContractVolm', 'dbo.FNAYrlyConVolm')
		SET @test_formula = REPLACE(@test_formula, 'YearlySetVolm','dbo.FNAYrlySetVolm')
		SET @test_formula = REPLACE(@test_formula, 'Row(Undefined', 'Row(-1')
		SET @test_formula = REPLACE(@test_formula, 'Row', 'dbo.FNARow')
		SET @test_formula = REPLACE(@test_formula, 'Month', 'dbo.FNAMonth')
		SET @test_formula = REPLACE(@test_formula, 'Year', 'dbo.FNAYear')
		SET @test_formula = REPLACE(@test_formula, 'AnnualVolCOD', 'dbo.FNAAnnualVolCOD') 
		SET @test_formula = REPLACE(@test_formula, 'GeneratorMxHour', 'dbo.FNAGeneratorMxHour') 
		SET @test_formula = REPLACE(@test_formula, 'DPrice', 'dbo.FNADPrice')
		SET @test_formula = REPLACE(@test_formula, 'IsPeak', 'dbo.FNAIsPeak')
		SET @test_formula = REPLACE(@test_formula, 'CorresMnthValue', 'dbo.FNACorresMnthValue')
		SET @test_formula = REPLACE(@test_formula, 'InterruptCalc', 'dbo.FNAInterruptCalc')
		SET @test_formula = REPLACE(@test_formula, 'ContractVol', 'dbo.FNAContractVol')
		SET @test_formula = REPLACE(@test_formula, 'ContractValue', 'dbo.FNAContractValue')
		SET @test_formula = REPLACE(@test_formula, 'CVD', 'dbo.FNACVD')
		SET @test_formula = REPLACE(@test_formula, 'MeterVol(', 'dbo.FNAMeterVol(')
		SET @test_formula = REPLACE(@test_formula, 'HourlyDmd', 'dbo.FNAHourlyDmd')
		SET @test_formula = REPLACE(@test_formula, 'DmdDateTime', 'dbo.FNADmdDateTime')
		SET @test_formula = REPLACE(@test_formula, 'InterruptVol', 'dbo.FNAInterruptVol')
		SET @test_formula = REPLACE(@test_formula, 'WeekDaysInMth', 'dbo.FNAWeekDaysInMnth')
		SET @test_formula = REPLACE(@test_formula, 'CoIncidentPeak', 'dbo.FNACoIncidentPeak')
		SET @test_formula = REPLACE(@test_formula, 'IsInterrupt', 'dbo.FNAIsInterrupt')
		SET @test_formula = REPLACE(@test_formula, 'IntCumulativeMnth', 'dbo.FNAIntCumulativeMnth')
		SET @test_formula = REPLACE(@test_formula, 'IntStartMnth', 'dbo.FNAIntStartMnth')
		SET @test_formula = REPLACE(@test_formula, 'IntStopMnth', 'dbo.FNAIntStopMnth')
		SET @test_formula = REPLACE(@test_formula, 'DailyRollingAveg', 'dbo.FNADailyRollingAveg')
		SET @test_formula = REPLACE(@test_formula, 'DealType', 'dbo.FNADealType')
		SET @test_formula = REPLACE(@test_formula, 'MTMPNL', 'dbo.FNAMTMPNL')
		SET @test_formula = REPLACE(@test_formula, 'MTMSettlement', 'dbo.FNAMTMSettlement')
		SET @test_formula = REPLACE(@test_formula, 'OptionsPremium', 'dbo.FNAOptionsPremium')
		SET @test_formula = REPLACE(@test_formula, 'UDFValue', 'dbo.FNAUDFValue')
		SET @test_formula = REPLACE(@test_formula, 'DealLeg', 'dbo.FNADealLeg')
		SET @test_formula = REPLACE(@test_formula, 'ExPostVolm', 'dbo.FNAExPostVolume')
		SET @test_formula = REPLACE(@test_formula, 'ExAnteVolm', 'dbo.FNAExAnteVolume')
		SET @test_formula = REPLACE(@test_formula, 'ExAntePrice', 'dbo.FNAExAntePrice')
		SET @test_formula = REPLACE(@test_formula, 'ExPostPrice', 'dbo.FNAExPostPrice')
		SET @test_formula = REPLACE(@test_formula, 'LagCurve', 'dbo.FNALagCurve')
		SET @test_formula = REPLACE(@test_formula, 'PriorCurve', 'dbo.FNAPriorCurve')
		SET @test_formula = REPLACE(@test_formula, 'FixedCurve', 'dbo.FNAFixedCurve')
		SET @test_formula = REPLACE(@test_formula, 'WeekDay(', 'dbo.FNAWeekDay(')
		SET @test_formula = REPLACE(@test_formula, 'IsHoliday', 'dbo.FNAIsHoliday')
		SET @test_formula = REPLACE(@test_formula, 'WACOG_Buy', 'dbo.FNAWACOG_Buy')
		SET @test_formula = REPLACE(@test_formula, 'WACOG_Sale', 'dbo.FNAWACOG_Sale')
		SET @test_formula = REPLACE(@test_formula, 'RelativePeriod', 'dbo.FNARelativePeriod')
		SET @test_formula = REPLACE(@test_formula, 'CounterpartyRating', 'dbo.FNACounterpartyRating')
		SET @test_formula = REPLACE(@test_formula, 'CounterpartyMTM', 'dbo.FNACounterpartyMTM')
		SET @test_formula = REPLACE(@test_formula, 'CounterpartyNetPwrPurchase', 'dbo.FNACounterpartyNetPwrPurchase')
		SET @test_formula = REPLACE(@test_formula, 'LoadVolume', 'dbo.FNALoadVolm')
		SET @test_formula = REPLACE(@test_formula, 'LoadVolm', 'dbo.FNALoadVolm')
		SET @test_formula = REPLACE(@test_formula, 'UOMConv','dbo.FNAUOMCOnv')
		SET @test_formula = REPLACE(@test_formula, 'AverageHourlyPrice','dbo.FNAAverageHourlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'AverageHourlyMxPrice','dbo.FNAAverageHourlyMxPrice')
		SET @test_formula = REPLACE(@test_formula, 'AverageHourlyMnPrice','dbo.FNAAverageHourlyMnPrice')
		set @test_formula = REPLACE(@test_formula, 'AVG','dbo.FNAAvg')
		SET @test_formula = REPLACE(@test_formula, 'ImbalanceVol', 'dbo.FNAImbalanceVol')
		SET @test_formula = REPLACE(@test_formula, 'AverageDailyPrice','dbo.FNAAverageDailyPrice')	
		SET @test_formula = REPLACE(@test_formula, 'LocationVol', 'dbo.FNALocationVol')
		SET @test_formula = REPLACE(@test_formula, 'FixedVolm', 'dbo.FNAFixedVolm')
		SET @test_formula = REPLACE(@test_formula, 'DealFixPrice', 'dbo.FNADealFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'PriceMultiplier', 'dbo.FNAPriceMultiplier')
		SET @test_formula = REPLACE(@test_formula, 'DealTotalVolm', 'dbo.FNADealTotalVolm')
		SET @test_formula = REPLACE(@test_formula, 'DealVolm', 'dbo.FNADealVolm')
		SET @test_formula = REPLACE(@test_formula, 'ContractualOnPeakVolm', 'dbo.FNAContractualOnPeakVolm')
		SET @test_formula = REPLACE(@test_formula, 'ContractualOffPeakVolm', 'dbo.FNAContractualOffPeakVolm')
		SET @test_formula = REPLACE(@test_formula, 'DutchTOU', 'dbo.FNADutchTOU')
		SET @test_formula = REPLACE(@test_formula, 'SettlementDate', 'dbo.FNASettlementDate')
		SET @test_formula = REPLACE(@test_formula, 'MnPrice', 'dbo.FNAMnPrice')
		SET @test_formula = REPLACE(@test_formula, 'MxPrice', 'dbo.FNAMxPrice')
		SET @test_formula = REPLACE(@test_formula, 'IF', 'dbo.FNAIF')
		SET @test_formula = REPLACE(@test_formula, 'PeakHours', 'dbo.FNAPeakHours')
		-------------------------------------------------------------
		SET @test_formula = REPLACE(@test_formula, 'DealFVolm', 'dbo.FNADealFVolm')
		SET @test_formula = REPLACE(@test_formula, 'DealFees', 'dbo.FNADealFees')
		SET @test_formula = REPLACE(@test_formula, 'DealSettlement', 'dbo.FNADealSettlement')
		SET @test_formula = REPLACE(@test_formula, 'ShapedVol', 'dbo.FNAShapedVol')
		SET @test_formula = REPLACE(@test_formula, 'StaticCurve', 'dbo.FNAStaticCurve')
		SET @test_formula = REPLACE(@test_formula, 'PhysicalVol', 'dbo.FNAPhysicalVol')
		SET @test_formula = REPLACE(@test_formula, 'FinancialVol', 'dbo.FNAFinancialVol')
		SET @test_formula = REPLACE(@test_formula, 'DealSetPrice', 'dbo.FNADealSetPrice')
		SET @test_formula = REPLACE(@test_formula, 'DealMultiplier', 'dbo.FNADealMultiplier')
		SET @test_formula = REPLACE(@test_formula, 'SettlementVolm', 'dbo.FNASettlementVolm')
		SET @test_formula = REPLACE(@test_formula, 'AllocVolm', 'dbo.FNAAllocVolm')
		SET @test_formula = REPLACE(@test_formula, 'IndexAllocation', 'dbo.FNAIndexAllocation')
		SET @test_formula = REPLACE(@test_formula, 'DealFloatPrice', 'dbo.FNADealFloatPrice')
		SET @test_formula = REPLACE(@test_formula, 'BuySell', 'dbo.FNABuySell')
		SET @test_formula = REPLACE(@test_formula, 'LocationGrid', 'dbo.FNALocationGrid')
		SET @test_formula = REPLACE(@test_formula, 'ContractPriceValue', 'dbo.FNAContractPriceValue')
		SET @test_formula = REPLACE(@test_formula, 'IsYrEnd', 'dbo.FNAIsYrEnd')
		SET @test_formula = REPLACE(@test_formula, 'EOHHours', 'dbo.FNAEOHHours')		
		SET @test_formula = REPLACE(@test_formula, 'PrevEvents','dbo.FNAPrevEvents')
		SET @test_formula = REPLACE(@test_formula, 'DMTMChange', 'dbo.FNADMTMChange')
		SET @test_formula = REPLACE(@test_formula, 'CptCollateral', 'dbo.FNACptCollateral')
		SET @test_formula = REPLACE(@test_formula, 'RateScheduleFee', 'dbo.FNARateScheduleFee')		
		SET @test_formula = REPLACE(@test_formula, 'TotalVolume', 'dbo.FNATotalVolm')	
		SET @test_formula = REPLACE(@test_formula, 'YrCount', 'dbo.FNAYrCount')	
		SET @test_formula = REPLACE(@test_formula, 'UDSql', 'dbo.FNAUDSql')	
		SET @test_formula = REPLACE(@test_formula, 'LocationRegionID', 'dbo.FNALocationRegionID')		
		SET @test_formula = REPLACE(@test_formula, 'CounterpartyRegionID', 'dbo.FNACounterpartyRegionID')
		SET @test_formula = REPLACE(@test_formula, 'FNABookMapName', 'dbo.FNABookMapName')
		SET @test_formula = REPLACE(@test_formula, 'GetID', 'dbo.FNAGetID')
		SET @test_formula = REPLACE(@test_formula, 'VATPercent', 'dbo.FNAVATPercent')	
		SET @test_formula = REPLACE(@test_formula, 'DealStrikePrice', 'dbo.FNADealStrikePrice')	
		SET @test_formula = REPLACE(@test_formula, 'CoIncidentPeak', 'dbo.FNACoIncidentPeak')
		SET @test_formula = REPLACE(@test_formula, 'IsInternalPortfolio', 'dbo.FNAIsInternalPortfolio')
		SET @test_formula = REPLACE(@test_formula, 'ShapedDealPrice', 'dbo.FNAShapedDealPrice')
        SET @test_formula = REPLACE(@test_formula, 'PriceCurve', 'dbo.FNAPriceCurve')       
        SET @test_formula = REPLACE(@test_formula, 'FieldValue', 'dbo.FNAFieldValue')      
		--Emissions Related formula
		SET @test_formula = REPLACE(@test_formula, 'CO2EmissionsValue', 'dbo.FNACO2EmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'SO2EmissionsValue', 'dbo.FNASO2EmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'NOXEmissionsValue', 'dbo.FNANOXEmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'IsSIngleStackBoiler', 'dbo.FNAIsSIngleStackBoiler')	
		SET @test_formula = REPLACE(@test_formula, 'EDRValue','dbo.FNAEDRValue')
		SET @test_formula = REPLACE(@test_formula, 'SourceEmissionsValue','dbo.FNASourceEmissionsValue')
		SET @test_formula = REPLACE(@test_formula, 'EDRHeatInput', 'dbo.FNAEDRHeatInpt')	
		SET @test_formula = REPLACE(@test_formula, 'EMSCoeff', 'dbo.FNAEMSCoeff')	
		SET @test_formula = REPLACE(@test_formula, 'SourceActivity', 'dbo.FNASourceActivity')	
		SET @test_formula = REPLACE(@test_formula, 'AverageCurveValue', 'dbo.FNAAverageCurveValue')	
		SET @test_formula = REPLACE(@test_formula, 'DaysInPeriod', 'dbo.FNADaysInPeriod')
        SET @test_formula = REPLACE(@test_formula, 'GetBookID', 'dbo.FNAGetBookID')
		SET @test_formula = REPLACE(@test_formula, 'ConstantValue', 'dbo.FNAConstantValue')
		SET @test_formula = REPLACE(@test_formula, 'AveragePrice', 'dbo.FNAAveragePrice')
        SET @test_formula = REPLACE(@test_formula, 'FieldValue(', 'dbo.FNAFieldValue(')
 		SET @test_formula = REPLACE(@test_formula, 'GetUserDefinedValue(', 'dbo.FNAGetUserDefinedValue(')
        SET @test_formula = REPLACE(@test_formula, 'GetRelativeCurveID(', 'dbo.FNAGetRelativeCurveID(')
		SET @test_formula = REPLACE(@test_formula, 'Escalation(', 'dbo.FNAEscalation(')
        SET @test_formula = REPLACE('['+@test_formula, '[Value', 'dbo.FNAValue')
		SET @test_formula = replace(@test_formula,'[','')
		--set @test_formula=replace(@test_formula,'MIN','dbo.FNAMIN')
		SET @test_formula = REPLACE(@test_formula, 'GetLogicalValue', 'dbo.FNAGetLogicalValue')
        SET @test_formula = REPLACE(@test_formula, 'AverageYrlyPrice', 'dbo.FNAAverageYrlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'AverageMnthlyPrice', 'dbo.FNAAverageMnthlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'IsNull', 'dbo.FNAIsNull')      
		SET @test_formula = REPLACE(@test_formula, 'AverageQVol', 'dbo.FNAAverageQVol')
		SET @test_formula = REPLACE(@test_formula, 'AverageQtrDailyPrice', 'dbo.FNAAverageQtrDailyPrice')
		SET @test_formula = REPLACE(@test_formula, 'PriorInvoiceAdjustment', 'dbo.FNAPriorInvoiceAdjustment')
		SET @test_formula = REPLACE(@test_formula, 'Floor', 'dbo.FNAFloor')
		SET @test_formula = REPLACE(@test_formula, 'Ceiling', 'dbo.FNACeiling')
		SET @test_formula = REPLACE(@test_formula, 'GetTimeSeriesData', 'dbo.FNAGetTimeSeriesData')
		SET @test_formula = REPLACE(@test_formula, 'WACOGLocPur', 'dbo.FNAWACOGLocPur')
		SET @test_formula = REPLACE(@test_formula, 'WACOGWD', 'dbo.FNAWACOGWD')
		SET @test_formula = REPLACE(@test_formula, 'PriceAdder', 'dbo.FNAPriceAdder')
		SET @test_formula = REPLACE(@test_formula, 'PriorFinalizedAmount', 'dbo.FNAPriorFinalizedAmount')
		SET @test_formula = REPLACE(@test_formula, 'PriorFinalizedVol', 'dbo.FNAPriorFinalizedVol')
		SET @test_formula = REPLACE(@test_formula, 'GetUKRates', 'dbo.FNAGetUKRates')
		SET @test_formula = REPLACE(@test_formula, 'MeterVolmUK', 'dbo.FNAMeterVolmUK')
		SET @test_formula = REPLACE(@test_formula, 'GetVatAmount', 'dbo.FNAGetVatAmount')
		SET @test_formula = REPLACE(@test_formula, 'DaysInContractMnth', 'dbo.FNADaysInContractMnth')
		SET @test_formula = REPLACE(@test_formula, 'DeriveDayAhead', 'dbo.FNADeriveDayAhead')
		SET @test_formula = REPLACE(@test_formula, 'GetGMContractFee', 'dbo.FNAGetGMContractFee')
		SET @test_formula = REPLACE(@test_formula, 'ActualVolume', 'dbo.FNAActualVolume')
		SET @test_formula = REPLACE(@test_formula, 'ScheduleVolume', 'dbo.FNAScheduleVolume')
		SET @test_formula = REPLACE(@test_formula, 'BestAvailableVolume', 'dbo.FNABestAvailableVolume')

		SET @test_formula = REPLACE(@test_formula, 'ContractFixPrice', 'dbo.FNAContractFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'ContractFees', 'dbo.FNAContractFees')
		SET @test_formula = REPLACE(@test_formula, 'GetMeteredVolm', 'dbo.FNAGetMeteredVolm')
		SET @test_formula = REPLACE(@test_formula, 'PreviousInvoicedVolume', 'dbo.FNAPreviousInvoicedVolume')
		SET @test_formula = REPLACE(@test_formula, 'PreviousInvoicedAmount', 'dbo.FNAPreviousInvoicedAmount')
		SET @test_formula = REPLACE(@test_formula, 'GetWACOGPoolPrice', 'dbo.FNAGetWACOGPoolPrice')
		SET @test_formula = REPLACE(@test_formula, 'StorageContractPrice', 'dbo.FNAStorageContractPrice')
		SET @test_formula = REPLACE(@test_formula, 'ContractualQualityValue', 'dbo.FNAContractualQualityValue')		
		SET @test_formula = REPLACE(@test_formula, 'ActualizedQualityValue', 'dbo.FNAActualizedQualityValue')			
	end
	else if @type in  ('c', 'r')
	begin
		SET @formula =  dbo.[FNAFormulaResolveParamSeperator](@formula, 'v');

		SET @test_formula = REPLACE(@formula, 'dbo.FNAMax', 'MAX')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASUMPRODUCT', 'SUMPRODUCT')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADaysInYr', 'DaysInYr')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADynamicCurve', 'DynamicCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAUDFDetailValue', 'UDFDetailValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAUDFCurveValue', 'UDFCurveValue')
		--SET @test_formula = REPLACE(@test_formula, 'dbo.FNARolling', 'Rolling')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPeakDmndMeter', 'PeakPeakDmndMeter')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPeakDmd', 'PeakDmd')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMIN', 'MIN')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPower', 'POWER')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASqrt', 'SQRT')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMnthlyRollingAveg', 'MnthlyRollingAveg')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARollingSum', 'RollingSUM')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARolling', 'RollingAVG')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALastMnthValue', 'LastMnthValue')

		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAvg', 'AVG')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWghtFixPrice', 'WghtFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAImbalanceVol','ImbalanceVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACptMeterVolm','CptMeterVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADaysInMnth', 'DaysInMnth')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAYrlyConVolm','YearlyContractVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAYrlySetVolm','YearlySetVolm')
		--SET @test_formula = REPLACE(@test_formula, 'dbo.FNAHCurve', 'HCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMxRwValue', 'MxRwValue')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurve15', 'Curve15')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurve30', 'Curve30')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurveH', 'CurveH')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurveD', 'CurveD')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurveY', 'CurveY')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACurve', 'CurveM')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetCurveValue', 'GetCurveValue')
		SET @test_formula = REPLACE(@test_formula, 'adiha_add', '+')
		SET @test_formula = REPLACE(@test_formula, 'adiha_space', ' ')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAChannel', 'Channel')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAInput', 'INPUT')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEMSConv', 'EMSConv')
		--display dbo.FNARow(-1) as Row(Undefined)
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARow(-1', 'dbo.FNARow(Undefined')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARow', 'Row')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMonth', 'Month')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAYear', 'Year')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAnnualVolCOD', 'AnnualVolCOD') 
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGeneratorMxHour', 'GeneratorMxHour') 
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADPrice', 'DPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsPeak', 'IsPeak')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACorresMnthValue', 'CorresMnthValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAInterruptCalc', 'InterruptCalc')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractVol', 'ContractVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractValue', 'ContractValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACVD', 'CVD')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMeterVol(', 'MeterVol(')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAHourlyDmd', 'HourlyDmd')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADmdDateTime', 'DmdDateTime')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAInterruptVol', 'InterruptVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWeekDaysInMnth', 'WeekDaysInMth')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACoIncidentPeak', 'CoIncidentPeak')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsInterrupt', 'IsInterrupt')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIntCumulativeMnth', 'IntCumulativeMnth')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIntStartMnth', 'IntStartMnth')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIntStopMnth', 'IntEndMnth')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADailyRollingAveg', 'DailyRollingAveg')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealType', 'DealType')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMTMPNL', 'MTMPNL')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMTMSettlement', 'MTMSettlement')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAOptionsPremium', 'OptionsPremium')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAUDFValue', 'UDFValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealLeg', 'DealLeg')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAExPostVolume', 'ExPostVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAExAnteVolume', 'ExAnteVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAExAntePrice', 'ExAntePrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAExPostPrice', 'ExPostPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALagCurve', 'LagCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriorCurve', 'PriorCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAFixedCurve', 'FixedCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWeekDay(', 'WeekDay(')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsHoliday', 'IsHoliday')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWACOG_Buy', 'WACOG_Buy')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWACOG_Sale', 'WACOG_Sale')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARelativePeriod', 'RelativePeriod')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACounterpartyRating', 'CounterpartyRating')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACounterpartyMTM', 'CounterpartyMTM')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealFixPrice', 'DealFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriceMultiplier', 'PriceMultiplier')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACounterpartyNetPwrPurchase', 'CounterpartyNetPwrPurchase')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALoadVolm', 'LoadVolume')
		set @test_formula = REPLACE(@test_formula, 'dbo.FNAUOMCOnv','UOMConv')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageHourlyPrice','AverageHourlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageHourlyMxPrice','AverageHourlyMxPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageHourlyMnPrice','AverageHourlyMnPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageDailyPrice','AverageDailyPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALocationVol','LocationVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAImbalanceTotalVol','ImbalanceTotalVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAFixedVolm','FixedVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealTotalVolm','DealTotalVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealVolm', 'DealVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractualOnPeakVolm','ContractualOnPeakVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractualOffPeakVolm','ContractualOffPeakVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADutchTOU','DutchTOU')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASettlementDate', 'SettlementDate')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMnPrice','MnPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMxPrice','MxPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIF','IF')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPeakHours','PeakHours')
		SET @test_formula = REPLACE(@test_formula,  'dbo.FNAUDFCurveValue','UDFCurveValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealFees','DealFees')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealFVolm','DealFVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealSettlement','DealSettlement')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAShapedVol','ShapedVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAStaticCurve','StaticCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPhysicalVol', 'PhysicalVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAFinancialVol','FinancialVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealSetPrice','DealSetPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealMultiplier','DealMultiplier')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASettlementVolm', 'SettlementVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAllocVolm','AllocVolm')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIndexAllocation','IndexAllocation')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealFloatPrice','DealFloatPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNABuySell','BuySell')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALocationGrid','LocationGrid')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractPriceValue','ContractPriceValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsYrEnd','IsYrEnd')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEOHHours', 'EOHHours')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPrevEvents', 'PrevEvents')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACntRw','CountRow')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADMTMChange','DMTMChange')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACptCollateral','CptCollateral')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARateScheduleFee','RateScheduleFee')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNARelativeDailyCurve','RelativeCurveD')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNABookMap','BookMap')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNATotalVolm','TotalVolume')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAActualTotalVol',  'ActualTotalVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAYrCount', 'YrCount')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAUDSql','UDSql')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNALocationRegionID','LocationRegionID')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACounterpartyRegionID','CounterpartyRegionID')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNABookMapName','FNABookMapName')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetID','GetID')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAVATPercent', 'VATPercent')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADealStrikePrice', 'DealStrikePrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACO2EmissionsValue','CO2EmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASO2EmissionsValue','SO2EmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNANOXEmissionsValue','NOXEmissionsValue')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEDRHeatInpt','EDRHeatInput')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsSIngleStackBoiler','IsSIngleStackBoiler')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEDRValue','EDRValue')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASourceEmissionsValue','SourceEmissionsValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEMSCoeff', 'EMSCoeff')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNASourceActivity', 'SourceActivity')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsInternalPortfolio', 'IsInternalPortfolio')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageCurveValue','AverageCurveValue')		
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNAShapedDealPrice', 'ShapedDealPrice')
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriceCurve', 'PriceCurve')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAveragePrice', 'AveragePrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAFieldValue', 'FieldValue')
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNADaysInPeriod', 'DaysInPeriod')
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetBookID', 'GetBookID')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAConstantValue', 'ConstantValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAValue', 'Value')
	
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNAFieldValue(', 'FieldValue(')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetLogicalValue', 'GetLogicalValue')
        SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageYrlyPrice', 'AverageYrlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageMnthlyPrice', 'AverageMnthlyPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAIsNull', 'IsNull')  
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAAverageQVol', 'AverageQVol')  
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetUserDefinedValue(', 'GetUserDefinedValue(')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetRelativeCurveID(', 'GetRelativeCurveID(')		
		SET @test_formula = REPLACE(@test_formula,  'dbo.FNAFloor(','Floor')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNACeiling', 'Ceiling')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAEscalation', 'Escalation(')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAWACOGPrice(','WACOGPrice(')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetTimeSeriesData','GetTimeSeriesData')
		SET @test_formula = REPLACE(@test_formula,  'dbo.FNAWACOGLocPur','WACOGLocPur')
		SET @test_formula = REPLACE(@test_formula,  'dbo.FNAWACOGWD','WACOGWD')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriceAdder', 'PriceAdder')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriorFinalizedAmount','PriorFinalizedAmount')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPriorFinalizedVol','PriorFinalizedVol')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetUKRates','GetUKRates')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAMeterVolmUK','MeterVolmUK')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetVatAmount','GetVatAmount')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADaysInContractMnth','DaysInContractMnth')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetMeteredVolm', 'GetMeteredVolm')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPreviousInvoicedVolume', 'PreviousInvoicedVolume')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAPreviousInvoicedAmount', 'PreviousInvoicedAmount')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADaysInContractMnth','DaysInContractMnth')		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNADeriveDayAhead', 'DeriveDayAhead')	
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetGMContractFee', 'GetGMContractFee')			
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAActualVolume', 'ActualVolume')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAScheduleVolume', 'ScheduleVolume')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNABestAvailableVolume', 'BestAvailableVolume')
		
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractFixPrice', 'ContractFixPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractFees', 'ContractFees')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAGetWACOGPoolPrice', 'GetWACOGPoolPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAStorageContractPrice', 'StorageContractPrice')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAContractualQualityValue', 'ContractualQualityValue')
		SET @test_formula = REPLACE(@test_formula, 'dbo.FNAActualizedQualityValue', 'ActualizedQualityValue')

			END
	RETURN @test_formula
END



GO