SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[FNAGetWACOGPoolPrice]') AND TYPE IN (N'FN', N'IF', N'TF', N'FS', N'FT'))
	DROP FUNCTION [dbo].[FNAGetWACOGPoolPrice]
GO

CREATE FUNCTION [dbo].[FNAGetWACOGPoolPrice](@wacog_group_id INT)
	RETURNS FLOAT
AS
BEGIN
	RETURN 1
END
GO



