SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS(SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[FNAGetBookID]') AND TYPE IN (N'FN', N'IF', N'TF', N'FS', N'FT'))
	DROP FUNCTION [dbo].[FNAGetBookID]
GO

CREATE FUNCTION [dbo].[FNAGetBookID](@source_book_id INT)
	RETURNS INT
AS
BEGIN
	RETURN 1
END
GO