IF OBJECT_ID(N'FNAIsNull', N'FN') IS NOT NULL
    DROP FUNCTION [dbo].[FNAIsNull]
 GO 

CREATE FUNCTION [dbo].[FNAIsNull] (
	@arg1  VARCHAR(5000),
	@arg2  VARCHAR(5000)
)
RETURNS INT
AS
BEGIN
	RETURN 1
END