IF OBJECT_ID(N'FNASqrt', N'FN') IS NOT NULL
    DROP FUNCTION [dbo].[FNASqrt]
GO
 
CREATE FUNCTION [dbo].[FNASqrt]
(
	@arg1 FLOAT
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @x AS FLOAT
	SET @x = SQRT(@arg1)
	RETURN @x
END